// -*- c++ -*-

#pragma once

#include "HIDTables.h"
#include "kaleidoscope/Key.h"


namespace kaleidoscope {

// This namespace is for storing constants of type `Key`. The leading `c` stands for
// `constant` or `const`
// `const Key` object.
namespace cKey {

namespace consumer {

const Key NumericKeyPad = Key::consumerKey(HID_CONSUMER_NUMERIC_KEY_PAD);
const Key ProgrammableButtons = Key::consumerKey(HID_CONSUMER_PROGRAMMABLE_BUTTONS);
const Key MicrophoneCa = Key::consumerKey(HID_CONSUMER_MICROPHONE_CA);
const Key HeadphoneCa = Key::consumerKey(HID_CONSUMER_HEADPHONE_CA);
const Key GraphicEqualizerCa = Key::consumerKey(HID_CONSUMER_GRAPHIC_EQUALIZER_CA);

const Key Plus10 = Key::consumerKey(HID_CONSUMER_PLUS_10);
const Key Plus100 = Key::consumerKey(HID_CONSUMER_PLUS_100);
const Key AMSlashPM = Key::consumerKey(HID_CONSUMER_AM_SLASH_PM);

const Key Power = Key::consumerKey(HID_CONSUMER_POWER);
const Key Reset = Key::consumerKey(HID_CONSUMER_RESET);
const Key Sleep = Key::consumerKey(HID_CONSUMER_SLEEP);
const Key Sleep_After = Key::consumerKey(HID_CONSUMER_SLEEP_AFTER);
const Key Sleep_Mode = Key::consumerKey(HID_CONSUMER_SLEEP_MODE);
const Key Illumination = Key::consumerKey(HID_CONSUMER_ILLUMINATION);
const Key Function_Buttons = Key::consumerKey(HID_CONSUMER_FUNCTION_BUTTONS);

const Key Menu = Key::consumerKey(HID_CONSUMER_MENU);
const Key MenuPick = Key::consumerKey(HID_CONSUMER_MENU_PICK);
const Key MenuUp = Key::consumerKey(HID_CONSUMER_MENU_UP);
const Key MenuDown = Key::consumerKey(HID_CONSUMER_MENU_DOWN);
const Key MenuLeft = Key::consumerKey(HID_CONSUMER_MENU_LEFT);
const Key MenuRight = Key::consumerKey(HID_CONSUMER_MENU_RIGHT);
const Key MenuEscape = Key::consumerKey(HID_CONSUMER_MENU_ESCAPE);
const Key MenuValueIncrease = Key::consumerKey(HID_CONSUMER_MENU_VALUE_INCREASE);
const Key MenuValueDecrease = Key::consumerKey(HID_CONSUMER_MENU_VALUE_DECREASE);

const Key DataOnScreen = Key::consumerKey(HID_CONSUMER_DATA_ON_SCREEN);
const Key ClosedCaption = Key::consumerKey(HID_CONSUMER_CLOSED_CAPTION);
const Key ClosedCaptionSelect = Key::consumerKey(HID_CONSUMER_CLOSED_CAPTION_SELECT);
const Key VCRSlashTV = Key::consumerKey(HID_CONSUMER_VCR_SLASH_TV);
const Key BroadcastMode = Key::consumerKey(HID_CONSUMER_BROADCAST_MODE);
const Key SNapshot = Key::consumerKey(HID_CONSUMER_SNAPSHOT);
const Key Still = Key::consumerKey(HID_CONSUMER_STILL);

const Key Selection = Key::consumerKey(HID_CONSUMER_SELECTION);
const Key AssignSelection = Key::consumerKey(HID_CONSUMER_ASSIGN_SELECTION);
const Key ModeStep = Key::consumerKey(HID_CONSUMER_MODE_STEP);
const Key RecallLast = Key::consumerKey(HID_CONSUMER_RECALL_LAST);
const Key EnterChannel = Key::consumerKey(HID_CONSUMER_ENTER_CHANNEL);
const Key OrderMovie = Key::consumerKey(HID_CONSUMER_ORDER_MOVIE);
const Key Channel = Key::consumerKey(HID_CONSUMER_CHANNEL);
const Key MediaSelection = Key::consumerKey(HID_CONSUMER_MEDIA_SELECTION);
const Key MediaSelectComputer = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_COMPUTER);
const Key MediaSelectTV = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_TV);
const Key MediaSelectWww = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_WWW);
const Key MediaSelectDvd = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_DVD);
const Key MediaSelectTelephone = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_TELEPHONE);
const Key MediaSelectProgramGuide = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_PROGRAM_GUIDE);
const Key MediaSelectVideoPhone = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_VIDEO_PHONE);
const Key MediaSelectGames = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_GAMES);
const Key MediaSelectMessages = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_MESSAGES);
const Key MediaSelectCd = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_CD);
const Key MediaSelectVcr = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_VCR);
const Key MediaSelectTuner = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_TUNER);
const Key Quit = Key::consumerKey(HID_CONSUMER_QUIT);
const Key Help = Key::consumerKey(HID_CONSUMER_HELP);
const Key MediaSelectTape = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_TAPE);
const Key MediaSelectCable = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_CABLE);
const Key MediaSelectSatellite = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_SATELLITE);
const Key MediaSelectSecurity = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_SECURITY);
const Key MediaSelectHome = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_HOME);
const Key MediaSelectCall = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_CALL);
const Key ChannelIncrement = Key::consumerKey(HID_CONSUMER_CHANNEL_INCREMENT);
const Key ChannelDecrement = Key::consumerKey(HID_CONSUMER_CHANNEL_DECREMENT);
const Key MediaSelectSap = Key::consumerKey(HID_CONSUMER_MEDIA_SELECT_SAP);

const Key VcrPlus = Key::consumerKey(HID_CONSUMER_VCR_PLUS);
const Key Once = Key::consumerKey(HID_CONSUMER_ONCE);
const Key Daily = Key::consumerKey(HID_CONSUMER_DAILY);
const Key Weekly = Key::consumerKey(HID_CONSUMER_WEEKLY);
const Key Monthly = Key::consumerKey(HID_CONSUMER_MONTHLY);

const Key Play = Key::consumerKey(HID_CONSUMER_PLAY);
const Key Pause = Key::consumerKey(HID_CONSUMER_PAUSE);
const Key Record = Key::consumerKey(HID_CONSUMER_RECORD);
const Key FastForward = Key::consumerKey(HID_CONSUMER_FAST_FORWARD);
const Key Rewind = Key::consumerKey(HID_CONSUMER_REWIND);
const Key ScanNextTrack = Key::consumerKey(HID_CONSUMER_SCAN_NEXT_TRACK);
const Key ScanPreviousTrack = Key::consumerKey(HID_CONSUMER_SCAN_PREVIOUS_TRACK);
const Key Stop = Key::consumerKey(HID_CONSUMER_STOP);
const Key Eject = Key::consumerKey(HID_CONSUMER_EJECT);
const Key RandomPlay = Key::consumerKey(HID_CONSUMER_RANDOM_PLAY);
const Key SelectDisc = Key::consumerKey(HID_CONSUMER_SELECT_DISC);
const Key EnterDiscMc = Key::consumerKey(HID_CONSUMER_ENTER_DISC_MC);
const Key Repeat = Key::consumerKey(HID_CONSUMER_REPEAT);
const Key Tracking = Key::consumerKey(HID_CONSUMER_TRACKING);
const Key Track_Normal = Key::consumerKey(HID_CONSUMER_TRACK_NORMAL);
const Key SlowTracking = Key::consumerKey(HID_CONSUMER_SLOW_TRACKING);
const Key FrameForward = Key::consumerKey(HID_CONSUMER_FRAME_FORWARD);
const Key FrameBack = Key::consumerKey(HID_CONSUMER_FRAME_BACK);
const Key Mark = Key::consumerKey(HID_CONSUMER_MARK);
const Key ClearMark = Key::consumerKey(HID_CONSUMER_CLEAR_MARK);
const Key RepeatFromMark = Key::consumerKey(HID_CONSUMER_REPEAT_FROM_MARK);
const Key ReturnTo_Mark = Key::consumerKey(HID_CONSUMER_RETURN_TO_MARK);
const Key SearchMarkForward = Key::consumerKey(HID_CONSUMER_SEARCH_MARK_FORWARD);
const Key SearchMarkBackwards = Key::consumerKey(HID_CONSUMER_SEARCH_MARK_BACKWARDS);
const Key CounterReset = Key::consumerKey(HID_CONSUMER_COUNTER_RESET);
const Key ShowCounter = Key::consumerKey(HID_CONSUMER_SHOW_COUNTER);
const Key TrackingIncrement = Key::consumerKey(HID_CONSUMER_TRACKING_INCREMENT);
const Key TrackingDecrement = Key::consumerKey(HID_CONSUMER_TRACKING_DECREMENT);
const Key StopSlashEject = Key::consumerKey(HID_CONSUMER_STOP_SLASH_EJECT);
const Key PlaySlashPause = Key::consumerKey(HID_CONSUMER_PLAY_SLASH_PAUSE);
const Key PlaySlashSkip = Key::consumerKey(HID_CONSUMER_PLAY_SLASH_SKIP);
const Key Volume = Key::consumerKey(HID_CONSUMER_VOLUME);
const Key Balance = Key::consumerKey(HID_CONSUMER_BALANCE);
const Key Mute = Key::consumerKey(HID_CONSUMER_MUTE);
const Key Bass = Key::consumerKey(HID_CONSUMER_BASS);
const Key Treble = Key::consumerKey(HID_CONSUMER_TREBLE);
const Key BassBoost = Key::consumerKey(HID_CONSUMER_BASS_BOOST);
const Key SurroundMode = Key::consumerKey(HID_CONSUMER_SURROUND_MODE);
const Key Loudness = Key::consumerKey(HID_CONSUMER_LOUDNESS);
const Key Mpx = Key::consumerKey(HID_CONSUMER_MPX);
const Key VolumeIncrement = Key::consumerKey(HID_CONSUMER_VOLUME_INCREMENT);


const Key VolumeDecrement = Key::consumerKey(HID_CONSUMER_VOLUME_DECREMENT);

const Key SpeedSelect = Key::consumerKey(HID_CONSUMER_SPEED_SELECT);
const Key PlaybackSpeed = Key::consumerKey(HID_CONSUMER_PLAYBACK_SPEED);
const Key StandardPlay = Key::consumerKey(HID_CONSUMER_STANDARD_PLAY);
const Key LongPlay = Key::consumerKey(HID_CONSUMER_LONG_PLAY);
const Key ExtendedPlay = Key::consumerKey(HID_CONSUMER_EXTENDED_PLAY);
const Key Slow = Key::consumerKey(HID_CONSUMER_SLOW);

const Key FanEnable = Key::consumerKey(HID_CONSUMER_FAN_ENABLE);
const Key FanSpeed = Key::consumerKey(HID_CONSUMER_FAN_SPEED);
const Key LightEnable = Key::consumerKey(HID_CONSUMER_LIGHT_ENABLE);
const Key LightIlluminationLevel = Key::consumerKey(HID_CONSUMER_LIGHT_ILLUMINATION_LEVEL);
const Key ClimateControlEnable = Key::consumerKey(HID_CONSUMER_CLIMATE_CONTROL_ENABLE);
const Key RoomTemperature = Key::consumerKey(HID_CONSUMER_ROOM_TEMPERATURE);
const Key SecurityEnable = Key::consumerKey(HID_CONSUMER_SECURITY_ENABLE);
const Key FireAlarm = Key::consumerKey(HID_CONSUMER_FIRE_ALARM);
const Key PoliceAlarm = Key::consumerKey(HID_CONSUMER_POLICE_ALARM);
const Key Proximity = Key::consumerKey(HID_CONSUMER_PROXIMITY);
const Key Motion = Key::consumerKey(HID_CONSUMER_MOTION);
const Key DuressAlarm = Key::consumerKey(HID_CONSUMER_DURESS_ALARM);
const Key HoldupAlarm = Key::consumerKey(HID_CONSUMER_HOLDUP_ALARM);
const Key MedicalAlarm = Key::consumerKey(HID_CONSUMER_MEDICAL_ALARM);

const Key BalanceRight = Key::consumerKey(HID_CONSUMER_BALANCE_RIGHT);
const Key BalanceLeft = Key::consumerKey(HID_CONSUMER_BALANCE_LEFT);
const Key BassIncrement = Key::consumerKey(HID_CONSUMER_BASS_INCREMENT);
const Key BassDecrement = Key::consumerKey(HID_CONSUMER_BASS_DECREMENT);
const Key TrebleIncrement = Key::consumerKey(HID_CONSUMER_TREBLE_INCREMENT);
const Key TrebleDecrement = Key::consumerKey(HID_CONSUMER_TREBLE_DECREMENT);

const Key SpeakerSystem = Key::consumerKey(HID_CONSUMER_SPEAKER_SYSTEM);
const Key ChannelLeft = Key::consumerKey(HID_CONSUMER_CHANNEL_LEFT);
const Key ChannelRight = Key::consumerKey(HID_CONSUMER_CHANNEL_RIGHT);
const Key ChannelCenter = Key::consumerKey(HID_CONSUMER_CHANNEL_CENTER);
const Key ChannelFront = Key::consumerKey(HID_CONSUMER_CHANNEL_FRONT);
const Key ChannelCenterFront = Key::consumerKey(HID_CONSUMER_CHANNEL_CENTER_FRONT);
const Key ChannelSide = Key::consumerKey(HID_CONSUMER_CHANNEL_SIDE);
const Key ChannelSurround = Key::consumerKey(HID_CONSUMER_CHANNEL_SURROUND);
const Key ChannelLowFrequencyEnhancement = Key::consumerKey(HID_CONSUMER_CHANNEL_LOW_FREQUENCY_ENHANCEMENT);
const Key ChannelTop = Key::consumerKey(HID_CONSUMER_CHANNEL_TOP);
const Key ChannelUnknown = Key::consumerKey(HID_CONSUMER_CHANNEL_UNKNOWN);

const Key SubChannel = Key::consumerKey(HID_CONSUMER_SUB_CHANNEL);
const Key SubChannelIncrement = Key::consumerKey(HID_CONSUMER_SUB_CHANNEL_INCREMENT);
const Key SubChannelDecrement = Key::consumerKey(HID_CONSUMER_SUB_CHANNEL_DECREMENT);
const Key AlternateAudioIncrement = Key::consumerKey(HID_CONSUMER_ALTERNATE_AUDIO_INCREMENT);
const Key AlternateAudioDecrement = Key::consumerKey(HID_CONSUMER_ALTERNATE_AUDIO_DECREMENT);

const Key Application_Launch_Buttons = Key::consumerKey(HID_CONSUMER_APPLICATION_LAUNCH_BUTTONS);
const Key AL_Launch_Button_Configuration_Tool = Key::consumerKey(HID_CONSUMER_AL_LAUNCH_BUTTON_CONFIGURATION_TOOL);
const Key AL_Programmable_Button_Configuration = Key::consumerKey(HID_CONSUMER_AL_PROGRAMMABLE_BUTTON_CONFIGURATION);
const Key AL_Consumer_Control_Configuration = Key::consumerKey(HID_CONSUMER_AL_CONSUMER_CONTROL_CONFIGURATION);
const Key AL_Word_Processor = Key::consumerKey(HID_CONSUMER_AL_WORD_PROCESSOR);
const Key AL_Text_Editor = Key::consumerKey(HID_CONSUMER_AL_TEXT_EDITOR);
const Key AL_Spreadsheet = Key::consumerKey(HID_CONSUMER_AL_SPREADSHEET);
const Key AL_Graphics_Editor = Key::consumerKey(HID_CONSUMER_AL_GRAPHICS_EDITOR);
const Key AL_Presentation_App = Key::consumerKey(HID_CONSUMER_AL_PRESENTATION_APP);
const Key AL_Database_App = Key::consumerKey(HID_CONSUMER_AL_DATABASE_APP);
const Key AL_Email_Reader = Key::consumerKey(HID_CONSUMER_AL_EMAIL_READER);
const Key AL_Newsreader = Key::consumerKey(HID_CONSUMER_AL_NEWSREADER);
const Key AL_Voicemail = Key::consumerKey(HID_CONSUMER_AL_VOICEMAIL);
const Key AL_Contacts_Slash_Address_Book = Key::consumerKey(HID_CONSUMER_AL_CONTACTS_SLASH_ADDRESS_BOOK);
const Key AL_Calendar_Slash_Schedule = Key::consumerKey(HID_CONSUMER_AL_CALENDAR_SLASH_SCHEDULE);
const Key AL_Task_Slash_Project_Manager = Key::consumerKey(HID_CONSUMER_AL_TASK_SLASH_PROJECT_MANAGER);
const Key AL_Log_Slash_Journal_Slash_Timecard = Key::consumerKey(HID_CONSUMER_AL_LOG_SLASH_JOURNAL_SLASH_TIMECARD);
const Key AL_Checkbook_Slash_Finance = Key::consumerKey(HID_CONSUMER_AL_CHECKBOOK_SLASH_FINANCE);
const Key AL_Calculator = Key::consumerKey(HID_CONSUMER_AL_CALCULATOR);
const Key AL_AVCaptureSlashPlayback = Key::consumerKey(HID_CONSUMER_AL_A_SLASH_V_CAPTURE_SLASH_PLAYBACK);
const Key AL_Local_MachineBrowser = Key::consumerKey(HID_CONSUMER_AL_LOCAL_MACHINE_BROWSER);
const Key AL_Lan_SlashWanBrowser = Key::consumerKey(HID_CONSUMER_AL_LAN_SLASH_WAN_BROWSER);
const Key AL_InternetBrowser = Key::consumerKey(HID_CONSUMER_AL_INTERNET_BROWSER);
const Key AL_RemoteNetworkingSlashIspConnect = Key::consumerKey(HID_CONSUMER_AL_REMOTE_NETWORKING_SLASH_ISP_CONNECT);
const Key AL_NetworkConference = Key::consumerKey(HID_CONSUMER_AL_NETWORK_CONFERENCE);
const Key AL_NetworkChat = Key::consumerKey(HID_CONSUMER_AL_NETWORK_CHAT);
const Key AL_TelephonySlashDialer = Key::consumerKey(HID_CONSUMER_AL_TELEPHONY_SLASH_DIALER);
const Key AL_Logon = Key::consumerKey(HID_CONSUMER_AL_LOGON);
const Key AL_Logoff = Key::consumerKey(HID_CONSUMER_AL_LOGOFF);
const Key AL_LogonSlashLogoff = Key::consumerKey(HID_CONSUMER_AL_LOGON_SLASH_LOGOFF);
const Key AL_TerminalLockSlashScreensaver = Key::consumerKey(HID_CONSUMER_AL_TERMINAL_LOCK_SLASH_SCREENSAVER);
const Key AL_ControlPanel = Key::consumerKey(HID_CONSUMER_AL_CONTROL_PANEL);
const Key AL_CommandLineProcessorSlashRun = Key::consumerKey(HID_CONSUMER_AL_COMMAND_LINE_PROCESSOR_SLASH_RUN);
const Key AL_ProcessSlashTask_Manager = Key::consumerKey(HID_CONSUMER_AL_PROCESS_SLASH_TASK_MANAGER);
const Key AL_SelectTaskSlashApplication = Key::consumerKey(HID_CONSUMER_AL_SELECT_TASK_SLASH_APPLICATION);
const Key AL_NextTaskSlashApplication = Key::consumerKey(HID_CONSUMER_AL_NEXT_TASK_SLASH_APPLICATION);
const Key AL_PreviousTaskSlashApplication = Key::consumerKey(HID_CONSUMER_AL_PREVIOUS_TASK_SLASH_APPLICATION);
const Key AL_PreemptiveHaltTaskSlashApplication = Key::consumerKey(HID_CONSUMER_AL_PREEMPTIVE_HALT_TASK_SLASH_APPLICATION);
const Key AL_IntegratedHelpCenter = Key::consumerKey(HID_CONSUMER_AL_INTEGRATED_HELP_CENTER);
const Key AL_Documents = Key::consumerKey(HID_CONSUMER_AL_DOCUMENTS);
const Key AL_Thesaurus = Key::consumerKey(HID_CONSUMER_AL_THESAURUS);
const Key AL_Dictionary = Key::consumerKey(HID_CONSUMER_AL_DICTIONARY);
const Key AL_Desktop = Key::consumerKey(HID_CONSUMER_AL_DESKTOP);
const Key AL_SpellCheck = Key::consumerKey(HID_CONSUMER_AL_SPELL_CHECK);
const Key AL_GrammarCheck = Key::consumerKey(HID_CONSUMER_AL_GRAMMAR_CHECK);
const Key AL_WirelessStatus = Key::consumerKey(HID_CONSUMER_AL_WIRELESS_STATUS);
const Key AL_KeyboardLayout = Key::consumerKey(HID_CONSUMER_AL_KEYBOARD_LAYOUT);
const Key AL_VirusProtection = Key::consumerKey(HID_CONSUMER_AL_VIRUS_PROTECTION);
const Key AL_Encryption = Key::consumerKey(HID_CONSUMER_AL_ENCRYPTION);
const Key AL_ScreenSaver = Key::consumerKey(HID_CONSUMER_AL_SCREEN_SAVER);
const Key AL_Alarms = Key::consumerKey(HID_CONSUMER_AL_ALARMS);
const Key AL_Clock = Key::consumerKey(HID_CONSUMER_AL_CLOCK);
const Key AL_FileBrowser = Key::consumerKey(HID_CONSUMER_AL_FILE_BROWSER);
const Key AL_PowerStatus = Key::consumerKey(HID_CONSUMER_AL_POWER_STATUS);
const Key AL_ImageBrowser = Key::consumerKey(HID_CONSUMER_AL_IMAGE_BROWSER);
const Key AL_AudioBrowser = Key::consumerKey(HID_CONSUMER_AL_AUDIO_BROWSER);
const Key AL_MovieBrowser = Key::consumerKey(HID_CONSUMER_AL_MOVIE_BROWSER);
const Key AL_DigitalRightsManager = Key::consumerKey(HID_CONSUMER_AL_DIGITAL_RIGHTS_MANAGER);
const Key AL_DigitalWallet = Key::consumerKey(HID_CONSUMER_AL_DIGITAL_WALLET);

const Key AL_InstantMessaging = Key::consumerKey(HID_CONSUMER_AL_INSTANT_MESSAGING);
const Key AL_OemFeaturesSlashTipsSlashTUTORIALBrowser = Key::consumerKey(HID_CONSUMER_AL_OEM_FEATURES_SLASH__TIPS_SLASH_TUTORIAL_BROWSER);
const Key AL_OemHelp = Key::consumerKey(HID_CONSUMER_AL_OEM_HELP);
const Key AL_OnlineCommunity = Key::consumerKey(HID_CONSUMER_AL_ONLINE_COMMUNITY);
const Key AL_Entertainment_Content_Browser = Key::consumerKey(HID_CONSUMER_AL_ENTERTAINMENT_CONTENT_BROWSER);
const Key AL_OnlineShoppingBrowser = Key::consumerKey(HID_CONSUMER_AL_ONLINE_SHOPPING_BROWSER);
const Key AL_SmartcardInformationSlashHelp = Key::consumerKey(HID_CONSUMER_AL_SMARTCARD_INFORMATION_SLASH_HELP);
const Key AL_MarketMonitorSlashFinanceBrowser = Key::consumerKey(HID_CONSUMER_AL_MARKET_MONITOR_SLASH_FINANCE_BROWSER);
const Key AL_CustomizedCorporateNewsBrowser = Key::consumerKey(HID_CONSUMER_AL_CUSTOMIZED_CORPORATE_NEWS_BROWSER);
const Key AL_OnlineActivityBrowser = Key::consumerKey(HID_CONSUMER_AL_ONLINE_ACTIVITY_BROWSER);
const Key AL_ResearchSlashSearchBrowser = Key::consumerKey(HID_CONSUMER_AL_RESEARCH_SLASH_SEARCH_BROWSER);
const Key AL_AudioPlayer = Key::consumerKey(HID_CONSUMER_AL_AUDIO_PLAYER);

const Key GenericGuiApplicationControls = Key::consumerKey(HID_CONSUMER_GENERIC_GUI_APPLICATION_CONTROLS);
const Key AC_New = Key::consumerKey(HID_CONSUMER_AC_NEW);
const Key AC_Open = Key::consumerKey(HID_CONSUMER_AC_OPEN);
const Key AC_Close = Key::consumerKey(HID_CONSUMER_AC_CLOSE);
const Key AC_Exit = Key::consumerKey(HID_CONSUMER_AC_EXIT);
const Key AC_Maximize = Key::consumerKey(HID_CONSUMER_AC_MAXIMIZE);
const Key AC_Minimize = Key::consumerKey(HID_CONSUMER_AC_MINIMIZE);
const Key AC_Save = Key::consumerKey(HID_CONSUMER_AC_SAVE);
const Key AC_Print = Key::consumerKey(HID_CONSUMER_AC_PRINT);
const Key AC_Properties = Key::consumerKey(HID_CONSUMER_AC_PROPERTIES);
const Key AC_Undo = Key::consumerKey(HID_CONSUMER_AC_UNDO);
const Key AC_Copy = Key::consumerKey(HID_CONSUMER_AC_COPY);
const Key AC_Cut = Key::consumerKey(HID_CONSUMER_AC_CUT);
const Key AC_Paste = Key::consumerKey(HID_CONSUMER_AC_PASTE);
const Key AC_SelectAll = Key::consumerKey(HID_CONSUMER_AC_SELECT_ALL);
const Key AC_Find = Key::consumerKey(HID_CONSUMER_AC_FIND);
const Key AC_FindAndReplace = Key::consumerKey(HID_CONSUMER_AC_FIND_AND_REPLACE);
const Key AC_Search = Key::consumerKey(HID_CONSUMER_AC_SEARCH);
const Key AC_GoTo = Key::consumerKey(HID_CONSUMER_AC_GO_TO);
const Key AC_Home = Key::consumerKey(HID_CONSUMER_AC_HOME);
const Key AC_Back = Key::consumerKey(HID_CONSUMER_AC_BACK);
const Key AC_Forward = Key::consumerKey(HID_CONSUMER_AC_FORWARD);
const Key AC_Stop = Key::consumerKey(HID_CONSUMER_AC_STOP);
const Key AC_Refresh = Key::consumerKey(HID_CONSUMER_AC_REFRESH);
const Key AC_PreviousLink = Key::consumerKey(HID_CONSUMER_AC_PREVIOUS_LINK);
const Key AC_NextLink = Key::consumerKey(HID_CONSUMER_AC_NEXT_LINK);
const Key AC_Bookmarks = Key::consumerKey(HID_CONSUMER_AC_BOOKMARKS);
const Key AC_History = Key::consumerKey(HID_CONSUMER_AC_HISTORY);
const Key AC_Subscriptions = Key::consumerKey(HID_CONSUMER_AC_SUBSCRIPTIONS);
const Key AC_ZoomIn = Key::consumerKey(HID_CONSUMER_AC_ZOOM_IN);
const Key AC_ZoomOut = Key::consumerKey(HID_CONSUMER_AC_ZOOM_OUT);
const Key AC_Zoom = Key::consumerKey(HID_CONSUMER_AC_ZOOM);
const Key AC_FullSCreenView = Key::consumerKey(HID_CONSUMER_AC_FULL_SCREEN_VIEW);
const Key AC_NormalView = Key::consumerKey(HID_CONSUMER_AC_NORMAL_VIEW);
const Key AC_ViewToggle = Key::consumerKey(HID_CONSUMER_AC_VIEW_TOGGLE);
const Key AC_ScrollUp = Key::consumerKey(HID_CONSUMER_AC_SCROLL_UP);
const Key AC_ScrollDown = Key::consumerKey(HID_CONSUMER_AC_SCROLL_DOWN);
const Key AC_Scroll = Key::consumerKey(HID_CONSUMER_AC_SCROLL);
const Key AC_PanLeft = Key::consumerKey(HID_CONSUMER_AC_PAN_LEFT);
const Key AC_PanRight = Key::consumerKey(HID_CONSUMER_AC_PAN_RIGHT);
const Key AC_Pan = Key::consumerKey(HID_CONSUMER_AC_PAN);
const Key AC_NewWindow = Key::consumerKey(HID_CONSUMER_AC_NEW_WINDOW);
const Key AC_TileHorizontally = Key::consumerKey(HID_CONSUMER_AC_TILE_HORIZONTALLY);
const Key AC_TileVertically = Key::consumerKey(HID_CONSUMER_AC_TILE_VERTICALLY);
const Key AC_Format = Key::consumerKey(HID_CONSUMER_AC_FORMAT);
const Key AC_Edit = Key::consumerKey(HID_CONSUMER_AC_EDIT);
const Key AC_Bold = Key::consumerKey(HID_CONSUMER_AC_BOLD);
const Key AC_Italics = Key::consumerKey(HID_CONSUMER_AC_ITALICS);
const Key AC_Underline = Key::consumerKey(HID_CONSUMER_AC_UNDERLINE);
const Key AC_Strikethrough = Key::consumerKey(HID_CONSUMER_AC_STRIKETHROUGH);
const Key AC_Subscript = Key::consumerKey(HID_CONSUMER_AC_SUBSCRIPT);
const Key AC_Superscript = Key::consumerKey(HID_CONSUMER_AC_SUPERSCRIPT);
const Key AC_AllCaps = Key::consumerKey(HID_CONSUMER_AC_ALL_CAPS);
const Key AC_Rotate = Key::consumerKey(HID_CONSUMER_AC_ROTATE);
const Key AC_Resize = Key::consumerKey(HID_CONSUMER_AC_RESIZE);
const Key AC_FlipHorizontal = Key::consumerKey(HID_CONSUMER_AC_FLIP_HORIZONTAL);
const Key AC_FlipVertical = Key::consumerKey(HID_CONSUMER_AC_FLIP_VERTICAL);
const Key AC_MirrorHorizontal = Key::consumerKey(HID_CONSUMER_AC_MIRROR_HORIZONTAL);
const Key AC_MirrorVertical = Key::consumerKey(HID_CONSUMER_AC_MIRROR_VERTICAL);
const Key AC_FontSelect = Key::consumerKey(HID_CONSUMER_AC_FONT_SELECT);
const Key AC_FontColor = Key::consumerKey(HID_CONSUMER_AC_FONT_COLOR);
const Key AC_FontSize = Key::consumerKey(HID_CONSUMER_AC_FONT_SIZE);
const Key AC_JustifyLeft = Key::consumerKey(HID_CONSUMER_AC_JUSTIFY_LEFT);
const Key AC_JustifyCenterH = Key::consumerKey(HID_CONSUMER_AC_JUSTIFY_CENTER_H);
const Key AC_JustifyRight = Key::consumerKey(HID_CONSUMER_AC_JUSTIFY_RIGHT);
const Key AC_JustifyBlockH = Key::consumerKey(HID_CONSUMER_AC_JUSTIFY_BLOCK_H);
const Key AC_JustifyTop = Key::consumerKey(HID_CONSUMER_AC_JUSTIFY_TOP);
const Key AC_JustifyCenterV = Key::consumerKey(HID_CONSUMER_AC_JUSTIFY_CENTER_V);
const Key AC_JustifyBottom = Key::consumerKey(HID_CONSUMER_AC_JUSTIFY_BOTTOM);
const Key AC_JustifyBlockV = Key::consumerKey(HID_CONSUMER_AC_JUSTIFY_BLOCK_V);
const Key AC_IndentDecrease = Key::consumerKey(HID_CONSUMER_AC_INDENT_DECREASE);
const Key AC_IndentIncrease = Key::consumerKey(HID_CONSUMER_AC_INDENT_INCREASE);
const Key AC_NumberedList = Key::consumerKey(HID_CONSUMER_AC_NUMBERED_LIST);
const Key AC_RestartNumbering = Key::consumerKey(HID_CONSUMER_AC_RESTART_NUMBERING);
const Key AC_BulletedList = Key::consumerKey(HID_CONSUMER_AC_BULLETED_LIST);
const Key AC_Promote = Key::consumerKey(HID_CONSUMER_AC_PROMOTE);
const Key AC_Demote = Key::consumerKey(HID_CONSUMER_AC_DEMOTE);
const Key AC_Yes = Key::consumerKey(HID_CONSUMER_AC_YES);
const Key AC_No = Key::consumerKey(HID_CONSUMER_AC_NO);
const Key AC_Cancel = Key::consumerKey(HID_CONSUMER_AC_CANCEL);
const Key AC_Catalog = Key::consumerKey(HID_CONSUMER_AC_CATALOG);
const Key AC_BuySlashCheckout = Key::consumerKey(HID_CONSUMER_AC_BUY_SLASH_CHECKOUT);
const Key AC_AddToCart = Key::consumerKey(HID_CONSUMER_AC_ADD_TO_CART);
const Key AC_Expand = Key::consumerKey(HID_CONSUMER_AC_EXPAND);
const Key AC_ExpandAll = Key::consumerKey(HID_CONSUMER_AC_EXPAND_ALL);
const Key AC_Collapse = Key::consumerKey(HID_CONSUMER_AC_COLLAPSE);
const Key AC_CollapseAll = Key::consumerKey(HID_CONSUMER_AC_COLLAPSE_ALL);
const Key AC_PrintPreview = Key::consumerKey(HID_CONSUMER_AC_PRINT_PREVIEW);
const Key AC_PasteSpecial = Key::consumerKey(HID_CONSUMER_AC_PASTE_SPECIAL);
const Key AC_InsertMode = Key::consumerKey(HID_CONSUMER_AC_INSERT_MODE);
const Key AC_Delete = Key::consumerKey(HID_CONSUMER_AC_DELETE);
const Key AC_Lock = Key::consumerKey(HID_CONSUMER_AC_LOCK);
const Key AC_Unlock = Key::consumerKey(HID_CONSUMER_AC_UNLOCK);
const Key AC_Protect = Key::consumerKey(HID_CONSUMER_AC_PROTECT);
const Key AC_Unprotect = Key::consumerKey(HID_CONSUMER_AC_UNPROTECT);
const Key AC_AttachComment = Key::consumerKey(HID_CONSUMER_AC_ATTACH_COMMENT);
const Key AC_DeleteComment = Key::consumerKey(HID_CONSUMER_AC_DELETE_COMMENT);
const Key AC_ViewComment = Key::consumerKey(HID_CONSUMER_AC_VIEW_COMMENT);
const Key AC_SelectWord = Key::consumerKey(HID_CONSUMER_AC_SELECT_WORD);
const Key AC_SelectSentence = Key::consumerKey(HID_CONSUMER_AC_SELECT_SENTENCE);
const Key AC_SelectParagraph = Key::consumerKey(HID_CONSUMER_AC_SELECT_PARAGRAPH);
const Key AC_SelectColumn = Key::consumerKey(HID_CONSUMER_AC_SELECT_COLUMN);
const Key AC_SelectRow = Key::consumerKey(HID_CONSUMER_AC_SELECT_ROW);
const Key AC_SelectTable = Key::consumerKey(HID_CONSUMER_AC_SELECT_TABLE);
const Key AC_SelectObject = Key::consumerKey(HID_CONSUMER_AC_SELECT_OBJECT);
const Key AC_RedoSlashRepeat = Key::consumerKey(HID_CONSUMER_AC_REDO_SLASH_REPEAT);
const Key AC_Sort = Key::consumerKey(HID_CONSUMER_AC_SORT);
const Key AC_Sort_Ascending = Key::consumerKey(HID_CONSUMER_AC_SORT_ASCENDING);
const Key AC_Sort_Descending = Key::consumerKey(HID_CONSUMER_AC_SORT_DESCENDING);
const Key AC_Filter = Key::consumerKey(HID_CONSUMER_AC_FILTER);
const Key AC_SetClock = Key::consumerKey(HID_CONSUMER_AC_SET_CLOCK);
const Key AC_ViewClock = Key::consumerKey(HID_CONSUMER_AC_VIEW_CLOCK);
const Key AC_SelectTimeZone = Key::consumerKey(HID_CONSUMER_AC_SELECT_TIME_ZONE);
const Key AC_EditTimeZones = Key::consumerKey(HID_CONSUMER_AC_EDIT_TIME_ZONES);
const Key AC_SetAlarm = Key::consumerKey(HID_CONSUMER_AC_SET_ALARM);
const Key AC_ClearAlarm = Key::consumerKey(HID_CONSUMER_AC_CLEAR_ALARM);
const Key AC_SnoozeAlarm = Key::consumerKey(HID_CONSUMER_AC_SNOOZE_ALARM);
const Key AC_ResetAlarm = Key::consumerKey(HID_CONSUMER_AC_RESET_ALARM);
const Key AC_Synchronize = Key::consumerKey(HID_CONSUMER_AC_SYNCHRONIZE);
const Key AC_SendSlashReceive = Key::consumerKey(HID_CONSUMER_AC_SEND_SLASH_RECEIVE);
const Key AC_SendTo = Key::consumerKey(HID_CONSUMER_AC_SEND_TO);
const Key AC_Reply = Key::consumerKey(HID_CONSUMER_AC_REPLY);
const Key AC_ReplyAll = Key::consumerKey(HID_CONSUMER_AC_REPLY_ALL);
const Key AC_ForwardMsg = Key::consumerKey(HID_CONSUMER_AC_FORWARD_MSG);
const Key AC_Send = Key::consumerKey(HID_CONSUMER_AC_SEND);
const Key AC_AttachFile = Key::consumerKey(HID_CONSUMER_AC_ATTACH_FILE);
const Key AC_Upload = Key::consumerKey(HID_CONSUMER_AC_UPLOAD);
const Key AC_Download = Key::consumerKey(HID_CONSUMER_AC_DOWNLOAD);
const Key AC_SetBorders = Key::consumerKey(HID_CONSUMER_AC_SET_BORDERS);
const Key AC_InsertRow = Key::consumerKey(HID_CONSUMER_AC_INSERT_ROW);
const Key AC_InsertColumn = Key::consumerKey(HID_CONSUMER_AC_INSERT_COLUMN);
const Key AC_InsertFile = Key::consumerKey(HID_CONSUMER_AC_INSERT_FILE);
const Key AC_InsertPicture = Key::consumerKey(HID_CONSUMER_AC_INSERT_PICTURE);
const Key AC_InsertObject = Key::consumerKey(HID_CONSUMER_AC_INSERT_OBJECT);
const Key AC_InsertSymbol = Key::consumerKey(HID_CONSUMER_AC_INSERT_SYMBOL);
const Key AC_SaveandClose = Key::consumerKey(HID_CONSUMER_AC_SAVE_AND_CLOSE);
const Key AC_Rename = Key::consumerKey(HID_CONSUMER_AC_RENAME);
const Key AC_Merge = Key::consumerKey(HID_CONSUMER_AC_MERGE);
const Key AC_Split = Key::consumerKey(HID_CONSUMER_AC_SPLIT);
const Key AC_Distribute_Horizontally = Key::consumerKey(HID_CONSUMER_AC_DISTRIBUTE_HORIZONTALLY);
const Key AC_Distribute_Vertically = Key::consumerKey(HID_CONSUMER_AC_DISTRIBUTE_VERTICALLY);

} // namespace consumer {

} // namespace cKey {

} // namespace kaleidoscope {
