// -*- c++ -*-

#pragma once

#include "HIDTables.h"
#include "kaleidoscope/Key.h"


namespace kaleidoscope {

// This namespace is for storing constants of type `Key`. The leading `c` stands for
// `constant` or `const`
// `const Key` object.
namespace cKey {

namespace consumer {

const Key NumericKeyPad = consumerKey(HID_CONSUMER_NUMERIC_KEY_PAD);
const Key ProgrammableButtons = consumerKey(HID_CONSUMER_PROGRAMMABLE_BUTTONS);
const Key MicrophoneCa = consumerKey(HID_CONSUMER_MICROPHONE_CA);
const Key HeadphoneCa = consumerKey(HID_CONSUMER_HEADPHONE_CA);
const Key GraphicEqualizerCa = consumerKey(HID_CONSUMER_GRAPHIC_EQUALIZER_CA);

const Key Plus10 = consumerKey(HID_CONSUMER_PLUS_10);
const Key Plus100 = consumerKey(HID_CONSUMER_PLUS_100);
const Key AMSlashPM = consumerKey(HID_CONSUMER_AM_SLASH_PM);

const Key Power = consumerKey(HID_CONSUMER_POWER);
const Key Reset = consumerKey(HID_CONSUMER_RESET);
const Key Sleep = consumerKey(HID_CONSUMER_SLEEP);
const Key Sleep_After = consumerKey(HID_CONSUMER_SLEEP_AFTER);
const Key Sleep_Mode = consumerKey(HID_CONSUMER_SLEEP_MODE);
const Key Illumination = consumerKey(HID_CONSUMER_ILLUMINATION);
const Key Function_Buttons = consumerKey(HID_CONSUMER_FUNCTION_BUTTONS);

const Key Menu = consumerKey(HID_CONSUMER_MENU);
const Key MenuPick = consumerKey(HID_CONSUMER_MENU_PICK);
const Key MenuUp = consumerKey(HID_CONSUMER_MENU_UP);
const Key MenuDown = consumerKey(HID_CONSUMER_MENU_DOWN);
const Key MenuLeft = consumerKey(HID_CONSUMER_MENU_LEFT);
const Key MenuRight = consumerKey(HID_CONSUMER_MENU_RIGHT);
const Key MenuEscape = consumerKey(HID_CONSUMER_MENU_ESCAPE);
const Key MenuValueIncrease = consumerKey(HID_CONSUMER_MENU_VALUE_INCREASE);
const Key MenuValueDecrease = consumerKey(HID_CONSUMER_MENU_VALUE_DECREASE);

const Key DataOnScreen = consumerKey(HID_CONSUMER_DATA_ON_SCREEN);
const Key ClosedCaption = consumerKey(HID_CONSUMER_CLOSED_CAPTION);
const Key ClosedCaptionSelect = consumerKey(HID_CONSUMER_CLOSED_CAPTION_SELECT);
const Key VCRSlashTV = consumerKey(HID_CONSUMER_VCR_SLASH_TV);
const Key BroadcastMode = consumerKey(HID_CONSUMER_BROADCAST_MODE);
const Key SNapshot = consumerKey(HID_CONSUMER_SNAPSHOT);
const Key Still = consumerKey(HID_CONSUMER_STILL);

const Key Selection = consumerKey(HID_CONSUMER_SELECTION);
const Key AssignSelection = consumerKey(HID_CONSUMER_ASSIGN_SELECTION);
const Key ModeStep = consumerKey(HID_CONSUMER_MODE_STEP);
const Key RecallLast = consumerKey(HID_CONSUMER_RECALL_LAST);
const Key EnterChannel = consumerKey(HID_CONSUMER_ENTER_CHANNEL);
const Key OrderMovie = consumerKey(HID_CONSUMER_ORDER_MOVIE);
const Key Channel = consumerKey(HID_CONSUMER_CHANNEL);
const Key MediaSelection = consumerKey(HID_CONSUMER_MEDIA_SELECTION);
const Key MediaSelectComputer = consumerKey(HID_CONSUMER_MEDIA_SELECT_COMPUTER);
const Key MediaSelectTV = consumerKey(HID_CONSUMER_MEDIA_SELECT_TV);
const Key MediaSelectWww = consumerKey(HID_CONSUMER_MEDIA_SELECT_WWW);
const Key MediaSelectDvd = consumerKey(HID_CONSUMER_MEDIA_SELECT_DVD);
const Key MediaSelectTelephone = consumerKey(HID_CONSUMER_MEDIA_SELECT_TELEPHONE);
const Key MediaSelectProgramGuide = consumerKey(HID_CONSUMER_MEDIA_SELECT_PROGRAM_GUIDE);
const Key MediaSelectVideoPhone = consumerKey(HID_CONSUMER_MEDIA_SELECT_VIDEO_PHONE);
const Key MediaSelectGames = consumerKey(HID_CONSUMER_MEDIA_SELECT_GAMES);
const Key MediaSelectMessages = consumerKey(HID_CONSUMER_MEDIA_SELECT_MESSAGES);
const Key MediaSelectCd = consumerKey(HID_CONSUMER_MEDIA_SELECT_CD);
const Key MediaSelectVcr = consumerKey(HID_CONSUMER_MEDIA_SELECT_VCR);
const Key MediaSelectTuner = consumerKey(HID_CONSUMER_MEDIA_SELECT_TUNER);
const Key Quit = consumerKey(HID_CONSUMER_QUIT);
const Key Help = consumerKey(HID_CONSUMER_HELP);
const Key MediaSelectTape = consumerKey(HID_CONSUMER_MEDIA_SELECT_TAPE);
const Key MediaSelectCable = consumerKey(HID_CONSUMER_MEDIA_SELECT_CABLE);
const Key MediaSelectSatellite = consumerKey(HID_CONSUMER_MEDIA_SELECT_SATELLITE);
const Key MediaSelectSecurity = consumerKey(HID_CONSUMER_MEDIA_SELECT_SECURITY);
const Key MediaSelectHome = consumerKey(HID_CONSUMER_MEDIA_SELECT_HOME);
const Key MediaSelectCall = consumerKey(HID_CONSUMER_MEDIA_SELECT_CALL);
const Key ChannelIncrement = consumerKey(HID_CONSUMER_CHANNEL_INCREMENT);
const Key ChannelDecrement = consumerKey(HID_CONSUMER_CHANNEL_DECREMENT);
const Key MediaSelectSap = consumerKey(HID_CONSUMER_MEDIA_SELECT_SAP);

const Key VcrPlus = consumerKey(HID_CONSUMER_VCR_PLUS);
const Key Once = consumerKey(HID_CONSUMER_ONCE);
const Key Daily = consumerKey(HID_CONSUMER_DAILY);
const Key Weekly = consumerKey(HID_CONSUMER_WEEKLY);
const Key Monthly = consumerKey(HID_CONSUMER_MONTHLY);

const Key Play = consumerKey(HID_CONSUMER_PLAY);
const Key Pause = consumerKey(HID_CONSUMER_PAUSE);
const Key Record = consumerKey(HID_CONSUMER_RECORD);
const Key FastForward = consumerKey(HID_CONSUMER_FAST_FORWARD);
const Key Rewind = consumerKey(HID_CONSUMER_REWIND);
const Key ScanNextTrack = consumerKey(HID_CONSUMER_SCAN_NEXT_TRACK);
const Key ScanPreviousTrack = consumerKey(HID_CONSUMER_SCAN_PREVIOUS_TRACK);
const Key Stop = consumerKey(HID_CONSUMER_STOP);
const Key Eject = consumerKey(HID_CONSUMER_EJECT);
const Key RandomPlay = consumerKey(HID_CONSUMER_RANDOM_PLAY);
const Key SelectDisc = consumerKey(HID_CONSUMER_SELECT_DISC);
const Key EnterDiscMc = consumerKey(HID_CONSUMER_ENTER_DISC_MC);
const Key Repeat = consumerKey(HID_CONSUMER_REPEAT);
const Key Tracking = consumerKey(HID_CONSUMER_TRACKING);
const Key Track_Normal = consumerKey(HID_CONSUMER_TRACK_NORMAL);
const Key SlowTracking = consumerKey(HID_CONSUMER_SLOW_TRACKING);
const Key FrameForward = consumerKey(HID_CONSUMER_FRAME_FORWARD);
const Key FrameBack = consumerKey(HID_CONSUMER_FRAME_BACK);
const Key Mark = consumerKey(HID_CONSUMER_MARK);
const Key ClearMark = consumerKey(HID_CONSUMER_CLEAR_MARK);
const Key RepeatFromMark = consumerKey(HID_CONSUMER_REPEAT_FROM_MARK);
const Key ReturnTo_Mark = consumerKey(HID_CONSUMER_RETURN_TO_MARK);
const Key SearchMarkForward = consumerKey(HID_CONSUMER_SEARCH_MARK_FORWARD);
const Key SearchMarkBackwards = consumerKey(HID_CONSUMER_SEARCH_MARK_BACKWARDS);
const Key CounterReset = consumerKey(HID_CONSUMER_COUNTER_RESET);
const Key ShowCounter = consumerKey(HID_CONSUMER_SHOW_COUNTER);
const Key TrackingIncrement = consumerKey(HID_CONSUMER_TRACKING_INCREMENT);
const Key TrackingDecrement = consumerKey(HID_CONSUMER_TRACKING_DECREMENT);
const Key StopSlashEject = consumerKey(HID_CONSUMER_STOP_SLASH_EJECT);
const Key PlaySlashPause = consumerKey(HID_CONSUMER_PLAY_SLASH_PAUSE);
const Key PlaySlashSkip = consumerKey(HID_CONSUMER_PLAY_SLASH_SKIP);
const Key Volume = consumerKey(HID_CONSUMER_VOLUME);
const Key Balance = consumerKey(HID_CONSUMER_BALANCE);
const Key Mute = consumerKey(HID_CONSUMER_MUTE);
const Key Bass = consumerKey(HID_CONSUMER_BASS);
const Key Treble = consumerKey(HID_CONSUMER_TREBLE);
const Key BassBoost = consumerKey(HID_CONSUMER_BASS_BOOST);
const Key SurroundMode = consumerKey(HID_CONSUMER_SURROUND_MODE);
const Key Loudness = consumerKey(HID_CONSUMER_LOUDNESS);
const Key Mpx = consumerKey(HID_CONSUMER_MPX);
const Key VolumeIncrement = consumerKey(HID_CONSUMER_VOLUME_INCREMENT);


const Key VolumeDecrement = consumerKey(HID_CONSUMER_VOLUME_DECREMENT);

const Key SpeedSelect = consumerKey(HID_CONSUMER_SPEED_SELECT);
const Key PlaybackSpeed = consumerKey(HID_CONSUMER_PLAYBACK_SPEED);
const Key StandardPlay = consumerKey(HID_CONSUMER_STANDARD_PLAY);
const Key LongPlay = consumerKey(HID_CONSUMER_LONG_PLAY);
const Key ExtendedPlay = consumerKey(HID_CONSUMER_EXTENDED_PLAY);
const Key Slow = consumerKey(HID_CONSUMER_SLOW);

const Key FanEnable = consumerKey(HID_CONSUMER_FAN_ENABLE);
const Key FanSpeed = consumerKey(HID_CONSUMER_FAN_SPEED);
const Key LightEnable = consumerKey(HID_CONSUMER_LIGHT_ENABLE);
const Key LightIlluminationLevel = consumerKey(HID_CONSUMER_LIGHT_ILLUMINATION_LEVEL);
const Key ClimateControlEnable = consumerKey(HID_CONSUMER_CLIMATE_CONTROL_ENABLE);
const Key RoomTemperature = consumerKey(HID_CONSUMER_ROOM_TEMPERATURE);
const Key SecurityEnable = consumerKey(HID_CONSUMER_SECURITY_ENABLE);
const Key FireAlarm = consumerKey(HID_CONSUMER_FIRE_ALARM);
const Key PoliceAlarm = consumerKey(HID_CONSUMER_POLICE_ALARM);
const Key Proximity = consumerKey(HID_CONSUMER_PROXIMITY);
const Key Motion = consumerKey(HID_CONSUMER_MOTION);
const Key DuressAlarm = consumerKey(HID_CONSUMER_DURESS_ALARM);
const Key HoldupAlarm = consumerKey(HID_CONSUMER_HOLDUP_ALARM);
const Key MedicalAlarm = consumerKey(HID_CONSUMER_MEDICAL_ALARM);

const Key BalanceRight = consumerKey(HID_CONSUMER_BALANCE_RIGHT);
const Key BalanceLeft = consumerKey(HID_CONSUMER_BALANCE_LEFT);
const Key BassIncrement = consumerKey(HID_CONSUMER_BASS_INCREMENT);
const Key BassDecrement = consumerKey(HID_CONSUMER_BASS_DECREMENT);
const Key TrebleIncrement = consumerKey(HID_CONSUMER_TREBLE_INCREMENT);
const Key TrebleDecrement = consumerKey(HID_CONSUMER_TREBLE_DECREMENT);

const Key SpeakerSystem = consumerKey(HID_CONSUMER_SPEAKER_SYSTEM);
const Key ChannelLeft = consumerKey(HID_CONSUMER_CHANNEL_LEFT);
const Key ChannelRight = consumerKey(HID_CONSUMER_CHANNEL_RIGHT);
const Key ChannelCenter = consumerKey(HID_CONSUMER_CHANNEL_CENTER);
const Key ChannelFront = consumerKey(HID_CONSUMER_CHANNEL_FRONT);
const Key ChannelCenterFront = consumerKey(HID_CONSUMER_CHANNEL_CENTER_FRONT);
const Key ChannelSide = consumerKey(HID_CONSUMER_CHANNEL_SIDE);
const Key ChannelSurround = consumerKey(HID_CONSUMER_CHANNEL_SURROUND);
const Key ChannelLowFrequencyEnhancement = consumerKey(HID_CONSUMER_CHANNEL_LOW_FREQUENCY_ENHANCEMENT);
const Key ChannelTop = consumerKey(HID_CONSUMER_CHANNEL_TOP);
const Key ChannelUnknown = consumerKey(HID_CONSUMER_CHANNEL_UNKNOWN);

const Key SubChannel = consumerKey(HID_CONSUMER_SUB_CHANNEL);
const Key SubChannelIncrement = consumerKey(HID_CONSUMER_SUB_CHANNEL_INCREMENT);
const Key SubChannelDecrement = consumerKey(HID_CONSUMER_SUB_CHANNEL_DECREMENT);
const Key AlternateAudioIncrement = consumerKey(HID_CONSUMER_ALTERNATE_AUDIO_INCREMENT);
const Key AlternateAudioDecrement = consumerKey(HID_CONSUMER_ALTERNATE_AUDIO_DECREMENT);

const Key Application_Launch_Buttons = consumerKey(HID_CONSUMER_APPLICATION_LAUNCH_BUTTONS);
const Key AL_Launch_Button_Configuration_Tool = consumerKey(HID_CONSUMER_AL_LAUNCH_BUTTON_CONFIGURATION_TOOL);
const Key AL_Programmable_Button_Configuration = consumerKey(HID_CONSUMER_AL_PROGRAMMABLE_BUTTON_CONFIGURATION);
const Key AL_Consumer_Control_Configuration = consumerKey(HID_CONSUMER_AL_CONSUMER_CONTROL_CONFIGURATION);
const Key AL_Word_Processor = consumerKey(HID_CONSUMER_AL_WORD_PROCESSOR);
const Key AL_Text_Editor = consumerKey(HID_CONSUMER_AL_TEXT_EDITOR);
const Key AL_Spreadsheet = consumerKey(HID_CONSUMER_AL_SPREADSHEET);
const Key AL_Graphics_Editor = consumerKey(HID_CONSUMER_AL_GRAPHICS_EDITOR);
const Key AL_Presentation_App = consumerKey(HID_CONSUMER_AL_PRESENTATION_APP);
const Key AL_Database_App = consumerKey(HID_CONSUMER_AL_DATABASE_APP);
const Key AL_Email_Reader = consumerKey(HID_CONSUMER_AL_EMAIL_READER);
const Key AL_Newsreader = consumerKey(HID_CONSUMER_AL_NEWSREADER);
const Key AL_Voicemail = consumerKey(HID_CONSUMER_AL_VOICEMAIL);
const Key AL_Contacts_Slash_Address_Book = consumerKey(HID_CONSUMER_AL_CONTACTS_SLASH_ADDRESS_BOOK);
const Key AL_Calendar_Slash_Schedule = consumerKey(HID_CONSUMER_AL_CALENDAR_SLASH_SCHEDULE);
const Key AL_Task_Slash_Project_Manager = consumerKey(HID_CONSUMER_AL_TASK_SLASH_PROJECT_MANAGER);
const Key AL_Log_Slash_Journal_Slash_Timecard = consumerKey(HID_CONSUMER_AL_LOG_SLASH_JOURNAL_SLASH_TIMECARD);
const Key AL_Checkbook_Slash_Finance = consumerKey(HID_CONSUMER_AL_CHECKBOOK_SLASH_FINANCE);
const Key AL_Calculator = consumerKey(HID_CONSUMER_AL_CALCULATOR);
const Key AL_AVCaptureSlashPlayback = consumerKey(HID_CONSUMER_AL_A_SLASH_V_CAPTURE_SLASH_PLAYBACK);
const Key AL_Local_MachineBrowser = consumerKey(HID_CONSUMER_AL_LOCAL_MACHINE_BROWSER);
const Key AL_Lan_SlashWanBrowser = consumerKey(HID_CONSUMER_AL_LAN_SLASH_WAN_BROWSER);
const Key AL_InternetBrowser = consumerKey(HID_CONSUMER_AL_INTERNET_BROWSER);
const Key AL_RemoteNetworkingSlashIspConnect = consumerKey(HID_CONSUMER_AL_REMOTE_NETWORKING_SLASH_ISP_CONNECT);
const Key AL_NetworkConference = consumerKey(HID_CONSUMER_AL_NETWORK_CONFERENCE);
const Key AL_NetworkChat = consumerKey(HID_CONSUMER_AL_NETWORK_CHAT);
const Key AL_TelephonySlashDialer = consumerKey(HID_CONSUMER_AL_TELEPHONY_SLASH_DIALER);
const Key AL_Logon = consumerKey(HID_CONSUMER_AL_LOGON);
const Key AL_Logoff = consumerKey(HID_CONSUMER_AL_LOGOFF);
const Key AL_LogonSlashLogoff = consumerKey(HID_CONSUMER_AL_LOGON_SLASH_LOGOFF);
const Key AL_TerminalLockSlashScreensaver = consumerKey(HID_CONSUMER_AL_TERMINAL_LOCK_SLASH_SCREENSAVER);
const Key AL_ControlPanel = consumerKey(HID_CONSUMER_AL_CONTROL_PANEL);
const Key AL_CommandLineProcessorSlashRun = consumerKey(HID_CONSUMER_AL_COMMAND_LINE_PROCESSOR_SLASH_RUN);
const Key AL_ProcessSlashTask_Manager = consumerKey(HID_CONSUMER_AL_PROCESS_SLASH_TASK_MANAGER);
const Key AL_SelectTaskSlashApplication = consumerKey(HID_CONSUMER_AL_SELECT_TASK_SLASH_APPLICATION);
const Key AL_NextTaskSlashApplication = consumerKey(HID_CONSUMER_AL_NEXT_TASK_SLASH_APPLICATION);
const Key AL_PreviousTaskSlashApplication = consumerKey(HID_CONSUMER_AL_PREVIOUS_TASK_SLASH_APPLICATION);
const Key AL_PreemptiveHaltTaskSlashApplication = consumerKey(HID_CONSUMER_AL_PREEMPTIVE_HALT_TASK_SLASH_APPLICATION);
const Key AL_IntegratedHelpCenter = consumerKey(HID_CONSUMER_AL_INTEGRATED_HELP_CENTER);
const Key AL_Documents = consumerKey(HID_CONSUMER_AL_DOCUMENTS);
const Key AL_Thesaurus = consumerKey(HID_CONSUMER_AL_THESAURUS);
const Key AL_Dictionary = consumerKey(HID_CONSUMER_AL_DICTIONARY);
const Key AL_Desktop = consumerKey(HID_CONSUMER_AL_DESKTOP);
const Key AL_SpellCheck = consumerKey(HID_CONSUMER_AL_SPELL_CHECK);
const Key AL_GrammarCheck = consumerKey(HID_CONSUMER_AL_GRAMMAR_CHECK);
const Key AL_WirelessStatus = consumerKey(HID_CONSUMER_AL_WIRELESS_STATUS);
const Key AL_KeyboardLayout = consumerKey(HID_CONSUMER_AL_KEYBOARD_LAYOUT);
const Key AL_VirusProtection = consumerKey(HID_CONSUMER_AL_VIRUS_PROTECTION);
const Key AL_Encryption = consumerKey(HID_CONSUMER_AL_ENCRYPTION);
const Key AL_ScreenSaver = consumerKey(HID_CONSUMER_AL_SCREEN_SAVER);
const Key AL_Alarms = consumerKey(HID_CONSUMER_AL_ALARMS);
const Key AL_Clock = consumerKey(HID_CONSUMER_AL_CLOCK);
const Key AL_FileBrowser = consumerKey(HID_CONSUMER_AL_FILE_BROWSER);
const Key AL_PowerStatus = consumerKey(HID_CONSUMER_AL_POWER_STATUS);
const Key AL_ImageBrowser = consumerKey(HID_CONSUMER_AL_IMAGE_BROWSER);
const Key AL_AudioBrowser = consumerKey(HID_CONSUMER_AL_AUDIO_BROWSER);
const Key AL_MovieBrowser = consumerKey(HID_CONSUMER_AL_MOVIE_BROWSER);
const Key AL_DigitalRightsManager = consumerKey(HID_CONSUMER_AL_DIGITAL_RIGHTS_MANAGER);
const Key AL_DigitalWallet = consumerKey(HID_CONSUMER_AL_DIGITAL_WALLET);

const Key AL_InstantMessaging = consumerKey(HID_CONSUMER_AL_INSTANT_MESSAGING);
const Key AL_OemFeaturesSlashTipsSlashTUTORIALBrowser = consumerKey(HID_CONSUMER_AL_OEM_FEATURES_SLASH__TIPS_SLASH_TUTORIAL_BROWSER);
const Key AL_OemHelp = consumerKey(HID_CONSUMER_AL_OEM_HELP);
const Key AL_OnlineCommunity = consumerKey(HID_CONSUMER_AL_ONLINE_COMMUNITY);
const Key AL_Entertainment_Content_Browser = consumerKey(HID_CONSUMER_AL_ENTERTAINMENT_CONTENT_BROWSER);
const Key AL_OnlineShoppingBrowser = consumerKey(HID_CONSUMER_AL_ONLINE_SHOPPING_BROWSER);
const Key AL_SmartcardInformationSlashHelp = consumerKey(HID_CONSUMER_AL_SMARTCARD_INFORMATION_SLASH_HELP);
const Key AL_MarketMonitorSlashFinanceBrowser = consumerKey(HID_CONSUMER_AL_MARKET_MONITOR_SLASH_FINANCE_BROWSER);
const Key AL_CustomizedCorporateNewsBrowser = consumerKey(HID_CONSUMER_AL_CUSTOMIZED_CORPORATE_NEWS_BROWSER);
const Key AL_OnlineActivityBrowser = consumerKey(HID_CONSUMER_AL_ONLINE_ACTIVITY_BROWSER);
const Key AL_ResearchSlashSearchBrowser = consumerKey(HID_CONSUMER_AL_RESEARCH_SLASH_SEARCH_BROWSER);
const Key AL_AudioPlayer = consumerKey(HID_CONSUMER_AL_AUDIO_PLAYER);

const Key GenericGuiApplicationControls = consumerKey(HID_CONSUMER_GENERIC_GUI_APPLICATION_CONTROLS);
const Key AC_New = consumerKey(HID_CONSUMER_AC_NEW);
const Key AC_Open = consumerKey(HID_CONSUMER_AC_OPEN);
const Key AC_Close = consumerKey(HID_CONSUMER_AC_CLOSE);
const Key AC_Exit = consumerKey(HID_CONSUMER_AC_EXIT);
const Key AC_Maximize = consumerKey(HID_CONSUMER_AC_MAXIMIZE);
const Key AC_Minimize = consumerKey(HID_CONSUMER_AC_MINIMIZE);
const Key AC_Save = consumerKey(HID_CONSUMER_AC_SAVE);
const Key AC_Print = consumerKey(HID_CONSUMER_AC_PRINT);
const Key AC_Properties = consumerKey(HID_CONSUMER_AC_PROPERTIES);
const Key AC_Undo = consumerKey(HID_CONSUMER_AC_UNDO);
const Key AC_Copy = consumerKey(HID_CONSUMER_AC_COPY);
const Key AC_Cut = consumerKey(HID_CONSUMER_AC_CUT);
const Key AC_Paste = consumerKey(HID_CONSUMER_AC_PASTE);
const Key AC_SelectAll = consumerKey(HID_CONSUMER_AC_SELECT_ALL);
const Key AC_Find = consumerKey(HID_CONSUMER_AC_FIND);
const Key AC_FindAndReplace = consumerKey(HID_CONSUMER_AC_FIND_AND_REPLACE);
const Key AC_Search = consumerKey(HID_CONSUMER_AC_SEARCH);
const Key AC_GoTo = consumerKey(HID_CONSUMER_AC_GO_TO);
const Key AC_Home = consumerKey(HID_CONSUMER_AC_HOME);
const Key AC_Back = consumerKey(HID_CONSUMER_AC_BACK);
const Key AC_Forward = consumerKey(HID_CONSUMER_AC_FORWARD);
const Key AC_Stop = consumerKey(HID_CONSUMER_AC_STOP);
const Key AC_Refresh = consumerKey(HID_CONSUMER_AC_REFRESH);
const Key AC_PreviousLink = consumerKey(HID_CONSUMER_AC_PREVIOUS_LINK);
const Key AC_NextLink = consumerKey(HID_CONSUMER_AC_NEXT_LINK);
const Key AC_Bookmarks = consumerKey(HID_CONSUMER_AC_BOOKMARKS);
const Key AC_History = consumerKey(HID_CONSUMER_AC_HISTORY);
const Key AC_Subscriptions = consumerKey(HID_CONSUMER_AC_SUBSCRIPTIONS);
const Key AC_ZoomIn = consumerKey(HID_CONSUMER_AC_ZOOM_IN);
const Key AC_ZoomOut = consumerKey(HID_CONSUMER_AC_ZOOM_OUT);
const Key AC_Zoom = consumerKey(HID_CONSUMER_AC_ZOOM);
const Key AC_FullSCreenView = consumerKey(HID_CONSUMER_AC_FULL_SCREEN_VIEW);
const Key AC_NormalView = consumerKey(HID_CONSUMER_AC_NORMAL_VIEW);
const Key AC_ViewToggle = consumerKey(HID_CONSUMER_AC_VIEW_TOGGLE);
const Key AC_ScrollUp = consumerKey(HID_CONSUMER_AC_SCROLL_UP);
const Key AC_ScrollDown = consumerKey(HID_CONSUMER_AC_SCROLL_DOWN);
const Key AC_Scroll = consumerKey(HID_CONSUMER_AC_SCROLL);
const Key AC_PanLeft = consumerKey(HID_CONSUMER_AC_PAN_LEFT);
const Key AC_PanRight = consumerKey(HID_CONSUMER_AC_PAN_RIGHT);
const Key AC_Pan = consumerKey(HID_CONSUMER_AC_PAN);
const Key AC_NewWindow = consumerKey(HID_CONSUMER_AC_NEW_WINDOW);
const Key AC_TileHorizontally = consumerKey(HID_CONSUMER_AC_TILE_HORIZONTALLY);
const Key AC_TileVertically = consumerKey(HID_CONSUMER_AC_TILE_VERTICALLY);
const Key AC_Format = consumerKey(HID_CONSUMER_AC_FORMAT);
const Key AC_Edit = consumerKey(HID_CONSUMER_AC_EDIT);
const Key AC_Bold = consumerKey(HID_CONSUMER_AC_BOLD);
const Key AC_Italics = consumerKey(HID_CONSUMER_AC_ITALICS);
const Key AC_Underline = consumerKey(HID_CONSUMER_AC_UNDERLINE);
const Key AC_Strikethrough = consumerKey(HID_CONSUMER_AC_STRIKETHROUGH);
const Key AC_Subscript = consumerKey(HID_CONSUMER_AC_SUBSCRIPT);
const Key AC_Superscript = consumerKey(HID_CONSUMER_AC_SUPERSCRIPT);
const Key AC_AllCaps = consumerKey(HID_CONSUMER_AC_ALL_CAPS);
const Key AC_Rotate = consumerKey(HID_CONSUMER_AC_ROTATE);
const Key AC_Resize = consumerKey(HID_CONSUMER_AC_RESIZE);
const Key AC_FlipHorizontal = consumerKey(HID_CONSUMER_AC_FLIP_HORIZONTAL);
const Key AC_FlipVertical = consumerKey(HID_CONSUMER_AC_FLIP_VERTICAL);
const Key AC_MirrorHorizontal = consumerKey(HID_CONSUMER_AC_MIRROR_HORIZONTAL);
const Key AC_MirrorVertical = consumerKey(HID_CONSUMER_AC_MIRROR_VERTICAL);
const Key AC_FontSelect = consumerKey(HID_CONSUMER_AC_FONT_SELECT);
const Key AC_FontColor = consumerKey(HID_CONSUMER_AC_FONT_COLOR);
const Key AC_FontSize = consumerKey(HID_CONSUMER_AC_FONT_SIZE);
const Key AC_JustifyLeft = consumerKey(HID_CONSUMER_AC_JUSTIFY_LEFT);
const Key AC_JustifyCenterH = consumerKey(HID_CONSUMER_AC_JUSTIFY_CENTER_H);
const Key AC_JustifyRight = consumerKey(HID_CONSUMER_AC_JUSTIFY_RIGHT);
const Key AC_JustifyBlockH = consumerKey(HID_CONSUMER_AC_JUSTIFY_BLOCK_H);
const Key AC_JustifyTop = consumerKey(HID_CONSUMER_AC_JUSTIFY_TOP);
const Key AC_JustifyCenterV = consumerKey(HID_CONSUMER_AC_JUSTIFY_CENTER_V);
const Key AC_JustifyBottom = consumerKey(HID_CONSUMER_AC_JUSTIFY_BOTTOM);
const Key AC_JustifyBlockV = consumerKey(HID_CONSUMER_AC_JUSTIFY_BLOCK_V);
const Key AC_IndentDecrease = consumerKey(HID_CONSUMER_AC_INDENT_DECREASE);
const Key AC_IndentIncrease = consumerKey(HID_CONSUMER_AC_INDENT_INCREASE);
const Key AC_NumberedList = consumerKey(HID_CONSUMER_AC_NUMBERED_LIST);
const Key AC_RestartNumbering = consumerKey(HID_CONSUMER_AC_RESTART_NUMBERING);
const Key AC_BulletedList = consumerKey(HID_CONSUMER_AC_BULLETED_LIST);
const Key AC_Promote = consumerKey(HID_CONSUMER_AC_PROMOTE);
const Key AC_Demote = consumerKey(HID_CONSUMER_AC_DEMOTE);
const Key AC_Yes = consumerKey(HID_CONSUMER_AC_YES);
const Key AC_No = consumerKey(HID_CONSUMER_AC_NO);
const Key AC_Cancel = consumerKey(HID_CONSUMER_AC_CANCEL);
const Key AC_Catalog = consumerKey(HID_CONSUMER_AC_CATALOG);
const Key AC_BuySlashCheckout = consumerKey(HID_CONSUMER_AC_BUY_SLASH_CHECKOUT);
const Key AC_AddToCart = consumerKey(HID_CONSUMER_AC_ADD_TO_CART);
const Key AC_Expand = consumerKey(HID_CONSUMER_AC_EXPAND);
const Key AC_ExpandAll = consumerKey(HID_CONSUMER_AC_EXPAND_ALL);
const Key AC_Collapse = consumerKey(HID_CONSUMER_AC_COLLAPSE);
const Key AC_CollapseAll = consumerKey(HID_CONSUMER_AC_COLLAPSE_ALL);
const Key AC_PrintPreview = consumerKey(HID_CONSUMER_AC_PRINT_PREVIEW);
const Key AC_PasteSpecial = consumerKey(HID_CONSUMER_AC_PASTE_SPECIAL);
const Key AC_InsertMode = consumerKey(HID_CONSUMER_AC_INSERT_MODE);
const Key AC_Delete = consumerKey(HID_CONSUMER_AC_DELETE);
const Key AC_Lock = consumerKey(HID_CONSUMER_AC_LOCK);
const Key AC_Unlock = consumerKey(HID_CONSUMER_AC_UNLOCK);
const Key AC_Protect = consumerKey(HID_CONSUMER_AC_PROTECT);
const Key AC_Unprotect = consumerKey(HID_CONSUMER_AC_UNPROTECT);
const Key AC_AttachComment = consumerKey(HID_CONSUMER_AC_ATTACH_COMMENT);
const Key AC_DeleteComment = consumerKey(HID_CONSUMER_AC_DELETE_COMMENT);
const Key AC_ViewComment = consumerKey(HID_CONSUMER_AC_VIEW_COMMENT);
const Key AC_SelectWord = consumerKey(HID_CONSUMER_AC_SELECT_WORD);
const Key AC_SelectSentence = consumerKey(HID_CONSUMER_AC_SELECT_SENTENCE);
const Key AC_SelectParagraph = consumerKey(HID_CONSUMER_AC_SELECT_PARAGRAPH);
const Key AC_SelectColumn = consumerKey(HID_CONSUMER_AC_SELECT_COLUMN);
const Key AC_SelectRow = consumerKey(HID_CONSUMER_AC_SELECT_ROW);
const Key AC_SelectTable = consumerKey(HID_CONSUMER_AC_SELECT_TABLE);
const Key AC_SelectObject = consumerKey(HID_CONSUMER_AC_SELECT_OBJECT);
const Key AC_RedoSlashRepeat = consumerKey(HID_CONSUMER_AC_REDO_SLASH_REPEAT);
const Key AC_Sort = consumerKey(HID_CONSUMER_AC_SORT);
const Key AC_Sort_Ascending = consumerKey(HID_CONSUMER_AC_SORT_ASCENDING);
const Key AC_Sort_Descending = consumerKey(HID_CONSUMER_AC_SORT_DESCENDING);
const Key AC_Filter = consumerKey(HID_CONSUMER_AC_FILTER);
const Key AC_SetClock = consumerKey(HID_CONSUMER_AC_SET_CLOCK);
const Key AC_ViewClock = consumerKey(HID_CONSUMER_AC_VIEW_CLOCK);
const Key AC_SelectTimeZone = consumerKey(HID_CONSUMER_AC_SELECT_TIME_ZONE);
const Key AC_EditTimeZones = consumerKey(HID_CONSUMER_AC_EDIT_TIME_ZONES);
const Key AC_SetAlarm = consumerKey(HID_CONSUMER_AC_SET_ALARM);
const Key AC_ClearAlarm = consumerKey(HID_CONSUMER_AC_CLEAR_ALARM);
const Key AC_SnoozeAlarm = consumerKey(HID_CONSUMER_AC_SNOOZE_ALARM);
const Key AC_ResetAlarm = consumerKey(HID_CONSUMER_AC_RESET_ALARM);
const Key AC_Synchronize = consumerKey(HID_CONSUMER_AC_SYNCHRONIZE);
const Key AC_SendSlashReceive = consumerKey(HID_CONSUMER_AC_SEND_SLASH_RECEIVE);
const Key AC_SendTo = consumerKey(HID_CONSUMER_AC_SEND_TO);
const Key AC_Reply = consumerKey(HID_CONSUMER_AC_REPLY);
const Key AC_ReplyAll = consumerKey(HID_CONSUMER_AC_REPLY_ALL);
const Key AC_ForwardMsg = consumerKey(HID_CONSUMER_AC_FORWARD_MSG);
const Key AC_Send = consumerKey(HID_CONSUMER_AC_SEND);
const Key AC_AttachFile = consumerKey(HID_CONSUMER_AC_ATTACH_FILE);
const Key AC_Upload = consumerKey(HID_CONSUMER_AC_UPLOAD);
const Key AC_Download = consumerKey(HID_CONSUMER_AC_DOWNLOAD);
const Key AC_SetBorders = consumerKey(HID_CONSUMER_AC_SET_BORDERS);
const Key AC_InsertRow = consumerKey(HID_CONSUMER_AC_INSERT_ROW);
const Key AC_InsertColumn = consumerKey(HID_CONSUMER_AC_INSERT_COLUMN);
const Key AC_InsertFile = consumerKey(HID_CONSUMER_AC_INSERT_FILE);
const Key AC_InsertPicture = consumerKey(HID_CONSUMER_AC_INSERT_PICTURE);
const Key AC_InsertObject = consumerKey(HID_CONSUMER_AC_INSERT_OBJECT);
const Key AC_InsertSymbol = consumerKey(HID_CONSUMER_AC_INSERT_SYMBOL);
const Key AC_SaveandClose = consumerKey(HID_CONSUMER_AC_SAVE_AND_CLOSE);
const Key AC_Rename = consumerKey(HID_CONSUMER_AC_RENAME);
const Key AC_Merge = consumerKey(HID_CONSUMER_AC_MERGE);
const Key AC_Split = consumerKey(HID_CONSUMER_AC_SPLIT);
const Key AC_Distribute_Horizontally = consumerKey(HID_CONSUMER_AC_DISTRIBUTE_HORIZONTALLY);
const Key AC_Distribute_Vertically = consumerKey(HID_CONSUMER_AC_DISTRIBUTE_VERTICALLY);

} // namespace consumer {

} // namespace cKey {

} // namespace kaleidoscope {
