#pragma once

// Keyboard HID mappings

// Reserved (no_event_indicated)
#define Key_NoEvent ::kaleidoglyph::cKeyboardKey::NoEvent
#define Key_ErrorRollover ::kaleidoglyph::cKeyboardKey::ErrorRollover
#define Key_PostFail ::kaleidoglyph::cKeyboardKey::PostFail
#define Key_ErrorUndefined ::kaleidoglyph::cKeyboardKey::ErrorUndefined
#define Key_A ::kaleidoglyph::cKeyboardKey::A
#define Key_B ::kaleidoglyph::cKeyboardKey::B
#define Key_C ::kaleidoglyph::cKeyboardKey::C
#define Key_D ::kaleidoglyph::cKeyboardKey::D
#define Key_E ::kaleidoglyph::cKeyboardKey::E
#define Key_F ::kaleidoglyph::cKeyboardKey::F
#define Key_G ::kaleidoglyph::cKeyboardKey::G
#define Key_H ::kaleidoglyph::cKeyboardKey::H
#define Key_I ::kaleidoglyph::cKeyboardKey::I
#define Key_J ::kaleidoglyph::cKeyboardKey::J
#define Key_K ::kaleidoglyph::cKeyboardKey::K
#define Key_L ::kaleidoglyph::cKeyboardKey::L
#define Key_M ::kaleidoglyph::cKeyboardKey::M
#define Key_N ::kaleidoglyph::cKeyboardKey::N
#define Key_O ::kaleidoglyph::cKeyboardKey::O
#define Key_P ::kaleidoglyph::cKeyboardKey::P
#define Key_Q ::kaleidoglyph::cKeyboardKey::Q
#define Key_R ::kaleidoglyph::cKeyboardKey::R
#define Key_S ::kaleidoglyph::cKeyboardKey::S
#define Key_T ::kaleidoglyph::cKeyboardKey::T
#define Key_U ::kaleidoglyph::cKeyboardKey::U
#define Key_V ::kaleidoglyph::cKeyboardKey::V
#define Key_W ::kaleidoglyph::cKeyboardKey::W
#define Key_X ::kaleidoglyph::cKeyboardKey::X
#define Key_Y ::kaleidoglyph::cKeyboardKey::Y
#define Key_Z ::kaleidoglyph::cKeyboardKey::Z
#define Key_1 ::kaleidoglyph::cKeyboardKey::_1
#define Key_2 ::kaleidoglyph::cKeyboardKey::_2
#define Key_3 ::kaleidoglyph::cKeyboardKey::_3
#define Key_4 ::kaleidoglyph::cKeyboardKey::_4
#define Key_5 ::kaleidoglyph::cKeyboardKey::_5
#define Key_6 ::kaleidoglyph::cKeyboardKey::_6
#define Key_7 ::kaleidoglyph::cKeyboardKey::_7
#define Key_8 ::kaleidoglyph::cKeyboardKey::_8
#define Key_9 ::kaleidoglyph::cKeyboardKey::_9
#define Key_0 ::kaleidoglyph::cKeyboardKey::_0
#define Key_Enter ::kaleidoglyph::cKeyboardKey::Enter
#define Key_Escape ::kaleidoglyph::cKeyboardKey::Escape
#define Key_Backspace ::kaleidoglyph::cKeyboardKey::Backspace
#define Key_Tab ::kaleidoglyph::cKeyboardKey::Tab
#define Key_Spacebar ::kaleidoglyph::cKeyboardKey::Spacebar
#define Key_Minus ::kaleidoglyph::cKeyboardKey::Minus
#define Key_Equals ::kaleidoglyph::cKeyboardKey::Equals
#define Key_LeftBracket ::kaleidoglyph::cKeyboardKey::LeftBracket
#define Key_RightBracket ::kaleidoglyph::cKeyboardKey::RightBracket
#define Key_Backslash ::kaleidoglyph::cKeyboardKey::Backslash
#define Key_NonUsPound ::kaleidoglyph::cKeyboardKey::NonUsPound
#define Key_Semicolon ::kaleidoglyph::cKeyboardKey::Semicolon
#define Key_Quote ::kaleidoglyph::cKeyboardKey::Quote
#define Key_Backtick ::kaleidoglyph::cKeyboardKey::Backtick
#define Key_Comma ::kaleidoglyph::cKeyboardKey::Comma
#define Key_Period ::kaleidoglyph::cKeyboardKey::Period
#define Key_Slash ::kaleidoglyph::cKeyboardKey::Slash
#define Key_CapsLock ::kaleidoglyph::cKeyboardKey::CapsLock
#define Key_F1 ::kaleidoglyph::cKeyboardKey::F1
#define Key_F2 ::kaleidoglyph::cKeyboardKey::F2
#define Key_F3 ::kaleidoglyph::cKeyboardKey::F3
#define Key_F4 ::kaleidoglyph::cKeyboardKey::F4
#define Key_F5 ::kaleidoglyph::cKeyboardKey::F5
#define Key_F6 ::kaleidoglyph::cKeyboardKey::F6
#define Key_F7 ::kaleidoglyph::cKeyboardKey::F7
#define Key_F8 ::kaleidoglyph::cKeyboardKey::F8
#define Key_F9 ::kaleidoglyph::cKeyboardKey::F9
#define Key_F10 ::kaleidoglyph::cKeyboardKey::F10
#define Key_F11 ::kaleidoglyph::cKeyboardKey::F11
#define Key_F12 ::kaleidoglyph::cKeyboardKey::F12
#define Key_PrintScreen ::kaleidoglyph::cKeyboardKey::PrintScreen
#define Key_ScrollLock ::kaleidoglyph::cKeyboardKey::ScrollLock
#define Key_Pause ::kaleidoglyph::cKeyboardKey::Pause
#define Key_Insert ::kaleidoglyph::cKeyboardKey::Insert
#define Key_Home ::kaleidoglyph::cKeyboardKey::Home
#define Key_PageUp ::kaleidoglyph::cKeyboardKey::PageUp
#define Key_Delete ::kaleidoglyph::cKeyboardKey::Delete
#define Key_End ::kaleidoglyph::cKeyboardKey::End
#define Key_PageDown ::kaleidoglyph::cKeyboardKey::PageDown
#define Key_RightArrow ::kaleidoglyph::cKeyboardKey::RightArrow
#define Key_LeftArrow ::kaleidoglyph::cKeyboardKey::LeftArrow
#define Key_DownArrow ::kaleidoglyph::cKeyboardKey::DownArrow
#define Key_UpArrow ::kaleidoglyph::cKeyboardKey::UpArrow
#define Key_KeypadNumLock ::kaleidoglyph::cKeyboardKey::KeypadNumLock
#define Key_KeypadDivide ::kaleidoglyph::cKeyboardKey::KeypadDivide
#define Key_KeypadMultiply ::kaleidoglyph::cKeyboardKey::KeypadMultiply
#define Key_KeypadSubtract ::kaleidoglyph::cKeyboardKey::KeypadSubtract
#define Key_KeypadAdd ::kaleidoglyph::cKeyboardKey::KeypadAdd
#define Key_KeypadEnter ::kaleidoglyph::cKeyboardKey::KeypadEnter
#define Key_Keypad1 ::kaleidoglyph::cKeyboardKey::Keypad1
#define Key_Keypad2 ::kaleidoglyph::cKeyboardKey::Keypad2
#define Key_Keypad3 ::kaleidoglyph::cKeyboardKey::Keypad3
#define Key_Keypad4 ::kaleidoglyph::cKeyboardKey::Keypad4
#define Key_Keypad5 ::kaleidoglyph::cKeyboardKey::Keypad5
#define Key_Keypad6 ::kaleidoglyph::cKeyboardKey::Keypad6
#define Key_Keypad7 ::kaleidoglyph::cKeyboardKey::Keypad7
#define Key_Keypad8 ::kaleidoglyph::cKeyboardKey::Keypad8
#define Key_Keypad9 ::kaleidoglyph::cKeyboardKey::Keypad9
#define Key_Keypad0 ::kaleidoglyph::cKeyboardKey::Keypad0
#define Key_KeypadDot ::kaleidoglyph::cKeyboardKey::KeypadDot
#define Key_NonUsBackslashAndPipe ::kaleidoglyph::cKeyboardKey::NonUsBackslashAndPipe
#define Key_PcApplication ::kaleidoglyph::cKeyboardKey::PcApplication
#define Key_Power ::kaleidoglyph::cKeyboardKey::Power
#define Key_KeypadEquals ::kaleidoglyph::cKeyboardKey::KeypadEquals
#define Key_F13 ::kaleidoglyph::cKeyboardKey::F13
#define Key_F14 ::kaleidoglyph::cKeyboardKey::F14
#define Key_F15 ::kaleidoglyph::cKeyboardKey::F15
#define Key_F16 ::kaleidoglyph::cKeyboardKey::F16
#define Key_F17 ::kaleidoglyph::cKeyboardKey::F17
#define Key_F18 ::kaleidoglyph::cKeyboardKey::F18
#define Key_F19 ::kaleidoglyph::cKeyboardKey::F19
#define Key_F20 ::kaleidoglyph::cKeyboardKey::F20
#define Key_F21 ::kaleidoglyph::cKeyboardKey::F21
#define Key_F22 ::kaleidoglyph::cKeyboardKey::F22
#define Key_F23 ::kaleidoglyph::cKeyboardKey::F23
#define Key_F24 ::kaleidoglyph::cKeyboardKey::F24
#define Key_Execute ::kaleidoglyph::cKeyboardKey::Execute
#define Key_Help ::kaleidoglyph::cKeyboardKey::Help
#define Key_Menu ::kaleidoglyph::cKeyboardKey::Menu
#define Key_Select ::kaleidoglyph::cKeyboardKey::Select
#define Key_Stop ::kaleidoglyph::cKeyboardKey::Stop
#define Key_Again ::kaleidoglyph::cKeyboardKey::Again
#define Key_Undo ::kaleidoglyph::cKeyboardKey::Undo
#define Key_Cut ::kaleidoglyph::cKeyboardKey::Cut
#define Key_Copy ::kaleidoglyph::cKeyboardKey::Copy
#define Key_Paste ::kaleidoglyph::cKeyboardKey::Paste
#define Key_Find ::kaleidoglyph::cKeyboardKey::Find
#define Key_Mute ::kaleidoglyph::cKeyboardKey::Mute
#define Key_VolumeUp ::kaleidoglyph::cKeyboardKey::VolumeUp
#define Key_VolumeDown ::kaleidoglyph::cKeyboardKey::VolumeDown
#define Key_LockingCapsLock ::kaleidoglyph::cKeyboardKey::LockingCapsLock
#define Key_LockingNumLock ::kaleidoglyph::cKeyboardKey::LockingNumLock
#define Key_LockingScrollLock ::kaleidoglyph::cKeyboardKey::LockingScrollLock
#define Key_KeypadComma ::kaleidoglyph::cKeyboardKey::KeypadComma
#define Key_KeypadEqualSign ::kaleidoglyph::cKeyboardKey::KeypadEqualSign
#define Key_International1 ::kaleidoglyph::cKeyboardKey::International1
#define Key_International2 ::kaleidoglyph::cKeyboardKey::International2
#define Key_International3 ::kaleidoglyph::cKeyboardKey::International3
#define Key_International4 ::kaleidoglyph::cKeyboardKey::International4
#define Key_International5 ::kaleidoglyph::cKeyboardKey::International5
#define Key_International6 ::kaleidoglyph::cKeyboardKey::International6
#define Key_International7 ::kaleidoglyph::cKeyboardKey::International7
#define Key_International8 ::kaleidoglyph::cKeyboardKey::International8
#define Key_International9 ::kaleidoglyph::cKeyboardKey::International9
#define Key_Lang1 ::kaleidoglyph::cKeyboardKey::Lang1
#define Key_Lang2 ::kaleidoglyph::cKeyboardKey::Lang2
#define Key_Lang3 ::kaleidoglyph::cKeyboardKey::Lang3
#define Key_Lang4 ::kaleidoglyph::cKeyboardKey::Lang4
#define Key_Lang5 ::kaleidoglyph::cKeyboardKey::Lang5
#define Key_Lang6 ::kaleidoglyph::cKeyboardKey::Lang6
#define Key_Lang7 ::kaleidoglyph::cKeyboardKey::Lang7
#define Key_Lang8 ::kaleidoglyph::cKeyboardKey::Lang8
#define Key_Lang9 ::kaleidoglyph::cKeyboardKey::Lang9
#define Key_AlternateErase ::kaleidoglyph::cKeyboardKey::AlternateErase
#define Key_Sysreq ::kaleidoglyph::cKeyboardKey::Sysreq
#define Key_Cancel ::kaleidoglyph::cKeyboardKey::Cancel
#define Key_Clear ::kaleidoglyph::cKeyboardKey::Clear
#define Key_Prior ::kaleidoglyph::cKeyboardKey::Prior
#define Key_Return ::kaleidoglyph::cKeyboardKey::Return
#define Key_Separator ::kaleidoglyph::cKeyboardKey::Separator
#define Key_Out ::kaleidoglyph::cKeyboardKey::Out
#define Key_Oper ::kaleidoglyph::cKeyboardKey::Oper
#define Key_ClearSlashAgain ::kaleidoglyph::cKeyboardKey::ClearSlashAgain
#define Key_CrselSlashProps ::kaleidoglyph::cKeyboardKey::CrselSlashProps
#define Key_Exsel ::kaleidoglyph::cKeyboardKey::Exsel
// Reserved	0xA5-AF
#define Key_Keypad00 ::kaleidoglyph::cKeyboardKey::Keypad00
#define Key_Keypad000 ::kaleidoglyph::cKeyboardKey::Keypad000
#define Key_ThousandsSeparator ::kaleidoglyph::cKeyboardKey::ThousandsSeparator
#define Key_DecimalSeparator ::kaleidoglyph::cKeyboardKey::DecimalSeparator
#define Key_CurrencyUnit ::kaleidoglyph::cKeyboardKey::CurrencyUnit
#define Key_CurrencySubunit ::kaleidoglyph::cKeyboardKey::CurrencySubunit
#define Key_KeypadLeftParen ::kaleidoglyph::cKeyboardKey::KeypadLeftParen
#define Key_KeypadRightParen ::kaleidoglyph::cKeyboardKey::KeypadRightParen
#define Key_KeypadLeftCurlyBrace ::kaleidoglyph::cKeyboardKey::KeypadLeftCurlyBrace
#define Key_KeypadRightCurlyBrace ::kaleidoglyph::cKeyboardKey::KeypadRightCurlyBrace
#define Key_KeypadTab ::kaleidoglyph::cKeyboardKey::KeypadTab
#define Key_KeypadBackspace ::kaleidoglyph::cKeyboardKey::KeypadBackspace
#define Key_KeypadA ::kaleidoglyph::cKeyboardKey::KeypadA
#define Key_KeypadB ::kaleidoglyph::cKeyboardKey::KeypadB
#define Key_KeypadC ::kaleidoglyph::cKeyboardKey::KeypadC
#define Key_KeypadD ::kaleidoglyph::cKeyboardKey::KeypadD
#define Key_KeypadE ::kaleidoglyph::cKeyboardKey::KeypadE
#define Key_KeypadF ::kaleidoglyph::cKeyboardKey::KeypadF
#define Key_KeypadXor ::kaleidoglyph::cKeyboardKey::KeypadXor
#define Key_KeypadCarat ::kaleidoglyph::cKeyboardKey::KeypadCarat
#define Key_KeypadPercent ::kaleidoglyph::cKeyboardKey::KeypadPercent
#define Key_KeypadLessThan ::kaleidoglyph::cKeyboardKey::KeypadLessThan
#define Key_KeypadGreaterThan ::kaleidoglyph::cKeyboardKey::KeypadGreaterThan
#define Key_KeypadAmpersand ::kaleidoglyph::cKeyboardKey::KeypadAmpersand
#define Key_KeypadDoubleampersand ::kaleidoglyph::cKeyboardKey::KeypadDoubleampersand
#define Key_KeypadPipe ::kaleidoglyph::cKeyboardKey::KeypadPipe
#define Key_KeypadDoublepipe ::kaleidoglyph::cKeyboardKey::KeypadDoublepipe
#define Key_KeypadColon ::kaleidoglyph::cKeyboardKey::KeypadColon
#define Key_KeypadPoundSign ::kaleidoglyph::cKeyboardKey::KeypadPoundSign
#define Key_KeypadSpace ::kaleidoglyph::cKeyboardKey::KeypadSpace
#define Key_KeypadAtSign ::kaleidoglyph::cKeyboardKey::KeypadAtSign
#define Key_KeypadExclamationPoint ::kaleidoglyph::cKeyboardKey::KeypadExclamationPoint
#define Key_KeypadMemoryStore ::kaleidoglyph::cKeyboardKey::KeypadMemoryStore
#define Key_KeypadMemoryRecall ::kaleidoglyph::cKeyboardKey::KeypadMemoryRecall
#define Key_KeypadMemoryClear ::kaleidoglyph::cKeyboardKey::KeypadMemoryClear
#define Key_KeypadMemoryAdd ::kaleidoglyph::cKeyboardKey::KeypadMemoryAdd
#define Key_KeypadMemorySubtract ::kaleidoglyph::cKeyboardKey::KeypadMemorySubtract
#define Key_KeypadMemoryMultiply ::kaleidoglyph::cKeyboardKey::KeypadMemoryMultiply
#define Key_KeypadMemoryDivide ::kaleidoglyph::cKeyboardKey::KeypadMemoryDivide
#define Key_KeypadPlusSlashMinus ::kaleidoglyph::cKeyboardKey::KeypadPlusSlashMinus
#define Key_KeypadClear ::kaleidoglyph::cKeyboardKey::KeypadClear
#define Key_KeypadClearEntry ::kaleidoglyph::cKeyboardKey::KeypadClearEntry
#define Key_KeypadBinary ::kaleidoglyph::cKeyboardKey::KeypadBinary
#define Key_KeypadOctal ::kaleidoglyph::cKeyboardKey::KeypadOctal
#define Key_KeypadDecimal ::kaleidoglyph::cKeyboardKey::KeypadDecimal
#define Key_KeypadHexadecimal ::kaleidoglyph::cKeyboardKey::KeypadHexadecimal

#define Key_LeftControl ::kaleidoglyph::cKeyboardKey::LeftControl
#define Key_LeftShift ::kaleidoglyph::cKeyboardKey::LeftShift
#define Key_LeftAlt ::kaleidoglyph::cKeyboardKey::LeftAlt
#define Key_LeftGui ::kaleidoglyph::cKeyboardKey::LeftGui
#define Key_RightControl ::kaleidoglyph::cKeyboardKey::RightControl
#define Key_RightShift ::kaleidoglyph::cKeyboardKey::RightShift
#define Key_RightAlt ::kaleidoglyph::cKeyboardKey::RightAlt
#define Key_RightGui ::kaleidoglyph::cKeyboardKey::RightGui


