#pragma once


#define Consumer_NumericKeyPad ::kaleidoglyph::cConsumerKey::NumericKeyPad
#define Consumer_ProgrammableButtons ::kaleidoglyph::cConsumerKey::ProgrammableButtons
#define Consumer_MicrophoneCa ::kaleidoglyph::cConsumerKey::MicrophoneCa
#define Consumer_HeadphoneCa ::kaleidoglyph::cConsumerKey::HeadphoneCa
#define Consumer_GraphicEqualizerCa ::kaleidoglyph::cConsumerKey::GraphicEqualizerCa

#define Consumer_Plus10 ::kaleidoglyph::cConsumerKey::Plus10
#define Consumer_Plus100 ::kaleidoglyph::cConsumerKey::Plus100
#define Consumer_AMSlashPM ::kaleidoglyph::cConsumerKey::AMSlashPM

#define Consumer_Power ::kaleidoglyph::cConsumerKey::Power
#define Consumer_Reset ::kaleidoglyph::cConsumerKey::Reset
#define Consumer_Sleep ::kaleidoglyph::cConsumerKey::Sleep
#define Consumer_Sleep_After ::kaleidoglyph::cConsumerKey::Sleep_After
#define Consumer_Sleep_Mode ::kaleidoglyph::cConsumerKey::Sleep_Mode
#define Consumer_Illumination ::kaleidoglyph::cConsumerKey::Illumination
#define Consumer_Function_Buttons ::kaleidoglyph::cConsumerKey::Function_Buttons

#define Consumer_Menu ::kaleidoglyph::cConsumerKey::Menu
#define Consumer_MenuPick ::kaleidoglyph::cConsumerKey::MenuPick
#define Consumer_MenuUp ::kaleidoglyph::cConsumerKey::MenuUp
#define Consumer_MenuDown ::kaleidoglyph::cConsumerKey::MenuDown
#define Consumer_MenuLeft ::kaleidoglyph::cConsumerKey::MenuLeft
#define Consumer_MenuRight ::kaleidoglyph::cConsumerKey::MenuRight
#define Consumer_MenuEscape ::kaleidoglyph::cConsumerKey::MenuEscape
#define Consumer_MenuValueIncrease ::kaleidoglyph::cConsumerKey::MenuValueIncrease
#define Consumer_MenuValueDecrease ::kaleidoglyph::cConsumerKey::MenuValueDecrease

#define Consumer_DataOnScreen ::kaleidoglyph::cConsumerKey::DataOnScreen
#define Consumer_ClosedCaption ::kaleidoglyph::cConsumerKey::ClosedCaption
#define Consumer_ClosedCaptionSelect ::kaleidoglyph::cConsumerKey::ClosedCaptionSelect
#define Consumer_VCRSlashTV ::kaleidoglyph::cConsumerKey::VCRSlashTV
#define Consumer_BroadcastMode ::kaleidoglyph::cConsumerKey::BroadcastMode
#define Consumer_SNapshot ::kaleidoglyph::cConsumerKey::SNapshot
#define Consumer_Still ::kaleidoglyph::cConsumerKey::Still

#define Consumer_Selection ::kaleidoglyph::cConsumerKey::Selection
#define Consumer_AssignSelection ::kaleidoglyph::cConsumerKey::AssignSelection
#define Consumer_ModeStep ::kaleidoglyph::cConsumerKey::ModeStep
#define Consumer_RecallLast ::kaleidoglyph::cConsumerKey::RecallLast
#define Consumer_EnterChannel ::kaleidoglyph::cConsumerKey::EnterChannel
#define Consumer_OrderMovie ::kaleidoglyph::cConsumerKey::OrderMovie
#define Consumer_Channel ::kaleidoglyph::cConsumerKey::Channel
#define Consumer_MediaSelection ::kaleidoglyph::cConsumerKey::MediaSelection
#define Consumer_MediaSelectComputer ::kaleidoglyph::cConsumerKey::MediaSelectComputer
#define Consumer_MediaSelectTV ::kaleidoglyph::cConsumerKey::MediaSelectTV
#define Consumer_MediaSelectWww ::kaleidoglyph::cConsumerKey::MediaSelectWww
#define Consumer_MediaSelectDvd ::kaleidoglyph::cConsumerKey::MediaSelectDvd
#define Consumer_MediaSelectTelephone ::kaleidoglyph::cConsumerKey::MediaSelectTelephone
#define Consumer_MediaSelectProgramGuide ::kaleidoglyph::cConsumerKey::MediaSelectProgramGuide
#define Consumer_MediaSelectVideoPhone ::kaleidoglyph::cConsumerKey::MediaSelectVideoPhone
#define Consumer_MediaSelectGames ::kaleidoglyph::cConsumerKey::MediaSelectGames
#define Consumer_MediaSelectMessages ::kaleidoglyph::cConsumerKey::MediaSelectMessages
#define Consumer_MediaSelectCd ::kaleidoglyph::cConsumerKey::MediaSelectCd
#define Consumer_MediaSelectVcr ::kaleidoglyph::cConsumerKey::MediaSelectVcr
#define Consumer_MediaSelectTuner ::kaleidoglyph::cConsumerKey::MediaSelectTuner
#define Consumer_Quit ::kaleidoglyph::cConsumerKey::Quit
#define Consumer_Help ::kaleidoglyph::cConsumerKey::Help
#define Consumer_MediaSelectTape ::kaleidoglyph::cConsumerKey::MediaSelectTape
#define Consumer_MediaSelectCable ::kaleidoglyph::cConsumerKey::MediaSelectCable
#define Consumer_MediaSelectSatellite ::kaleidoglyph::cConsumerKey::MediaSelectSatellite
#define Consumer_MediaSelectSecurity ::kaleidoglyph::cConsumerKey::MediaSelectSecurity
#define Consumer_MediaSelectHome ::kaleidoglyph::cConsumerKey::MediaSelectHome
#define Consumer_MediaSelectCall ::kaleidoglyph::cConsumerKey::MediaSelectCall
#define Consumer_ChannelIncrement ::kaleidoglyph::cConsumerKey::ChannelIncrement
#define Consumer_ChannelDecrement ::kaleidoglyph::cConsumerKey::ChannelDecrement
#define Consumer_MediaSelectSap ::kaleidoglyph::cConsumerKey::MediaSelectSap

#define Consumer_VcrPlus ::kaleidoglyph::cConsumerKey::VcrPlus
#define Consumer_Once ::kaleidoglyph::cConsumerKey::Once
#define Consumer_Daily ::kaleidoglyph::cConsumerKey::Daily
#define Consumer_Weekly ::kaleidoglyph::cConsumerKey::Weekly
#define Consumer_Monthly ::kaleidoglyph::cConsumerKey::Monthly

#define Consumer_Play ::kaleidoglyph::cConsumerKey::Play
#define Consumer_Pause ::kaleidoglyph::cConsumerKey::Pause
#define Consumer_Record ::kaleidoglyph::cConsumerKey::Record
#define Consumer_FastForward ::kaleidoglyph::cConsumerKey::FastForward
#define Consumer_Rewind ::kaleidoglyph::cConsumerKey::Rewind
#define Consumer_ScanNextTrack ::kaleidoglyph::cConsumerKey::ScanNextTrack
#define Consumer_ScanPreviousTrack ::kaleidoglyph::cConsumerKey::ScanPreviousTrack
#define Consumer_Stop ::kaleidoglyph::cConsumerKey::Stop
#define Consumer_Eject ::kaleidoglyph::cConsumerKey::Eject
#define Consumer_RandomPlay ::kaleidoglyph::cConsumerKey::RandomPlay
#define Consumer_SelectDisc ::kaleidoglyph::cConsumerKey::SelectDisc
#define Consumer_EnterDiscMc ::kaleidoglyph::cConsumerKey::EnterDiscMc
#define Consumer_Repeat ::kaleidoglyph::cConsumerKey::Repeat
#define Consumer_Tracking ::kaleidoglyph::cConsumerKey::Tracking
#define Consumer_Track_Normal ::kaleidoglyph::cConsumerKey::Track_Normal
#define Consumer_SlowTracking ::kaleidoglyph::cConsumerKey::SlowTracking
#define Consumer_FrameForward ::kaleidoglyph::cConsumerKey::FrameForward
#define Consumer_FrameBack ::kaleidoglyph::cConsumerKey::FrameBack
#define Consumer_Mark ::kaleidoglyph::cConsumerKey::Mark
#define Consumer_ClearMark ::kaleidoglyph::cConsumerKey::ClearMark
#define Consumer_RepeatFromMark ::kaleidoglyph::cConsumerKey::RepeatFromMark
#define Consumer_ReturnTo_Mark ::kaleidoglyph::cConsumerKey::ReturnTo_Mark
#define Consumer_SearchMarkForward ::kaleidoglyph::cConsumerKey::SearchMarkForward
#define Consumer_SearchMarkBackwards ::kaleidoglyph::cConsumerKey::SearchMarkBackwards
#define Consumer_CounterReset ::kaleidoglyph::cConsumerKey::CounterReset
#define Consumer_ShowCounter ::kaleidoglyph::cConsumerKey::ShowCounter
#define Consumer_TrackingIncrement ::kaleidoglyph::cConsumerKey::TrackingIncrement
#define Consumer_TrackingDecrement ::kaleidoglyph::cConsumerKey::TrackingDecrement
#define Consumer_StopSlashEject ::kaleidoglyph::cConsumerKey::StopSlashEject
#define Consumer_PlaySlashPause ::kaleidoglyph::cConsumerKey::PlaySlashPause
#define Consumer_PlaySlashSkip ::kaleidoglyph::cConsumerKey::PlaySlashSkip
#define Consumer_Volume ::kaleidoglyph::cConsumerKey::Volume
#define Consumer_Balance ::kaleidoglyph::cConsumerKey::Balance
#define Consumer_Mute ::kaleidoglyph::cConsumerKey::Mute
#define Consumer_Bass ::kaleidoglyph::cConsumerKey::Bass
#define Consumer_Treble ::kaleidoglyph::cConsumerKey::Treble
#define Consumer_BassBoost ::kaleidoglyph::cConsumerKey::BassBoost
#define Consumer_SurroundMode ::kaleidoglyph::cConsumerKey::SurroundMode
#define Consumer_Loudness ::kaleidoglyph::cConsumerKey::Loudness
#define Consumer_Mpx ::kaleidoglyph::cConsumerKey::Mpx
#define Consumer_VolumeIncrement ::kaleidoglyph::cConsumerKey::VolumeIncrement


#define Consumer_VolumeDecrement ::kaleidoglyph::cConsumerKey::VolumeDecrement

#define Consumer_SpeedSelect ::kaleidoglyph::cConsumerKey::SpeedSelect
#define Consumer_PlaybackSpeed ::kaleidoglyph::cConsumerKey::PlaybackSpeed
#define Consumer_StandardPlay ::kaleidoglyph::cConsumerKey::StandardPlay
#define Consumer_LongPlay ::kaleidoglyph::cConsumerKey::LongPlay
#define Consumer_ExtendedPlay ::kaleidoglyph::cConsumerKey::ExtendedPlay
#define Consumer_Slow ::kaleidoglyph::cConsumerKey::Slow

#define Consumer_FanEnable ::kaleidoglyph::cConsumerKey::FanEnable
#define Consumer_FanSpeed ::kaleidoglyph::cConsumerKey::FanSpeed
#define Consumer_LightEnable ::kaleidoglyph::cConsumerKey::LightEnable
#define Consumer_LightIlluminationLevel ::kaleidoglyph::cConsumerKey::LightIlluminationLevel
#define Consumer_ClimateControlEnable ::kaleidoglyph::cConsumerKey::ClimateControlEnable
#define Consumer_RoomTemperature ::kaleidoglyph::cConsumerKey::RoomTemperature
#define Consumer_SecurityEnable ::kaleidoglyph::cConsumerKey::SecurityEnable
#define Consumer_FireAlarm ::kaleidoglyph::cConsumerKey::FireAlarm
#define Consumer_PoliceAlarm ::kaleidoglyph::cConsumerKey::PoliceAlarm
#define Consumer_Proximity ::kaleidoglyph::cConsumerKey::Proximity
#define Consumer_Motion ::kaleidoglyph::cConsumerKey::Motion
#define Consumer_DuressAlarm ::kaleidoglyph::cConsumerKey::DuressAlarm
#define Consumer_HoldupAlarm ::kaleidoglyph::cConsumerKey::HoldupAlarm
#define Consumer_MedicalAlarm ::kaleidoglyph::cConsumerKey::MedicalAlarm

#define Consumer_BalanceRight ::kaleidoglyph::cConsumerKey::BalanceRight
#define Consumer_BalanceLeft ::kaleidoglyph::cConsumerKey::BalanceLeft
#define Consumer_BassIncrement ::kaleidoglyph::cConsumerKey::BassIncrement
#define Consumer_BassDecrement ::kaleidoglyph::cConsumerKey::BassDecrement
#define Consumer_TrebleIncrement ::kaleidoglyph::cConsumerKey::TrebleIncrement
#define Consumer_TrebleDecrement ::kaleidoglyph::cConsumerKey::TrebleDecrement

#define Consumer_SpeakerSystem ::kaleidoglyph::cConsumerKey::SpeakerSystem
#define Consumer_ChannelLeft ::kaleidoglyph::cConsumerKey::ChannelLeft
#define Consumer_ChannelRight ::kaleidoglyph::cConsumerKey::ChannelRight
#define Consumer_ChannelCenter ::kaleidoglyph::cConsumerKey::ChannelCenter
#define Consumer_ChannelFront ::kaleidoglyph::cConsumerKey::ChannelFront
#define Consumer_ChannelCenterFront ::kaleidoglyph::cConsumerKey::ChannelCenterFront
#define Consumer_ChannelSide ::kaleidoglyph::cConsumerKey::ChannelSide
#define Consumer_ChannelSurround ::kaleidoglyph::cConsumerKey::ChannelSurround
#define Consumer_ChannelLowFrequencyEnhancement ::kaleidoglyph::cConsumerKey::ChannelLowFrequencyEnhancement
#define Consumer_ChannelTop ::kaleidoglyph::cConsumerKey::ChannelTop
#define Consumer_ChannelUnknown ::kaleidoglyph::cConsumerKey::ChannelUnknown

#define Consumer_SubChannel ::kaleidoglyph::cConsumerKey::SubChannel
#define Consumer_SubChannelIncrement ::kaleidoglyph::cConsumerKey::SubChannelIncrement
#define Consumer_SubChannelDecrement ::kaleidoglyph::cConsumerKey::SubChannelDecrement
#define Consumer_AlternateAudioIncrement ::kaleidoglyph::cConsumerKey::AlternateAudioIncrement
#define Consumer_AlternateAudioDecrement ::kaleidoglyph::cConsumerKey::AlternateAudioDecrement

#define Consumer_Application_Launch_Buttons ::kaleidoglyph::cConsumerKey::Application_Launch_Buttons
#define Consumer_AL_Launch_Button_Configuration_Tool ::kaleidoglyph::cConsumerKey::AL_Launch_Button_Configuration_Tool
#define Consumer_AL_Programmable_Button_Configuration ::kaleidoglyph::cConsumerKey::AL_Programmable_Button_Configuration
#define Consumer_AL_Consumer_Control_Configuration ::kaleidoglyph::cConsumerKey::AL_Consumer_Control_Configuration
#define Consumer_AL_Word_Processor ::kaleidoglyph::cConsumerKey::AL_Word_Processor
#define Consumer_AL_Text_Editor ::kaleidoglyph::cConsumerKey::AL_Text_Editor
#define Consumer_AL_Spreadsheet ::kaleidoglyph::cConsumerKey::AL_Spreadsheet
#define Consumer_AL_Graphics_Editor ::kaleidoglyph::cConsumerKey::AL_Graphics_Editor
#define Consumer_AL_Presentation_App ::kaleidoglyph::cConsumerKey::AL_Presentation_App
#define Consumer_AL_Database_App ::kaleidoglyph::cConsumerKey::AL_Database_App
#define Consumer_AL_Email_Reader ::kaleidoglyph::cConsumerKey::AL_Email_Reader
#define Consumer_AL_Newsreader ::kaleidoglyph::cConsumerKey::AL_Newsreader
#define Consumer_AL_Voicemail ::kaleidoglyph::cConsumerKey::AL_Voicemail
#define Consumer_AL_Contacts_Slash_Address_Book ::kaleidoglyph::cConsumerKey::AL_Contacts_Slash_Address_Book
#define Consumer_AL_Calendar_Slash_Schedule ::kaleidoglyph::cConsumerKey::AL_Calendar_Slash_Schedule
#define Consumer_AL_Task_Slash_Project_Manager ::kaleidoglyph::cConsumerKey::AL_Task_Slash_Project_Manager
#define Consumer_AL_Log_Slash_Journal_Slash_Timecard ::kaleidoglyph::cConsumerKey::AL_Log_Slash_Journal_Slash_Timecard
#define Consumer_AL_Checkbook_Slash_Finance ::kaleidoglyph::cConsumerKey::AL_Checkbook_Slash_Finance
#define Consumer_AL_Calculator ::kaleidoglyph::cConsumerKey::AL_Calculator
#define Consumer_AL_AVCaptureSlashPlayback ::kaleidoglyph::cConsumerKey::AL_AVCaptureSlashPlayback
#define Consumer_AL_Local_MachineBrowser ::kaleidoglyph::cConsumerKey::AL_Local_MachineBrowser
#define Consumer_AL_Lan_SlashWanBrowser ::kaleidoglyph::cConsumerKey::AL_Lan_SlashWanBrowser
#define Consumer_AL_InternetBrowser ::kaleidoglyph::cConsumerKey::AL_InternetBrowser
#define Consumer_AL_RemoteNetworkingSlashIspConnect ::kaleidoglyph::cConsumerKey::AL_RemoteNetworkingSlashIspConnect
#define Consumer_AL_NetworkConference ::kaleidoglyph::cConsumerKey::AL_NetworkConference
#define Consumer_AL_NetworkChat ::kaleidoglyph::cConsumerKey::AL_NetworkChat
#define Consumer_AL_TelephonySlashDialer ::kaleidoglyph::cConsumerKey::AL_TelephonySlashDialer
#define Consumer_AL_Logon ::kaleidoglyph::cConsumerKey::AL_Logon
#define Consumer_AL_Logoff ::kaleidoglyph::cConsumerKey::AL_Logoff
#define Consumer_AL_LogonSlashLogoff ::kaleidoglyph::cConsumerKey::AL_LogonSlashLogoff
#define Consumer_AL_TerminalLockSlashScreensaver ::kaleidoglyph::cConsumerKey::AL_TerminalLockSlashScreensaver
#define Consumer_AL_ControlPanel ::kaleidoglyph::cConsumerKey::AL_ControlPanel
#define Consumer_AL_CommandLineProcessorSlashRun ::kaleidoglyph::cConsumerKey::AL_CommandLineProcessorSlashRun
#define Consumer_AL_ProcessSlashTask_Manager ::kaleidoglyph::cConsumerKey::AL_ProcessSlashTask_Manager
#define Consumer_AL_SelectTaskSlashApplication ::kaleidoglyph::cConsumerKey::AL_SelectTaskSlashApplication
#define Consumer_AL_NextTaskSlashApplication ::kaleidoglyph::cConsumerKey::AL_NextTaskSlashApplication
#define Consumer_AL_PreviousTaskSlashApplication ::kaleidoglyph::cConsumerKey::AL_PreviousTaskSlashApplication
#define Consumer_AL_PreemptiveHaltTaskSlashApplication ::kaleidoglyph::cConsumerKey::AL_PreemptiveHaltTaskSlashApplication
#define Consumer_AL_IntegratedHelpCenter ::kaleidoglyph::cConsumerKey::AL_IntegratedHelpCenter
#define Consumer_AL_Documents ::kaleidoglyph::cConsumerKey::AL_Documents
#define Consumer_AL_Thesaurus ::kaleidoglyph::cConsumerKey::AL_Thesaurus
#define Consumer_AL_Dictionary ::kaleidoglyph::cConsumerKey::AL_Dictionary
#define Consumer_AL_Desktop ::kaleidoglyph::cConsumerKey::AL_Desktop
#define Consumer_AL_SpellCheck ::kaleidoglyph::cConsumerKey::AL_SpellCheck
#define Consumer_AL_GrammarCheck ::kaleidoglyph::cConsumerKey::AL_GrammarCheck
#define Consumer_AL_WirelessStatus ::kaleidoglyph::cConsumerKey::AL_WirelessStatus
#define Consumer_AL_KeyboardLayout ::kaleidoglyph::cConsumerKey::AL_KeyboardLayout
#define Consumer_AL_VirusProtection ::kaleidoglyph::cConsumerKey::AL_VirusProtection
#define Consumer_AL_Encryption ::kaleidoglyph::cConsumerKey::AL_Encryption
#define Consumer_AL_ScreenSaver ::kaleidoglyph::cConsumerKey::AL_ScreenSaver
#define Consumer_AL_Alarms ::kaleidoglyph::cConsumerKey::AL_Alarms
#define Consumer_AL_Clock ::kaleidoglyph::cConsumerKey::AL_Clock
#define Consumer_AL_FileBrowser ::kaleidoglyph::cConsumerKey::AL_FileBrowser
#define Consumer_AL_PowerStatus ::kaleidoglyph::cConsumerKey::AL_PowerStatus
#define Consumer_AL_ImageBrowser ::kaleidoglyph::cConsumerKey::AL_ImageBrowser
#define Consumer_AL_AudioBrowser ::kaleidoglyph::cConsumerKey::AL_AudioBrowser
#define Consumer_AL_MovieBrowser ::kaleidoglyph::cConsumerKey::AL_MovieBrowser
#define Consumer_AL_DigitalRightsManager ::kaleidoglyph::cConsumerKey::AL_DigitalRightsManager
#define Consumer_AL_DigitalWallet ::kaleidoglyph::cConsumerKey::AL_DigitalWallet

#define Consumer_AL_InstantMessaging ::kaleidoglyph::cConsumerKey::AL_InstantMessaging
#define Consumer_AL_OemFeaturesSlashTipsSlashTUTORIALBrowser ::kaleidoglyph::cConsumerKey::AL_OemFeaturesSlashTipsSlashTUTORIALBrowser
#define Consumer_AL_OemHelp ::kaleidoglyph::cConsumerKey::AL_OemHelp
#define Consumer_AL_OnlineCommunity ::kaleidoglyph::cConsumerKey::AL_OnlineCommunity
#define Consumer_AL_Entertainment_Content_Browser ::kaleidoglyph::cConsumerKey::AL_Entertainment_Content_Browser
#define Consumer_AL_OnlineShoppingBrowser ::kaleidoglyph::cConsumerKey::AL_OnlineShoppingBrowser
#define Consumer_AL_SmartcardInformationSlashHelp ::kaleidoglyph::cConsumerKey::AL_SmartcardInformationSlashHelp
#define Consumer_AL_MarketMonitorSlashFinanceBrowser ::kaleidoglyph::cConsumerKey::AL_MarketMonitorSlashFinanceBrowser
#define Consumer_AL_CustomizedCorporateNewsBrowser ::kaleidoglyph::cConsumerKey::AL_CustomizedCorporateNewsBrowser
#define Consumer_AL_OnlineActivityBrowser ::kaleidoglyph::cConsumerKey::AL_OnlineActivityBrowser
#define Consumer_AL_ResearchSlashSearchBrowser ::kaleidoglyph::cConsumerKey::AL_ResearchSlashSearchBrowser
#define Consumer_AL_AudioPlayer ::kaleidoglyph::cConsumerKey::AL_AudioPlayer

#define Consumer_GenericGuiApplicationControls ::kaleidoglyph::cConsumerKey::GenericGuiApplicationControls
#define Consumer_AC_New ::kaleidoglyph::cConsumerKey::AC_New
#define Consumer_AC_Open ::kaleidoglyph::cConsumerKey::AC_Open
#define Consumer_AC_Close ::kaleidoglyph::cConsumerKey::AC_Close
#define Consumer_AC_Exit ::kaleidoglyph::cConsumerKey::AC_Exit
#define Consumer_AC_Maximize ::kaleidoglyph::cConsumerKey::AC_Maximize
#define Consumer_AC_Minimize ::kaleidoglyph::cConsumerKey::AC_Minimize
#define Consumer_AC_Save ::kaleidoglyph::cConsumerKey::AC_Save
#define Consumer_AC_Print ::kaleidoglyph::cConsumerKey::AC_Print
#define Consumer_AC_Properties ::kaleidoglyph::cConsumerKey::AC_Properties
#define Consumer_AC_Undo ::kaleidoglyph::cConsumerKey::AC_Undo
#define Consumer_AC_Copy ::kaleidoglyph::cConsumerKey::AC_Copy
#define Consumer_AC_Cut ::kaleidoglyph::cConsumerKey::AC_Cut
#define Consumer_AC_Paste ::kaleidoglyph::cConsumerKey::AC_Paste
#define Consumer_AC_SelectAll ::kaleidoglyph::cConsumerKey::AC_SelectAll
#define Consumer_AC_Find ::kaleidoglyph::cConsumerKey::AC_Find
#define Consumer_AC_FindAndReplace ::kaleidoglyph::cConsumerKey::AC_FindAndReplace
#define Consumer_AC_Search ::kaleidoglyph::cConsumerKey::AC_Search
#define Consumer_AC_GoTo ::kaleidoglyph::cConsumerKey::AC_GoTo
#define Consumer_AC_Home ::kaleidoglyph::cConsumerKey::AC_Home
#define Consumer_AC_Back ::kaleidoglyph::cConsumerKey::AC_Back
#define Consumer_AC_Forward ::kaleidoglyph::cConsumerKey::AC_Forward
#define Consumer_AC_Stop ::kaleidoglyph::cConsumerKey::AC_Stop
#define Consumer_AC_Refresh ::kaleidoglyph::cConsumerKey::AC_Refresh
#define Consumer_AC_PreviousLink ::kaleidoglyph::cConsumerKey::AC_PreviousLink
#define Consumer_AC_NextLink ::kaleidoglyph::cConsumerKey::AC_NextLink
#define Consumer_AC_Bookmarks ::kaleidoglyph::cConsumerKey::AC_Bookmarks
#define Consumer_AC_History ::kaleidoglyph::cConsumerKey::AC_History
#define Consumer_AC_Subscriptions ::kaleidoglyph::cConsumerKey::AC_Subscriptions
#define Consumer_AC_ZoomIn ::kaleidoglyph::cConsumerKey::AC_ZoomIn
#define Consumer_AC_ZoomOut ::kaleidoglyph::cConsumerKey::AC_ZoomOut
#define Consumer_AC_Zoom ::kaleidoglyph::cConsumerKey::AC_Zoom
#define Consumer_AC_FullSCreenView ::kaleidoglyph::cConsumerKey::AC_FullSCreenView
#define Consumer_AC_NormalView ::kaleidoglyph::cConsumerKey::AC_NormalView
#define Consumer_AC_ViewToggle ::kaleidoglyph::cConsumerKey::AC_ViewToggle
#define Consumer_AC_ScrollUp ::kaleidoglyph::cConsumerKey::AC_ScrollUp
#define Consumer_AC_ScrollDown ::kaleidoglyph::cConsumerKey::AC_ScrollDown
#define Consumer_AC_Scroll ::kaleidoglyph::cConsumerKey::AC_Scroll
#define Consumer_AC_PanLeft ::kaleidoglyph::cConsumerKey::AC_PanLeft
#define Consumer_AC_PanRight ::kaleidoglyph::cConsumerKey::AC_PanRight
#define Consumer_AC_Pan ::kaleidoglyph::cConsumerKey::AC_Pan
#define Consumer_AC_NewWindow ::kaleidoglyph::cConsumerKey::AC_NewWindow
#define Consumer_AC_TileHorizontally ::kaleidoglyph::cConsumerKey::AC_TileHorizontally
#define Consumer_AC_TileVertically ::kaleidoglyph::cConsumerKey::AC_TileVertically
#define Consumer_AC_Format ::kaleidoglyph::cConsumerKey::AC_Format
#define Consumer_AC_Edit ::kaleidoglyph::cConsumerKey::AC_Edit
#define Consumer_AC_Bold ::kaleidoglyph::cConsumerKey::AC_Bold
#define Consumer_AC_Italics ::kaleidoglyph::cConsumerKey::AC_Italics
#define Consumer_AC_Underline ::kaleidoglyph::cConsumerKey::AC_Underline
#define Consumer_AC_Strikethrough ::kaleidoglyph::cConsumerKey::AC_Strikethrough
#define Consumer_AC_Subscript ::kaleidoglyph::cConsumerKey::AC_Subscript
#define Consumer_AC_Superscript ::kaleidoglyph::cConsumerKey::AC_Superscript
#define Consumer_AC_AllCaps ::kaleidoglyph::cConsumerKey::AC_AllCaps
#define Consumer_AC_Rotate ::kaleidoglyph::cConsumerKey::AC_Rotate
#define Consumer_AC_Resize ::kaleidoglyph::cConsumerKey::AC_Resize
#define Consumer_AC_FlipHorizontal ::kaleidoglyph::cConsumerKey::AC_FlipHorizontal
#define Consumer_AC_FlipVertical ::kaleidoglyph::cConsumerKey::AC_FlipVertical
#define Consumer_AC_MirrorHorizontal ::kaleidoglyph::cConsumerKey::AC_MirrorHorizontal
#define Consumer_AC_MirrorVertical ::kaleidoglyph::cConsumerKey::AC_MirrorVertical
#define Consumer_AC_FontSelect ::kaleidoglyph::cConsumerKey::AC_FontSelect
#define Consumer_AC_FontColor ::kaleidoglyph::cConsumerKey::AC_FontColor
#define Consumer_AC_FontSize ::kaleidoglyph::cConsumerKey::AC_FontSize
#define Consumer_AC_JustifyLeft ::kaleidoglyph::cConsumerKey::AC_JustifyLeft
#define Consumer_AC_JustifyCenterH ::kaleidoglyph::cConsumerKey::AC_JustifyCenterH
#define Consumer_AC_JustifyRight ::kaleidoglyph::cConsumerKey::AC_JustifyRight
#define Consumer_AC_JustifyBlockH ::kaleidoglyph::cConsumerKey::AC_JustifyBlockH
#define Consumer_AC_JustifyTop ::kaleidoglyph::cConsumerKey::AC_JustifyTop
#define Consumer_AC_JustifyCenterV ::kaleidoglyph::cConsumerKey::AC_JustifyCenterV
#define Consumer_AC_JustifyBottom ::kaleidoglyph::cConsumerKey::AC_JustifyBottom
#define Consumer_AC_JustifyBlockV ::kaleidoglyph::cConsumerKey::AC_JustifyBlockV
#define Consumer_AC_IndentDecrease ::kaleidoglyph::cConsumerKey::AC_IndentDecrease
#define Consumer_AC_IndentIncrease ::kaleidoglyph::cConsumerKey::AC_IndentIncrease
#define Consumer_AC_NumberedList ::kaleidoglyph::cConsumerKey::AC_NumberedList
#define Consumer_AC_RestartNumbering ::kaleidoglyph::cConsumerKey::AC_RestartNumbering
#define Consumer_AC_BulletedList ::kaleidoglyph::cConsumerKey::AC_BulletedList
#define Consumer_AC_Promote ::kaleidoglyph::cConsumerKey::AC_Promote
#define Consumer_AC_Demote ::kaleidoglyph::cConsumerKey::AC_Demote
#define Consumer_AC_Yes ::kaleidoglyph::cConsumerKey::AC_Yes
#define Consumer_AC_No ::kaleidoglyph::cConsumerKey::AC_No
#define Consumer_AC_Cancel ::kaleidoglyph::cConsumerKey::AC_Cancel
#define Consumer_AC_Catalog ::kaleidoglyph::cConsumerKey::AC_Catalog
#define Consumer_AC_BuySlashCheckout ::kaleidoglyph::cConsumerKey::AC_BuySlashCheckout
#define Consumer_AC_AddToCart ::kaleidoglyph::cConsumerKey::AC_AddToCart
#define Consumer_AC_Expand ::kaleidoglyph::cConsumerKey::AC_Expand
#define Consumer_AC_ExpandAll ::kaleidoglyph::cConsumerKey::AC_ExpandAll
#define Consumer_AC_Collapse ::kaleidoglyph::cConsumerKey::AC_Collapse
#define Consumer_AC_CollapseAll ::kaleidoglyph::cConsumerKey::AC_CollapseAll
#define Consumer_AC_PrintPreview ::kaleidoglyph::cConsumerKey::AC_PrintPreview
#define Consumer_AC_PasteSpecial ::kaleidoglyph::cConsumerKey::AC_PasteSpecial
#define Consumer_AC_InsertMode ::kaleidoglyph::cConsumerKey::AC_InsertMode
#define Consumer_AC_Delete ::kaleidoglyph::cConsumerKey::AC_Delete
#define Consumer_AC_Lock ::kaleidoglyph::cConsumerKey::AC_Lock
#define Consumer_AC_Unlock ::kaleidoglyph::cConsumerKey::AC_Unlock
#define Consumer_AC_Protect ::kaleidoglyph::cConsumerKey::AC_Protect
#define Consumer_AC_Unprotect ::kaleidoglyph::cConsumerKey::AC_Unprotect
#define Consumer_AC_AttachComment ::kaleidoglyph::cConsumerKey::AC_AttachComment
#define Consumer_AC_DeleteComment ::kaleidoglyph::cConsumerKey::AC_DeleteComment
#define Consumer_AC_ViewComment ::kaleidoglyph::cConsumerKey::AC_ViewComment
#define Consumer_AC_SelectWord ::kaleidoglyph::cConsumerKey::AC_SelectWord
#define Consumer_AC_SelectSentence ::kaleidoglyph::cConsumerKey::AC_SelectSentence
#define Consumer_AC_SelectParagraph ::kaleidoglyph::cConsumerKey::AC_SelectParagraph
#define Consumer_AC_SelectColumn ::kaleidoglyph::cConsumerKey::AC_SelectColumn
#define Consumer_AC_SelectRow ::kaleidoglyph::cConsumerKey::AC_SelectRow
#define Consumer_AC_SelectTable ::kaleidoglyph::cConsumerKey::AC_SelectTable
#define Consumer_AC_SelectObject ::kaleidoglyph::cConsumerKey::AC_SelectObject
#define Consumer_AC_RedoSlashRepeat ::kaleidoglyph::cConsumerKey::AC_RedoSlashRepeat
#define Consumer_AC_Sort ::kaleidoglyph::cConsumerKey::AC_Sort
#define Consumer_AC_Sort_Ascending ::kaleidoglyph::cConsumerKey::AC_Sort_Ascending
#define Consumer_AC_Sort_Descending ::kaleidoglyph::cConsumerKey::AC_Sort_Descending
#define Consumer_AC_Filter ::kaleidoglyph::cConsumerKey::AC_Filter
#define Consumer_AC_SetClock ::kaleidoglyph::cConsumerKey::AC_SetClock
#define Consumer_AC_ViewClock ::kaleidoglyph::cConsumerKey::AC_ViewClock
#define Consumer_AC_SelectTimeZone ::kaleidoglyph::cConsumerKey::AC_SelectTimeZone
#define Consumer_AC_EditTimeZones ::kaleidoglyph::cConsumerKey::AC_EditTimeZones
#define Consumer_AC_SetAlarm ::kaleidoglyph::cConsumerKey::AC_SetAlarm
#define Consumer_AC_ClearAlarm ::kaleidoglyph::cConsumerKey::AC_ClearAlarm
#define Consumer_AC_SnoozeAlarm ::kaleidoglyph::cConsumerKey::AC_SnoozeAlarm
#define Consumer_AC_ResetAlarm ::kaleidoglyph::cConsumerKey::AC_ResetAlarm
#define Consumer_AC_Synchronize ::kaleidoglyph::cConsumerKey::AC_Synchronize
#define Consumer_AC_SendSlashReceive ::kaleidoglyph::cConsumerKey::AC_SendSlashReceive
#define Consumer_AC_SendTo ::kaleidoglyph::cConsumerKey::AC_SendTo
#define Consumer_AC_Reply ::kaleidoglyph::cConsumerKey::AC_Reply
#define Consumer_AC_ReplyAll ::kaleidoglyph::cConsumerKey::AC_ReplyAll
#define Consumer_AC_ForwardMsg ::kaleidoglyph::cConsumerKey::AC_ForwardMsg
#define Consumer_AC_Send ::kaleidoglyph::cConsumerKey::AC_Send
#define Consumer_AC_AttachFile ::kaleidoglyph::cConsumerKey::AC_AttachFile
#define Consumer_AC_Upload ::kaleidoglyph::cConsumerKey::AC_Upload
#define Consumer_AC_Download ::kaleidoglyph::cConsumerKey::AC_Download
#define Consumer_AC_SetBorders ::kaleidoglyph::cConsumerKey::AC_SetBorders
#define Consumer_AC_InsertRow ::kaleidoglyph::cConsumerKey::AC_InsertRow
#define Consumer_AC_InsertColumn ::kaleidoglyph::cConsumerKey::AC_InsertColumn
#define Consumer_AC_InsertFile ::kaleidoglyph::cConsumerKey::AC_InsertFile
#define Consumer_AC_InsertPicture ::kaleidoglyph::cConsumerKey::AC_InsertPicture
#define Consumer_AC_InsertObject ::kaleidoglyph::cConsumerKey::AC_InsertObject
#define Consumer_AC_InsertSymbol ::kaleidoglyph::cConsumerKey::AC_InsertSymbol
#define Consumer_AC_SaveandClose ::kaleidoglyph::cConsumerKey::AC_SaveandClose
#define Consumer_AC_Rename ::kaleidoglyph::cConsumerKey::AC_Rename
#define Consumer_AC_Merge ::kaleidoglyph::cConsumerKey::AC_Merge
#define Consumer_AC_Split ::kaleidoglyph::cConsumerKey::AC_Split
#define Consumer_AC_Distribute_Horizontally ::kaleidoglyph::cConsumerKey::AC_Distribute_Horizontally
#define Consumer_AC_Distribute_Vertically ::kaleidoglyph::cConsumerKey::AC_Distribute_Vertically
