#pragma once

// Keyboard HID mappings

// Reserved (no_event_indicated)
#define Key_NoEvent ::kaleidoscope::cKey::NoEvent
#define Key_ErrorRollover ::kaleidoscope::cKey::ErrorRollover
#define Key_PostFail ::kaleidoscope::cKey::PostFail
#define Key_ErrorUndefined ::kaleidoscope::cKey::ErrorUndefined
#define Key_A ::kaleidoscope::cKey::A
#define Key_B ::kaleidoscope::cKey::B
#define Key_C ::kaleidoscope::cKey::C
#define Key_D ::kaleidoscope::cKey::D
#define Key_E ::kaleidoscope::cKey::E
#define Key_F ::kaleidoscope::cKey::F
#define Key_G ::kaleidoscope::cKey::G
#define Key_H ::kaleidoscope::cKey::H
#define Key_I ::kaleidoscope::cKey::I
#define Key_J ::kaleidoscope::cKey::J
#define Key_K ::kaleidoscope::cKey::K
#define Key_L ::kaleidoscope::cKey::L
#define Key_M ::kaleidoscope::cKey::M
#define Key_N ::kaleidoscope::cKey::N
#define Key_O ::kaleidoscope::cKey::O
#define Key_P ::kaleidoscope::cKey::P
#define Key_Q ::kaleidoscope::cKey::Q
#define Key_R ::kaleidoscope::cKey::R
#define Key_S ::kaleidoscope::cKey::S
#define Key_T ::kaleidoscope::cKey::T
#define Key_U ::kaleidoscope::cKey::U
#define Key_V ::kaleidoscope::cKey::V
#define Key_W ::kaleidoscope::cKey::W
#define Key_X ::kaleidoscope::cKey::X
#define Key_Y ::kaleidoscope::cKey::Y
#define Key_Z ::kaleidoscope::cKey::Z
#define Key_1 ::kaleidoscope::cKey::_1
#define Key_2 ::kaleidoscope::cKey::_2
#define Key_3 ::kaleidoscope::cKey::_3
#define Key_4 ::kaleidoscope::cKey::_4
#define Key_5 ::kaleidoscope::cKey::_5
#define Key_6 ::kaleidoscope::cKey::_6
#define Key_7 ::kaleidoscope::cKey::_7
#define Key_8 ::kaleidoscope::cKey::_8
#define Key_9 ::kaleidoscope::cKey::_9
#define Key_0 ::kaleidoscope::cKey::_0
#define Key_Enter ::kaleidoscope::cKey::Enter
#define Key_Escape ::kaleidoscope::cKey::Escape
#define Key_Backspace ::kaleidoscope::cKey::Backspace
#define Key_Tab ::kaleidoscope::cKey::Tab
#define Key_Spacebar ::kaleidoscope::cKey::Spacebar
#define Key_Minus ::kaleidoscope::cKey::Minus
#define Key_Equals ::kaleidoscope::cKey::Equals
#define Key_LeftBracket ::kaleidoscope::cKey::LeftBracket
#define Key_RightBracket ::kaleidoscope::cKey::RightBracket
#define Key_Backslash ::kaleidoscope::cKey::Backslash
#define Key_NonUsPound ::kaleidoscope::cKey::NonUsPound
#define Key_Semicolon ::kaleidoscope::cKey::Semicolon
#define Key_Quote ::kaleidoscope::cKey::Quote
#define Key_Backtick ::kaleidoscope::cKey::Backtick
#define Key_Comma ::kaleidoscope::cKey::Comma
#define Key_Period ::kaleidoscope::cKey::Period
#define Key_Slash ::kaleidoscope::cKey::Slash
#define Key_CapsLock ::kaleidoscope::cKey::CapsLock
#define Key_F1 ::kaleidoscope::cKey::F1
#define Key_F2 ::kaleidoscope::cKey::F2
#define Key_F3 ::kaleidoscope::cKey::F3
#define Key_F4 ::kaleidoscope::cKey::F4
#define Key_F5 ::kaleidoscope::cKey::F5
#define Key_F6 ::kaleidoscope::cKey::F6
#define Key_F7 ::kaleidoscope::cKey::F7
#define Key_F8 ::kaleidoscope::cKey::F8
#define Key_F9 ::kaleidoscope::cKey::F9
#define Key_F10 ::kaleidoscope::cKey::F10
#define Key_F11 ::kaleidoscope::cKey::F11
#define Key_F12 ::kaleidoscope::cKey::F12
#define Key_PrintScreen ::kaleidoscope::cKey::PrintScreen
#define Key_ScrollLock ::kaleidoscope::cKey::ScrollLock
#define Key_Pause ::kaleidoscope::cKey::Pause
#define Key_Insert ::kaleidoscope::cKey::Insert
#define Key_Home ::kaleidoscope::cKey::Home
#define Key_PageUp ::kaleidoscope::cKey::PageUp
#define Key_Delete ::kaleidoscope::cKey::Delete
#define Key_End ::kaleidoscope::cKey::End
#define Key_PageDown ::kaleidoscope::cKey::PageDown
#define Key_RightArrow ::kaleidoscope::cKey::RightArrow
#define Key_LeftArrow ::kaleidoscope::cKey::LeftArrow
#define Key_DownArrow ::kaleidoscope::cKey::DownArrow
#define Key_UpArrow ::kaleidoscope::cKey::UpArrow
#define Key_KeypadNumLock ::kaleidoscope::cKey::KeypadNumLock
#define Key_KeypadDivide ::kaleidoscope::cKey::KeypadDivide
#define Key_KeypadMultiply ::kaleidoscope::cKey::KeypadMultiply
#define Key_KeypadSubtract ::kaleidoscope::cKey::KeypadSubtract
#define Key_KeypadAdd ::kaleidoscope::cKey::KeypadAdd
#define Key_KeypadEnter ::kaleidoscope::cKey::KeypadEnter
#define Key_Keypad1 ::kaleidoscope::cKey::Keypad1
#define Key_Keypad2 ::kaleidoscope::cKey::Keypad2
#define Key_Keypad3 ::kaleidoscope::cKey::Keypad3
#define Key_Keypad4 ::kaleidoscope::cKey::Keypad4
#define Key_Keypad5 ::kaleidoscope::cKey::Keypad5
#define Key_Keypad6 ::kaleidoscope::cKey::Keypad6
#define Key_Keypad7 ::kaleidoscope::cKey::Keypad7
#define Key_Keypad8 ::kaleidoscope::cKey::Keypad8
#define Key_Keypad9 ::kaleidoscope::cKey::Keypad9
#define Key_Keypad0 ::kaleidoscope::cKey::Keypad0
#define Key_KeypadDot ::kaleidoscope::cKey::KeypadDot
#define Key_NonUsBackslashAndPipe ::kaleidoscope::cKey::NonUsBackslashAndPipe
#define Key_PcApplication ::kaleidoscope::cKey::PcApplication
#define Key_Power ::kaleidoscope::cKey::Power
#define Key_KeypadEquals ::kaleidoscope::cKey::KeypadEquals
#define Key_F13 ::kaleidoscope::cKey::F13
#define Key_F14 ::kaleidoscope::cKey::F14
#define Key_F15 ::kaleidoscope::cKey::F15
#define Key_F16 ::kaleidoscope::cKey::F16
#define Key_F17 ::kaleidoscope::cKey::F17
#define Key_F18 ::kaleidoscope::cKey::F18
#define Key_F19 ::kaleidoscope::cKey::F19
#define Key_F20 ::kaleidoscope::cKey::F20
#define Key_F21 ::kaleidoscope::cKey::F21
#define Key_F22 ::kaleidoscope::cKey::F22
#define Key_F23 ::kaleidoscope::cKey::F23
#define Key_F24 ::kaleidoscope::cKey::F24
#define Key_Execute ::kaleidoscope::cKey::Execute
#define Key_Help ::kaleidoscope::cKey::Help
#define Key_Menu ::kaleidoscope::cKey::Menu
#define Key_Select ::kaleidoscope::cKey::Select
#define Key_Stop ::kaleidoscope::cKey::Stop
#define Key_Again ::kaleidoscope::cKey::Again
#define Key_Undo ::kaleidoscope::cKey::Undo
#define Key_Cut ::kaleidoscope::cKey::Cut
#define Key_Copy ::kaleidoscope::cKey::Copy
#define Key_Paste ::kaleidoscope::cKey::Paste
#define Key_Find ::kaleidoscope::cKey::Find
#define Key_Mute ::kaleidoscope::cKey::Mute
#define Key_VolumeUp ::kaleidoscope::cKey::VolumeUp
#define Key_VolumeDown ::kaleidoscope::cKey::VolumeDown
#define Key_LockingCapsLock ::kaleidoscope::cKey::LockingCapsLock
#define Key_LockingNumLock ::kaleidoscope::cKey::LockingNumLock
#define Key_LockingScrollLock ::kaleidoscope::cKey::LockingScrollLock
#define Key_KeypadComma ::kaleidoscope::cKey::KeypadComma
#define Key_KeypadEqualSign ::kaleidoscope::cKey::KeypadEqualSign
#define Key_International1 ::kaleidoscope::cKey::International1
#define Key_International2 ::kaleidoscope::cKey::International2
#define Key_International3 ::kaleidoscope::cKey::International3
#define Key_International4 ::kaleidoscope::cKey::International4
#define Key_International5 ::kaleidoscope::cKey::International5
#define Key_International6 ::kaleidoscope::cKey::International6
#define Key_International7 ::kaleidoscope::cKey::International7
#define Key_International8 ::kaleidoscope::cKey::International8
#define Key_International9 ::kaleidoscope::cKey::International9
#define Key_Lang1 ::kaleidoscope::cKey::Lang1
#define Key_Lang2 ::kaleidoscope::cKey::Lang2
#define Key_Lang3 ::kaleidoscope::cKey::Lang3
#define Key_Lang4 ::kaleidoscope::cKey::Lang4
#define Key_Lang5 ::kaleidoscope::cKey::Lang5
#define Key_Lang6 ::kaleidoscope::cKey::Lang6
#define Key_Lang7 ::kaleidoscope::cKey::Lang7
#define Key_Lang8 ::kaleidoscope::cKey::Lang8
#define Key_Lang9 ::kaleidoscope::cKey::Lang9
#define Key_AlternateErase ::kaleidoscope::cKey::AlternateErase
#define Key_Sysreq ::kaleidoscope::cKey::Sysreq
#define Key_Cancel ::kaleidoscope::cKey::Cancel
#define Key_Clear ::kaleidoscope::cKey::Clear
#define Key_Prior ::kaleidoscope::cKey::Prior
#define Key_Return ::kaleidoscope::cKey::Return
#define Key_Separator ::kaleidoscope::cKey::Separator
#define Key_Out ::kaleidoscope::cKey::Out
#define Key_Oper ::kaleidoscope::cKey::Oper
#define Key_ClearSlashAgain ::kaleidoscope::cKey::ClearSlashAgain
#define Key_CrselSlashProps ::kaleidoscope::cKey::CrselSlashProps
#define Key_Exsel ::kaleidoscope::cKey::Exsel
// Reserved	0xA5-AF
#define Key_Keypad00 ::kaleidoscope::cKey::Keypad00
#define Key_Keypad000 ::kaleidoscope::cKey::Keypad000
#define Key_ThousandsSeparator ::kaleidoscope::cKey::ThousandsSeparator
#define Key_DecimalSeparator ::kaleidoscope::cKey::DecimalSeparator
#define Key_CurrencyUnit ::kaleidoscope::cKey::CurrencyUnit
#define Key_CurrencySubunit ::kaleidoscope::cKey::CurrencySubunit
#define Key_KeypadLeftParen ::kaleidoscope::cKey::KeypadLeftParen
#define Key_KeypadRightParen ::kaleidoscope::cKey::KeypadRightParen
#define Key_KeypadLeftCurlyBrace ::kaleidoscope::cKey::KeypadLeftCurlyBrace
#define Key_KeypadRightCurlyBrace ::kaleidoscope::cKey::KeypadRightCurlyBrace
#define Key_KeypadTab ::kaleidoscope::cKey::KeypadTab
#define Key_KeypadBackspace ::kaleidoscope::cKey::KeypadBackspace
#define Key_KeypadA ::kaleidoscope::cKey::KeypadA
#define Key_KeypadB ::kaleidoscope::cKey::KeypadB
#define Key_KeypadC ::kaleidoscope::cKey::KeypadC
#define Key_KeypadD ::kaleidoscope::cKey::KeypadD
#define Key_KeypadE ::kaleidoscope::cKey::KeypadE
#define Key_KeypadF ::kaleidoscope::cKey::KeypadF
#define Key_KeypadXor ::kaleidoscope::cKey::KeypadXor
#define Key_KeypadCarat ::kaleidoscope::cKey::KeypadCarat
#define Key_KeypadPercent ::kaleidoscope::cKey::KeypadPercent
#define Key_KeypadLessThan ::kaleidoscope::cKey::KeypadLessThan
#define Key_KeypadGreaterThan ::kaleidoscope::cKey::KeypadGreaterThan
#define Key_KeypadAmpersand ::kaleidoscope::cKey::KeypadAmpersand
#define Key_KeypadDoubleampersand ::kaleidoscope::cKey::KeypadDoubleampersand
#define Key_KeypadPipe ::kaleidoscope::cKey::KeypadPipe
#define Key_KeypadDoublepipe ::kaleidoscope::cKey::KeypadDoublepipe
#define Key_KeypadColon ::kaleidoscope::cKey::KeypadColon
#define Key_KeypadPoundSign ::kaleidoscope::cKey::KeypadPoundSign
#define Key_KeypadSpace ::kaleidoscope::cKey::KeypadSpace
#define Key_KeypadAtSign ::kaleidoscope::cKey::KeypadAtSign
#define Key_KeypadExclamationPoint ::kaleidoscope::cKey::KeypadExclamationPoint
#define Key_KeypadMemoryStore ::kaleidoscope::cKey::KeypadMemoryStore
#define Key_KeypadMemoryRecall ::kaleidoscope::cKey::KeypadMemoryRecall
#define Key_KeypadMemoryClear ::kaleidoscope::cKey::KeypadMemoryClear
#define Key_KeypadMemoryAdd ::kaleidoscope::cKey::KeypadMemoryAdd
#define Key_KeypadMemorySubtract ::kaleidoscope::cKey::KeypadMemorySubtract
#define Key_KeypadMemoryMultiply ::kaleidoscope::cKey::KeypadMemoryMultiply
#define Key_KeypadMemoryDivide ::kaleidoscope::cKey::KeypadMemoryDivide
#define Key_KeypadPlusSlashMinus ::kaleidoscope::cKey::KeypadPlusSlashMinus
#define Key_KeypadClear ::kaleidoscope::cKey::KeypadClear
#define Key_KeypadClearEntry ::kaleidoscope::cKey::KeypadClearEntry
#define Key_KeypadBinary ::kaleidoscope::cKey::KeypadBinary
#define Key_KeypadOctal ::kaleidoscope::cKey::KeypadOctal
#define Key_KeypadDecimal ::kaleidoscope::cKey::KeypadDecimal
#define Key_KeypadHexadecimal ::kaleidoscope::cKey::KeypadHexadecimal

#define Key_LeftControl ::kaleidoscope::cKey::LeftControl
#define Key_LeftShift ::kaleidoscope::cKey::LeftShift
#define Key_LeftAlt ::kaleidoscope::cKey::LeftAlt
#define Key_LeftGui ::kaleidoscope::cKey::LeftGui
#define Key_RightControl ::kaleidoscope::cKey::RightControl
#define Key_RightShift ::kaleidoscope::cKey::RightShift
#define Key_RightAlt ::kaleidoscope::cKey::RightAlt
#define Key_RightGui ::kaleidoscope::cKey::RightGui


