#pragma once


#define Consumer_NumericKeyPad ::kaleidoscope::cConsumerKey::NumericKeyPad
#define Consumer_ProgrammableButtons ::kaleidoscope::cConsumerKey::ProgrammableButtons
#define Consumer_MicrophoneCa ::kaleidoscope::cConsumerKey::MicrophoneCa
#define Consumer_HeadphoneCa ::kaleidoscope::cConsumerKey::HeadphoneCa
#define Consumer_GraphicEqualizerCa ::kaleidoscope::cConsumerKey::GraphicEqualizerCa

#define Consumer_Plus10 ::kaleidoscope::cConsumerKey::Plus10
#define Consumer_Plus100 ::kaleidoscope::cConsumerKey::Plus100
#define Consumer_AMSlashPM ::kaleidoscope::cConsumerKey::AMSlashPM

#define Consumer_Power ::kaleidoscope::cConsumerKey::Power
#define Consumer_Reset ::kaleidoscope::cConsumerKey::Reset
#define Consumer_Sleep ::kaleidoscope::cConsumerKey::Sleep
#define Consumer_Sleep_After ::kaleidoscope::cConsumerKey::Sleep_After
#define Consumer_Sleep_Mode ::kaleidoscope::cConsumerKey::Sleep_Mode
#define Consumer_Illumination ::kaleidoscope::cConsumerKey::Illumination
#define Consumer_Function_Buttons ::kaleidoscope::cConsumerKey::Function_Buttons

#define Consumer_Menu ::kaleidoscope::cConsumerKey::Menu
#define Consumer_MenuPick ::kaleidoscope::cConsumerKey::MenuPick
#define Consumer_MenuUp ::kaleidoscope::cConsumerKey::MenuUp
#define Consumer_MenuDown ::kaleidoscope::cConsumerKey::MenuDown
#define Consumer_MenuLeft ::kaleidoscope::cConsumerKey::MenuLeft
#define Consumer_MenuRight ::kaleidoscope::cConsumerKey::MenuRight
#define Consumer_MenuEscape ::kaleidoscope::cConsumerKey::MenuEscape
#define Consumer_MenuValueIncrease ::kaleidoscope::cConsumerKey::MenuValueIncrease
#define Consumer_MenuValueDecrease ::kaleidoscope::cConsumerKey::MenuValueDecrease

#define Consumer_DataOnScreen ::kaleidoscope::cConsumerKey::DataOnScreen
#define Consumer_ClosedCaption ::kaleidoscope::cConsumerKey::ClosedCaption
#define Consumer_ClosedCaptionSelect ::kaleidoscope::cConsumerKey::ClosedCaptionSelect
#define Consumer_VCRSlashTV ::kaleidoscope::cConsumerKey::VCRSlashTV
#define Consumer_BroadcastMode ::kaleidoscope::cConsumerKey::BroadcastMode
#define Consumer_SNapshot ::kaleidoscope::cConsumerKey::SNapshot
#define Consumer_Still ::kaleidoscope::cConsumerKey::Still

#define Consumer_Selection ::kaleidoscope::cConsumerKey::Selection
#define Consumer_AssignSelection ::kaleidoscope::cConsumerKey::AssignSelection
#define Consumer_ModeStep ::kaleidoscope::cConsumerKey::ModeStep
#define Consumer_RecallLast ::kaleidoscope::cConsumerKey::RecallLast
#define Consumer_EnterChannel ::kaleidoscope::cConsumerKey::EnterChannel
#define Consumer_OrderMovie ::kaleidoscope::cConsumerKey::OrderMovie
#define Consumer_Channel ::kaleidoscope::cConsumerKey::Channel
#define Consumer_MediaSelection ::kaleidoscope::cConsumerKey::MediaSelection
#define Consumer_MediaSelectComputer ::kaleidoscope::cConsumerKey::MediaSelectComputer
#define Consumer_MediaSelectTV ::kaleidoscope::cConsumerKey::MediaSelectTV
#define Consumer_MediaSelectWww ::kaleidoscope::cConsumerKey::MediaSelectWww
#define Consumer_MediaSelectDvd ::kaleidoscope::cConsumerKey::MediaSelectDvd
#define Consumer_MediaSelectTelephone ::kaleidoscope::cConsumerKey::MediaSelectTelephone
#define Consumer_MediaSelectProgramGuide ::kaleidoscope::cConsumerKey::MediaSelectProgramGuide
#define Consumer_MediaSelectVideoPhone ::kaleidoscope::cConsumerKey::MediaSelectVideoPhone
#define Consumer_MediaSelectGames ::kaleidoscope::cConsumerKey::MediaSelectGames
#define Consumer_MediaSelectMessages ::kaleidoscope::cConsumerKey::MediaSelectMessages
#define Consumer_MediaSelectCd ::kaleidoscope::cConsumerKey::MediaSelectCd
#define Consumer_MediaSelectVcr ::kaleidoscope::cConsumerKey::MediaSelectVcr
#define Consumer_MediaSelectTuner ::kaleidoscope::cConsumerKey::MediaSelectTuner
#define Consumer_Quit ::kaleidoscope::cConsumerKey::Quit
#define Consumer_Help ::kaleidoscope::cConsumerKey::Help
#define Consumer_MediaSelectTape ::kaleidoscope::cConsumerKey::MediaSelectTape
#define Consumer_MediaSelectCable ::kaleidoscope::cConsumerKey::MediaSelectCable
#define Consumer_MediaSelectSatellite ::kaleidoscope::cConsumerKey::MediaSelectSatellite
#define Consumer_MediaSelectSecurity ::kaleidoscope::cConsumerKey::MediaSelectSecurity
#define Consumer_MediaSelectHome ::kaleidoscope::cConsumerKey::MediaSelectHome
#define Consumer_MediaSelectCall ::kaleidoscope::cConsumerKey::MediaSelectCall
#define Consumer_ChannelIncrement ::kaleidoscope::cConsumerKey::ChannelIncrement
#define Consumer_ChannelDecrement ::kaleidoscope::cConsumerKey::ChannelDecrement
#define Consumer_MediaSelectSap ::kaleidoscope::cConsumerKey::MediaSelectSap

#define Consumer_VcrPlus ::kaleidoscope::cConsumerKey::VcrPlus
#define Consumer_Once ::kaleidoscope::cConsumerKey::Once
#define Consumer_Daily ::kaleidoscope::cConsumerKey::Daily
#define Consumer_Weekly ::kaleidoscope::cConsumerKey::Weekly
#define Consumer_Monthly ::kaleidoscope::cConsumerKey::Monthly

#define Consumer_Play ::kaleidoscope::cConsumerKey::Play
#define Consumer_Pause ::kaleidoscope::cConsumerKey::Pause
#define Consumer_Record ::kaleidoscope::cConsumerKey::Record
#define Consumer_FastForward ::kaleidoscope::cConsumerKey::FastForward
#define Consumer_Rewind ::kaleidoscope::cConsumerKey::Rewind
#define Consumer_ScanNextTrack ::kaleidoscope::cConsumerKey::ScanNextTrack
#define Consumer_ScanPreviousTrack ::kaleidoscope::cConsumerKey::ScanPreviousTrack
#define Consumer_Stop ::kaleidoscope::cConsumerKey::Stop
#define Consumer_Eject ::kaleidoscope::cConsumerKey::Eject
#define Consumer_RandomPlay ::kaleidoscope::cConsumerKey::RandomPlay
#define Consumer_SelectDisc ::kaleidoscope::cConsumerKey::SelectDisc
#define Consumer_EnterDiscMc ::kaleidoscope::cConsumerKey::EnterDiscMc
#define Consumer_Repeat ::kaleidoscope::cConsumerKey::Repeat
#define Consumer_Tracking ::kaleidoscope::cConsumerKey::Tracking
#define Consumer_Track_Normal ::kaleidoscope::cConsumerKey::Track_Normal
#define Consumer_SlowTracking ::kaleidoscope::cConsumerKey::SlowTracking
#define Consumer_FrameForward ::kaleidoscope::cConsumerKey::FrameForward
#define Consumer_FrameBack ::kaleidoscope::cConsumerKey::FrameBack
#define Consumer_Mark ::kaleidoscope::cConsumerKey::Mark
#define Consumer_ClearMark ::kaleidoscope::cConsumerKey::ClearMark
#define Consumer_RepeatFromMark ::kaleidoscope::cConsumerKey::RepeatFromMark
#define Consumer_ReturnTo_Mark ::kaleidoscope::cConsumerKey::ReturnTo_Mark
#define Consumer_SearchMarkForward ::kaleidoscope::cConsumerKey::SearchMarkForward
#define Consumer_SearchMarkBackwards ::kaleidoscope::cConsumerKey::SearchMarkBackwards
#define Consumer_CounterReset ::kaleidoscope::cConsumerKey::CounterReset
#define Consumer_ShowCounter ::kaleidoscope::cConsumerKey::ShowCounter
#define Consumer_TrackingIncrement ::kaleidoscope::cConsumerKey::TrackingIncrement
#define Consumer_TrackingDecrement ::kaleidoscope::cConsumerKey::TrackingDecrement
#define Consumer_StopSlashEject ::kaleidoscope::cConsumerKey::StopSlashEject
#define Consumer_PlaySlashPause ::kaleidoscope::cConsumerKey::PlaySlashPause
#define Consumer_PlaySlashSkip ::kaleidoscope::cConsumerKey::PlaySlashSkip
#define Consumer_Volume ::kaleidoscope::cConsumerKey::Volume
#define Consumer_Balance ::kaleidoscope::cConsumerKey::Balance
#define Consumer_Mute ::kaleidoscope::cConsumerKey::Mute
#define Consumer_Bass ::kaleidoscope::cConsumerKey::Bass
#define Consumer_Treble ::kaleidoscope::cConsumerKey::Treble
#define Consumer_BassBoost ::kaleidoscope::cConsumerKey::BassBoost
#define Consumer_SurroundMode ::kaleidoscope::cConsumerKey::SurroundMode
#define Consumer_Loudness ::kaleidoscope::cConsumerKey::Loudness
#define Consumer_Mpx ::kaleidoscope::cConsumerKey::Mpx
#define Consumer_VolumeIncrement ::kaleidoscope::cConsumerKey::VolumeIncrement


#define Consumer_VolumeDecrement ::kaleidoscope::cConsumerKey::VolumeDecrement

#define Consumer_SpeedSelect ::kaleidoscope::cConsumerKey::SpeedSelect
#define Consumer_PlaybackSpeed ::kaleidoscope::cConsumerKey::PlaybackSpeed
#define Consumer_StandardPlay ::kaleidoscope::cConsumerKey::StandardPlay
#define Consumer_LongPlay ::kaleidoscope::cConsumerKey::LongPlay
#define Consumer_ExtendedPlay ::kaleidoscope::cConsumerKey::ExtendedPlay
#define Consumer_Slow ::kaleidoscope::cConsumerKey::Slow

#define Consumer_FanEnable ::kaleidoscope::cConsumerKey::FanEnable
#define Consumer_FanSpeed ::kaleidoscope::cConsumerKey::FanSpeed
#define Consumer_LightEnable ::kaleidoscope::cConsumerKey::LightEnable
#define Consumer_LightIlluminationLevel ::kaleidoscope::cConsumerKey::LightIlluminationLevel
#define Consumer_ClimateControlEnable ::kaleidoscope::cConsumerKey::ClimateControlEnable
#define Consumer_RoomTemperature ::kaleidoscope::cConsumerKey::RoomTemperature
#define Consumer_SecurityEnable ::kaleidoscope::cConsumerKey::SecurityEnable
#define Consumer_FireAlarm ::kaleidoscope::cConsumerKey::FireAlarm
#define Consumer_PoliceAlarm ::kaleidoscope::cConsumerKey::PoliceAlarm
#define Consumer_Proximity ::kaleidoscope::cConsumerKey::Proximity
#define Consumer_Motion ::kaleidoscope::cConsumerKey::Motion
#define Consumer_DuressAlarm ::kaleidoscope::cConsumerKey::DuressAlarm
#define Consumer_HoldupAlarm ::kaleidoscope::cConsumerKey::HoldupAlarm
#define Consumer_MedicalAlarm ::kaleidoscope::cConsumerKey::MedicalAlarm

#define Consumer_BalanceRight ::kaleidoscope::cConsumerKey::BalanceRight
#define Consumer_BalanceLeft ::kaleidoscope::cConsumerKey::BalanceLeft
#define Consumer_BassIncrement ::kaleidoscope::cConsumerKey::BassIncrement
#define Consumer_BassDecrement ::kaleidoscope::cConsumerKey::BassDecrement
#define Consumer_TrebleIncrement ::kaleidoscope::cConsumerKey::TrebleIncrement
#define Consumer_TrebleDecrement ::kaleidoscope::cConsumerKey::TrebleDecrement

#define Consumer_SpeakerSystem ::kaleidoscope::cConsumerKey::SpeakerSystem
#define Consumer_ChannelLeft ::kaleidoscope::cConsumerKey::ChannelLeft
#define Consumer_ChannelRight ::kaleidoscope::cConsumerKey::ChannelRight
#define Consumer_ChannelCenter ::kaleidoscope::cConsumerKey::ChannelCenter
#define Consumer_ChannelFront ::kaleidoscope::cConsumerKey::ChannelFront
#define Consumer_ChannelCenterFront ::kaleidoscope::cConsumerKey::ChannelCenterFront
#define Consumer_ChannelSide ::kaleidoscope::cConsumerKey::ChannelSide
#define Consumer_ChannelSurround ::kaleidoscope::cConsumerKey::ChannelSurround
#define Consumer_ChannelLowFrequencyEnhancement ::kaleidoscope::cConsumerKey::ChannelLowFrequencyEnhancement
#define Consumer_ChannelTop ::kaleidoscope::cConsumerKey::ChannelTop
#define Consumer_ChannelUnknown ::kaleidoscope::cConsumerKey::ChannelUnknown

#define Consumer_SubChannel ::kaleidoscope::cConsumerKey::SubChannel
#define Consumer_SubChannelIncrement ::kaleidoscope::cConsumerKey::SubChannelIncrement
#define Consumer_SubChannelDecrement ::kaleidoscope::cConsumerKey::SubChannelDecrement
#define Consumer_AlternateAudioIncrement ::kaleidoscope::cConsumerKey::AlternateAudioIncrement
#define Consumer_AlternateAudioDecrement ::kaleidoscope::cConsumerKey::AlternateAudioDecrement

#define Consumer_Application_Launch_Buttons ::kaleidoscope::cConsumerKey::Application_Launch_Buttons
#define Consumer_AL_Launch_Button_Configuration_Tool ::kaleidoscope::cConsumerKey::AL_Launch_Button_Configuration_Tool
#define Consumer_AL_Programmable_Button_Configuration ::kaleidoscope::cConsumerKey::AL_Programmable_Button_Configuration
#define Consumer_AL_Consumer_Control_Configuration ::kaleidoscope::cConsumerKey::AL_Consumer_Control_Configuration
#define Consumer_AL_Word_Processor ::kaleidoscope::cConsumerKey::AL_Word_Processor
#define Consumer_AL_Text_Editor ::kaleidoscope::cConsumerKey::AL_Text_Editor
#define Consumer_AL_Spreadsheet ::kaleidoscope::cConsumerKey::AL_Spreadsheet
#define Consumer_AL_Graphics_Editor ::kaleidoscope::cConsumerKey::AL_Graphics_Editor
#define Consumer_AL_Presentation_App ::kaleidoscope::cConsumerKey::AL_Presentation_App
#define Consumer_AL_Database_App ::kaleidoscope::cConsumerKey::AL_Database_App
#define Consumer_AL_Email_Reader ::kaleidoscope::cConsumerKey::AL_Email_Reader
#define Consumer_AL_Newsreader ::kaleidoscope::cConsumerKey::AL_Newsreader
#define Consumer_AL_Voicemail ::kaleidoscope::cConsumerKey::AL_Voicemail
#define Consumer_AL_Contacts_Slash_Address_Book ::kaleidoscope::cConsumerKey::AL_Contacts_Slash_Address_Book
#define Consumer_AL_Calendar_Slash_Schedule ::kaleidoscope::cConsumerKey::AL_Calendar_Slash_Schedule
#define Consumer_AL_Task_Slash_Project_Manager ::kaleidoscope::cConsumerKey::AL_Task_Slash_Project_Manager
#define Consumer_AL_Log_Slash_Journal_Slash_Timecard ::kaleidoscope::cConsumerKey::AL_Log_Slash_Journal_Slash_Timecard
#define Consumer_AL_Checkbook_Slash_Finance ::kaleidoscope::cConsumerKey::AL_Checkbook_Slash_Finance
#define Consumer_AL_Calculator ::kaleidoscope::cConsumerKey::AL_Calculator
#define Consumer_AL_AVCaptureSlashPlayback ::kaleidoscope::cConsumerKey::AL_AVCaptureSlashPlayback
#define Consumer_AL_Local_MachineBrowser ::kaleidoscope::cConsumerKey::AL_Local_MachineBrowser
#define Consumer_AL_Lan_SlashWanBrowser ::kaleidoscope::cConsumerKey::AL_Lan_SlashWanBrowser
#define Consumer_AL_InternetBrowser ::kaleidoscope::cConsumerKey::AL_InternetBrowser
#define Consumer_AL_RemoteNetworkingSlashIspConnect ::kaleidoscope::cConsumerKey::AL_RemoteNetworkingSlashIspConnect
#define Consumer_AL_NetworkConference ::kaleidoscope::cConsumerKey::AL_NetworkConference
#define Consumer_AL_NetworkChat ::kaleidoscope::cConsumerKey::AL_NetworkChat
#define Consumer_AL_TelephonySlashDialer ::kaleidoscope::cConsumerKey::AL_TelephonySlashDialer
#define Consumer_AL_Logon ::kaleidoscope::cConsumerKey::AL_Logon
#define Consumer_AL_Logoff ::kaleidoscope::cConsumerKey::AL_Logoff
#define Consumer_AL_LogonSlashLogoff ::kaleidoscope::cConsumerKey::AL_LogonSlashLogoff
#define Consumer_AL_TerminalLockSlashScreensaver ::kaleidoscope::cConsumerKey::AL_TerminalLockSlashScreensaver
#define Consumer_AL_ControlPanel ::kaleidoscope::cConsumerKey::AL_ControlPanel
#define Consumer_AL_CommandLineProcessorSlashRun ::kaleidoscope::cConsumerKey::AL_CommandLineProcessorSlashRun
#define Consumer_AL_ProcessSlashTask_Manager ::kaleidoscope::cConsumerKey::AL_ProcessSlashTask_Manager
#define Consumer_AL_SelectTaskSlashApplication ::kaleidoscope::cConsumerKey::AL_SelectTaskSlashApplication
#define Consumer_AL_NextTaskSlashApplication ::kaleidoscope::cConsumerKey::AL_NextTaskSlashApplication
#define Consumer_AL_PreviousTaskSlashApplication ::kaleidoscope::cConsumerKey::AL_PreviousTaskSlashApplication
#define Consumer_AL_PreemptiveHaltTaskSlashApplication ::kaleidoscope::cConsumerKey::AL_PreemptiveHaltTaskSlashApplication
#define Consumer_AL_IntegratedHelpCenter ::kaleidoscope::cConsumerKey::AL_IntegratedHelpCenter
#define Consumer_AL_Documents ::kaleidoscope::cConsumerKey::AL_Documents
#define Consumer_AL_Thesaurus ::kaleidoscope::cConsumerKey::AL_Thesaurus
#define Consumer_AL_Dictionary ::kaleidoscope::cConsumerKey::AL_Dictionary
#define Consumer_AL_Desktop ::kaleidoscope::cConsumerKey::AL_Desktop
#define Consumer_AL_SpellCheck ::kaleidoscope::cConsumerKey::AL_SpellCheck
#define Consumer_AL_GrammarCheck ::kaleidoscope::cConsumerKey::AL_GrammarCheck
#define Consumer_AL_WirelessStatus ::kaleidoscope::cConsumerKey::AL_WirelessStatus
#define Consumer_AL_KeyboardLayout ::kaleidoscope::cConsumerKey::AL_KeyboardLayout
#define Consumer_AL_VirusProtection ::kaleidoscope::cConsumerKey::AL_VirusProtection
#define Consumer_AL_Encryption ::kaleidoscope::cConsumerKey::AL_Encryption
#define Consumer_AL_ScreenSaver ::kaleidoscope::cConsumerKey::AL_ScreenSaver
#define Consumer_AL_Alarms ::kaleidoscope::cConsumerKey::AL_Alarms
#define Consumer_AL_Clock ::kaleidoscope::cConsumerKey::AL_Clock
#define Consumer_AL_FileBrowser ::kaleidoscope::cConsumerKey::AL_FileBrowser
#define Consumer_AL_PowerStatus ::kaleidoscope::cConsumerKey::AL_PowerStatus
#define Consumer_AL_ImageBrowser ::kaleidoscope::cConsumerKey::AL_ImageBrowser
#define Consumer_AL_AudioBrowser ::kaleidoscope::cConsumerKey::AL_AudioBrowser
#define Consumer_AL_MovieBrowser ::kaleidoscope::cConsumerKey::AL_MovieBrowser
#define Consumer_AL_DigitalRightsManager ::kaleidoscope::cConsumerKey::AL_DigitalRightsManager
#define Consumer_AL_DigitalWallet ::kaleidoscope::cConsumerKey::AL_DigitalWallet

#define Consumer_AL_InstantMessaging ::kaleidoscope::cConsumerKey::AL_InstantMessaging
#define Consumer_AL_OemFeaturesSlashTipsSlashTUTORIALBrowser ::kaleidoscope::cConsumerKey::AL_OemFeaturesSlashTipsSlashTUTORIALBrowser
#define Consumer_AL_OemHelp ::kaleidoscope::cConsumerKey::AL_OemHelp
#define Consumer_AL_OnlineCommunity ::kaleidoscope::cConsumerKey::AL_OnlineCommunity
#define Consumer_AL_Entertainment_Content_Browser ::kaleidoscope::cConsumerKey::AL_Entertainment_Content_Browser
#define Consumer_AL_OnlineShoppingBrowser ::kaleidoscope::cConsumerKey::AL_OnlineShoppingBrowser
#define Consumer_AL_SmartcardInformationSlashHelp ::kaleidoscope::cConsumerKey::AL_SmartcardInformationSlashHelp
#define Consumer_AL_MarketMonitorSlashFinanceBrowser ::kaleidoscope::cConsumerKey::AL_MarketMonitorSlashFinanceBrowser
#define Consumer_AL_CustomizedCorporateNewsBrowser ::kaleidoscope::cConsumerKey::AL_CustomizedCorporateNewsBrowser
#define Consumer_AL_OnlineActivityBrowser ::kaleidoscope::cConsumerKey::AL_OnlineActivityBrowser
#define Consumer_AL_ResearchSlashSearchBrowser ::kaleidoscope::cConsumerKey::AL_ResearchSlashSearchBrowser
#define Consumer_AL_AudioPlayer ::kaleidoscope::cConsumerKey::AL_AudioPlayer

#define Consumer_GenericGuiApplicationControls ::kaleidoscope::cConsumerKey::GenericGuiApplicationControls
#define Consumer_AC_New ::kaleidoscope::cConsumerKey::AC_New
#define Consumer_AC_Open ::kaleidoscope::cConsumerKey::AC_Open
#define Consumer_AC_Close ::kaleidoscope::cConsumerKey::AC_Close
#define Consumer_AC_Exit ::kaleidoscope::cConsumerKey::AC_Exit
#define Consumer_AC_Maximize ::kaleidoscope::cConsumerKey::AC_Maximize
#define Consumer_AC_Minimize ::kaleidoscope::cConsumerKey::AC_Minimize
#define Consumer_AC_Save ::kaleidoscope::cConsumerKey::AC_Save
#define Consumer_AC_Print ::kaleidoscope::cConsumerKey::AC_Print
#define Consumer_AC_Properties ::kaleidoscope::cConsumerKey::AC_Properties
#define Consumer_AC_Undo ::kaleidoscope::cConsumerKey::AC_Undo
#define Consumer_AC_Copy ::kaleidoscope::cConsumerKey::AC_Copy
#define Consumer_AC_Cut ::kaleidoscope::cConsumerKey::AC_Cut
#define Consumer_AC_Paste ::kaleidoscope::cConsumerKey::AC_Paste
#define Consumer_AC_SelectAll ::kaleidoscope::cConsumerKey::AC_SelectAll
#define Consumer_AC_Find ::kaleidoscope::cConsumerKey::AC_Find
#define Consumer_AC_FindAndReplace ::kaleidoscope::cConsumerKey::AC_FindAndReplace
#define Consumer_AC_Search ::kaleidoscope::cConsumerKey::AC_Search
#define Consumer_AC_GoTo ::kaleidoscope::cConsumerKey::AC_GoTo
#define Consumer_AC_Home ::kaleidoscope::cConsumerKey::AC_Home
#define Consumer_AC_Back ::kaleidoscope::cConsumerKey::AC_Back
#define Consumer_AC_Forward ::kaleidoscope::cConsumerKey::AC_Forward
#define Consumer_AC_Stop ::kaleidoscope::cConsumerKey::AC_Stop
#define Consumer_AC_Refresh ::kaleidoscope::cConsumerKey::AC_Refresh
#define Consumer_AC_PreviousLink ::kaleidoscope::cConsumerKey::AC_PreviousLink
#define Consumer_AC_NextLink ::kaleidoscope::cConsumerKey::AC_NextLink
#define Consumer_AC_Bookmarks ::kaleidoscope::cConsumerKey::AC_Bookmarks
#define Consumer_AC_History ::kaleidoscope::cConsumerKey::AC_History
#define Consumer_AC_Subscriptions ::kaleidoscope::cConsumerKey::AC_Subscriptions
#define Consumer_AC_ZoomIn ::kaleidoscope::cConsumerKey::AC_ZoomIn
#define Consumer_AC_ZoomOut ::kaleidoscope::cConsumerKey::AC_ZoomOut
#define Consumer_AC_Zoom ::kaleidoscope::cConsumerKey::AC_Zoom
#define Consumer_AC_FullSCreenView ::kaleidoscope::cConsumerKey::AC_FullSCreenView
#define Consumer_AC_NormalView ::kaleidoscope::cConsumerKey::AC_NormalView
#define Consumer_AC_ViewToggle ::kaleidoscope::cConsumerKey::AC_ViewToggle
#define Consumer_AC_ScrollUp ::kaleidoscope::cConsumerKey::AC_ScrollUp
#define Consumer_AC_ScrollDown ::kaleidoscope::cConsumerKey::AC_ScrollDown
#define Consumer_AC_Scroll ::kaleidoscope::cConsumerKey::AC_Scroll
#define Consumer_AC_PanLeft ::kaleidoscope::cConsumerKey::AC_PanLeft
#define Consumer_AC_PanRight ::kaleidoscope::cConsumerKey::AC_PanRight
#define Consumer_AC_Pan ::kaleidoscope::cConsumerKey::AC_Pan
#define Consumer_AC_NewWindow ::kaleidoscope::cConsumerKey::AC_NewWindow
#define Consumer_AC_TileHorizontally ::kaleidoscope::cConsumerKey::AC_TileHorizontally
#define Consumer_AC_TileVertically ::kaleidoscope::cConsumerKey::AC_TileVertically
#define Consumer_AC_Format ::kaleidoscope::cConsumerKey::AC_Format
#define Consumer_AC_Edit ::kaleidoscope::cConsumerKey::AC_Edit
#define Consumer_AC_Bold ::kaleidoscope::cConsumerKey::AC_Bold
#define Consumer_AC_Italics ::kaleidoscope::cConsumerKey::AC_Italics
#define Consumer_AC_Underline ::kaleidoscope::cConsumerKey::AC_Underline
#define Consumer_AC_Strikethrough ::kaleidoscope::cConsumerKey::AC_Strikethrough
#define Consumer_AC_Subscript ::kaleidoscope::cConsumerKey::AC_Subscript
#define Consumer_AC_Superscript ::kaleidoscope::cConsumerKey::AC_Superscript
#define Consumer_AC_AllCaps ::kaleidoscope::cConsumerKey::AC_AllCaps
#define Consumer_AC_Rotate ::kaleidoscope::cConsumerKey::AC_Rotate
#define Consumer_AC_Resize ::kaleidoscope::cConsumerKey::AC_Resize
#define Consumer_AC_FlipHorizontal ::kaleidoscope::cConsumerKey::AC_FlipHorizontal
#define Consumer_AC_FlipVertical ::kaleidoscope::cConsumerKey::AC_FlipVertical
#define Consumer_AC_MirrorHorizontal ::kaleidoscope::cConsumerKey::AC_MirrorHorizontal
#define Consumer_AC_MirrorVertical ::kaleidoscope::cConsumerKey::AC_MirrorVertical
#define Consumer_AC_FontSelect ::kaleidoscope::cConsumerKey::AC_FontSelect
#define Consumer_AC_FontColor ::kaleidoscope::cConsumerKey::AC_FontColor
#define Consumer_AC_FontSize ::kaleidoscope::cConsumerKey::AC_FontSize
#define Consumer_AC_JustifyLeft ::kaleidoscope::cConsumerKey::AC_JustifyLeft
#define Consumer_AC_JustifyCenterH ::kaleidoscope::cConsumerKey::AC_JustifyCenterH
#define Consumer_AC_JustifyRight ::kaleidoscope::cConsumerKey::AC_JustifyRight
#define Consumer_AC_JustifyBlockH ::kaleidoscope::cConsumerKey::AC_JustifyBlockH
#define Consumer_AC_JustifyTop ::kaleidoscope::cConsumerKey::AC_JustifyTop
#define Consumer_AC_JustifyCenterV ::kaleidoscope::cConsumerKey::AC_JustifyCenterV
#define Consumer_AC_JustifyBottom ::kaleidoscope::cConsumerKey::AC_JustifyBottom
#define Consumer_AC_JustifyBlockV ::kaleidoscope::cConsumerKey::AC_JustifyBlockV
#define Consumer_AC_IndentDecrease ::kaleidoscope::cConsumerKey::AC_IndentDecrease
#define Consumer_AC_IndentIncrease ::kaleidoscope::cConsumerKey::AC_IndentIncrease
#define Consumer_AC_NumberedList ::kaleidoscope::cConsumerKey::AC_NumberedList
#define Consumer_AC_RestartNumbering ::kaleidoscope::cConsumerKey::AC_RestartNumbering
#define Consumer_AC_BulletedList ::kaleidoscope::cConsumerKey::AC_BulletedList
#define Consumer_AC_Promote ::kaleidoscope::cConsumerKey::AC_Promote
#define Consumer_AC_Demote ::kaleidoscope::cConsumerKey::AC_Demote
#define Consumer_AC_Yes ::kaleidoscope::cConsumerKey::AC_Yes
#define Consumer_AC_No ::kaleidoscope::cConsumerKey::AC_No
#define Consumer_AC_Cancel ::kaleidoscope::cConsumerKey::AC_Cancel
#define Consumer_AC_Catalog ::kaleidoscope::cConsumerKey::AC_Catalog
#define Consumer_AC_BuySlashCheckout ::kaleidoscope::cConsumerKey::AC_BuySlashCheckout
#define Consumer_AC_AddToCart ::kaleidoscope::cConsumerKey::AC_AddToCart
#define Consumer_AC_Expand ::kaleidoscope::cConsumerKey::AC_Expand
#define Consumer_AC_ExpandAll ::kaleidoscope::cConsumerKey::AC_ExpandAll
#define Consumer_AC_Collapse ::kaleidoscope::cConsumerKey::AC_Collapse
#define Consumer_AC_CollapseAll ::kaleidoscope::cConsumerKey::AC_CollapseAll
#define Consumer_AC_PrintPreview ::kaleidoscope::cConsumerKey::AC_PrintPreview
#define Consumer_AC_PasteSpecial ::kaleidoscope::cConsumerKey::AC_PasteSpecial
#define Consumer_AC_InsertMode ::kaleidoscope::cConsumerKey::AC_InsertMode
#define Consumer_AC_Delete ::kaleidoscope::cConsumerKey::AC_Delete
#define Consumer_AC_Lock ::kaleidoscope::cConsumerKey::AC_Lock
#define Consumer_AC_Unlock ::kaleidoscope::cConsumerKey::AC_Unlock
#define Consumer_AC_Protect ::kaleidoscope::cConsumerKey::AC_Protect
#define Consumer_AC_Unprotect ::kaleidoscope::cConsumerKey::AC_Unprotect
#define Consumer_AC_AttachComment ::kaleidoscope::cConsumerKey::AC_AttachComment
#define Consumer_AC_DeleteComment ::kaleidoscope::cConsumerKey::AC_DeleteComment
#define Consumer_AC_ViewComment ::kaleidoscope::cConsumerKey::AC_ViewComment
#define Consumer_AC_SelectWord ::kaleidoscope::cConsumerKey::AC_SelectWord
#define Consumer_AC_SelectSentence ::kaleidoscope::cConsumerKey::AC_SelectSentence
#define Consumer_AC_SelectParagraph ::kaleidoscope::cConsumerKey::AC_SelectParagraph
#define Consumer_AC_SelectColumn ::kaleidoscope::cConsumerKey::AC_SelectColumn
#define Consumer_AC_SelectRow ::kaleidoscope::cConsumerKey::AC_SelectRow
#define Consumer_AC_SelectTable ::kaleidoscope::cConsumerKey::AC_SelectTable
#define Consumer_AC_SelectObject ::kaleidoscope::cConsumerKey::AC_SelectObject
#define Consumer_AC_RedoSlashRepeat ::kaleidoscope::cConsumerKey::AC_RedoSlashRepeat
#define Consumer_AC_Sort ::kaleidoscope::cConsumerKey::AC_Sort
#define Consumer_AC_Sort_Ascending ::kaleidoscope::cConsumerKey::AC_Sort_Ascending
#define Consumer_AC_Sort_Descending ::kaleidoscope::cConsumerKey::AC_Sort_Descending
#define Consumer_AC_Filter ::kaleidoscope::cConsumerKey::AC_Filter
#define Consumer_AC_SetClock ::kaleidoscope::cConsumerKey::AC_SetClock
#define Consumer_AC_ViewClock ::kaleidoscope::cConsumerKey::AC_ViewClock
#define Consumer_AC_SelectTimeZone ::kaleidoscope::cConsumerKey::AC_SelectTimeZone
#define Consumer_AC_EditTimeZones ::kaleidoscope::cConsumerKey::AC_EditTimeZones
#define Consumer_AC_SetAlarm ::kaleidoscope::cConsumerKey::AC_SetAlarm
#define Consumer_AC_ClearAlarm ::kaleidoscope::cConsumerKey::AC_ClearAlarm
#define Consumer_AC_SnoozeAlarm ::kaleidoscope::cConsumerKey::AC_SnoozeAlarm
#define Consumer_AC_ResetAlarm ::kaleidoscope::cConsumerKey::AC_ResetAlarm
#define Consumer_AC_Synchronize ::kaleidoscope::cConsumerKey::AC_Synchronize
#define Consumer_AC_SendSlashReceive ::kaleidoscope::cConsumerKey::AC_SendSlashReceive
#define Consumer_AC_SendTo ::kaleidoscope::cConsumerKey::AC_SendTo
#define Consumer_AC_Reply ::kaleidoscope::cConsumerKey::AC_Reply
#define Consumer_AC_ReplyAll ::kaleidoscope::cConsumerKey::AC_ReplyAll
#define Consumer_AC_ForwardMsg ::kaleidoscope::cConsumerKey::AC_ForwardMsg
#define Consumer_AC_Send ::kaleidoscope::cConsumerKey::AC_Send
#define Consumer_AC_AttachFile ::kaleidoscope::cConsumerKey::AC_AttachFile
#define Consumer_AC_Upload ::kaleidoscope::cConsumerKey::AC_Upload
#define Consumer_AC_Download ::kaleidoscope::cConsumerKey::AC_Download
#define Consumer_AC_SetBorders ::kaleidoscope::cConsumerKey::AC_SetBorders
#define Consumer_AC_InsertRow ::kaleidoscope::cConsumerKey::AC_InsertRow
#define Consumer_AC_InsertColumn ::kaleidoscope::cConsumerKey::AC_InsertColumn
#define Consumer_AC_InsertFile ::kaleidoscope::cConsumerKey::AC_InsertFile
#define Consumer_AC_InsertPicture ::kaleidoscope::cConsumerKey::AC_InsertPicture
#define Consumer_AC_InsertObject ::kaleidoscope::cConsumerKey::AC_InsertObject
#define Consumer_AC_InsertSymbol ::kaleidoscope::cConsumerKey::AC_InsertSymbol
#define Consumer_AC_SaveandClose ::kaleidoscope::cConsumerKey::AC_SaveandClose
#define Consumer_AC_Rename ::kaleidoscope::cConsumerKey::AC_Rename
#define Consumer_AC_Merge ::kaleidoscope::cConsumerKey::AC_Merge
#define Consumer_AC_Split ::kaleidoscope::cConsumerKey::AC_Split
#define Consumer_AC_Distribute_Horizontally ::kaleidoscope::cConsumerKey::AC_Distribute_Horizontally
#define Consumer_AC_Distribute_Vertically ::kaleidoscope::cConsumerKey::AC_Distribute_Vertically
