#pragma once


#define Consumer_NumericKeyPad ::kaleidoscope::cKey::Consumer::NumericKeyPad
#define Consumer_ProgrammableButtons ::kaleidoscope::cKey::Consumer::ProgrammableButtons
#define Consumer_MicrophoneCa ::kaleidoscope::cKey::Consumer::MicrophoneCa
#define Consumer_HeadphoneCa ::kaleidoscope::cKey::Consumer::HeadphoneCa
#define Consumer_GraphicEqualizerCa ::kaleidoscope::cKey::Consumer::GraphicEqualizerCa

#define Consumer_Plus10 ::kaleidoscope::cKey::Consumer::Plus10
#define Consumer_Plus100 ::kaleidoscope::cKey::Consumer::Plus100
#define Consumer_AMSlashPM ::kaleidoscope::cKey::Consumer::AMSlashPM

#define Consumer_Power ::kaleidoscope::cKey::Consumer::Power
#define Consumer_Reset ::kaleidoscope::cKey::Consumer::Reset
#define Consumer_Sleep ::kaleidoscope::cKey::Consumer::Sleep
#define Consumer_Sleep_After ::kaleidoscope::cKey::Consumer::Sleep_After
#define Consumer_Sleep_Mode ::kaleidoscope::cKey::Consumer::Sleep_Mode
#define Consumer_Illumination ::kaleidoscope::cKey::Consumer::Illumination
#define Consumer_Function_Buttons ::kaleidoscope::cKey::Consumer::Function_Buttons

#define Consumer_Menu ::kaleidoscope::cKey::Consumer::Menu
#define Consumer_MenuPick ::kaleidoscope::cKey::Consumer::MenuPick
#define Consumer_MenuUp ::kaleidoscope::cKey::Consumer::MenuUp
#define Consumer_MenuDown ::kaleidoscope::cKey::Consumer::MenuDown
#define Consumer_MenuLeft ::kaleidoscope::cKey::Consumer::MenuLeft
#define Consumer_MenuRight ::kaleidoscope::cKey::Consumer::MenuRight
#define Consumer_MenuEscape ::kaleidoscope::cKey::Consumer::MenuEscape
#define Consumer_MenuValueIncrease ::kaleidoscope::cKey::Consumer::MenuValueIncrease
#define Consumer_MenuValueDecrease ::kaleidoscope::cKey::Consumer::MenuValueDecrease

#define Consumer_DataOnScreen ::kaleidoscope::cKey::Consumer::DataOnScreen
#define Consumer_ClosedCaption ::kaleidoscope::cKey::Consumer::ClosedCaption
#define Consumer_ClosedCaptionSelect ::kaleidoscope::cKey::Consumer::ClosedCaptionSelect
#define Consumer_VCRSlashTV ::kaleidoscope::cKey::Consumer::VCRSlashTV
#define Consumer_BroadcastMode ::kaleidoscope::cKey::Consumer::BroadcastMode
#define Consumer_SNapshot ::kaleidoscope::cKey::Consumer::SNapshot
#define Consumer_Still ::kaleidoscope::cKey::Consumer::Still

#define Consumer_Selection ::kaleidoscope::cKey::Consumer::Selection
#define Consumer_AssignSelection ::kaleidoscope::cKey::Consumer::AssignSelection
#define Consumer_ModeStep ::kaleidoscope::cKey::Consumer::ModeStep
#define Consumer_RecallLast ::kaleidoscope::cKey::Consumer::RecallLast
#define Consumer_EnterChannel ::kaleidoscope::cKey::Consumer::EnterChannel
#define Consumer_OrderMovie ::kaleidoscope::cKey::Consumer::OrderMovie
#define Consumer_Channel ::kaleidoscope::cKey::Consumer::Channel
#define Consumer_MediaSelection ::kaleidoscope::cKey::Consumer::MediaSelection
#define Consumer_MediaSelectComputer ::kaleidoscope::cKey::Consumer::MediaSelectComputer
#define Consumer_MediaSelectTV ::kaleidoscope::cKey::Consumer::MediaSelectTV
#define Consumer_MediaSelectWww ::kaleidoscope::cKey::Consumer::MediaSelectWww
#define Consumer_MediaSelectDvd ::kaleidoscope::cKey::Consumer::MediaSelectDvd
#define Consumer_MediaSelectTelephone ::kaleidoscope::cKey::Consumer::MediaSelectTelephone
#define Consumer_MediaSelectProgramGuide ::kaleidoscope::cKey::Consumer::MediaSelectProgramGuide
#define Consumer_MediaSelectVideoPhone ::kaleidoscope::cKey::Consumer::MediaSelectVideoPhone
#define Consumer_MediaSelectGames ::kaleidoscope::cKey::Consumer::MediaSelectGames
#define Consumer_MediaSelectMessages ::kaleidoscope::cKey::Consumer::MediaSelectMessages
#define Consumer_MediaSelectCd ::kaleidoscope::cKey::Consumer::MediaSelectCd
#define Consumer_MediaSelectVcr ::kaleidoscope::cKey::Consumer::MediaSelectVcr
#define Consumer_MediaSelectTuner ::kaleidoscope::cKey::Consumer::MediaSelectTuner
#define Consumer_Quit ::kaleidoscope::cKey::Consumer::Quit
#define Consumer_Help ::kaleidoscope::cKey::Consumer::Help
#define Consumer_MediaSelectTape ::kaleidoscope::cKey::Consumer::MediaSelectTape
#define Consumer_MediaSelectCable ::kaleidoscope::cKey::Consumer::MediaSelectCable
#define Consumer_MediaSelectSatellite ::kaleidoscope::cKey::Consumer::MediaSelectSatellite
#define Consumer_MediaSelectSecurity ::kaleidoscope::cKey::Consumer::MediaSelectSecurity
#define Consumer_MediaSelectHome ::kaleidoscope::cKey::Consumer::MediaSelectHome
#define Consumer_MediaSelectCall ::kaleidoscope::cKey::Consumer::MediaSelectCall
#define Consumer_ChannelIncrement ::kaleidoscope::cKey::Consumer::ChannelIncrement
#define Consumer_ChannelDecrement ::kaleidoscope::cKey::Consumer::ChannelDecrement
#define Consumer_MediaSelectSap ::kaleidoscope::cKey::Consumer::MediaSelectSap

#define Consumer_VcrPlus ::kaleidoscope::cKey::Consumer::VcrPlus
#define Consumer_Once ::kaleidoscope::cKey::Consumer::Once
#define Consumer_Daily ::kaleidoscope::cKey::Consumer::Daily
#define Consumer_Weekly ::kaleidoscope::cKey::Consumer::Weekly
#define Consumer_Monthly ::kaleidoscope::cKey::Consumer::Monthly

#define Consumer_Play ::kaleidoscope::cKey::Consumer::Play
#define Consumer_Pause ::kaleidoscope::cKey::Consumer::Pause
#define Consumer_Record ::kaleidoscope::cKey::Consumer::Record
#define Consumer_FastForward ::kaleidoscope::cKey::Consumer::FastForward
#define Consumer_Rewind ::kaleidoscope::cKey::Consumer::Rewind
#define Consumer_ScanNextTrack ::kaleidoscope::cKey::Consumer::ScanNextTrack
#define Consumer_ScanPreviousTrack ::kaleidoscope::cKey::Consumer::ScanPreviousTrack
#define Consumer_Stop ::kaleidoscope::cKey::Consumer::Stop
#define Consumer_Eject ::kaleidoscope::cKey::Consumer::Eject
#define Consumer_RandomPlay ::kaleidoscope::cKey::Consumer::RandomPlay
#define Consumer_SelectDisc ::kaleidoscope::cKey::Consumer::SelectDisc
#define Consumer_EnterDiscMc ::kaleidoscope::cKey::Consumer::EnterDiscMc
#define Consumer_Repeat ::kaleidoscope::cKey::Consumer::Repeat
#define Consumer_Tracking ::kaleidoscope::cKey::Consumer::Tracking
#define Consumer_Track_Normal ::kaleidoscope::cKey::Consumer::Track_Normal
#define Consumer_SlowTracking ::kaleidoscope::cKey::Consumer::SlowTracking
#define Consumer_FrameForward ::kaleidoscope::cKey::Consumer::FrameForward
#define Consumer_FrameBack ::kaleidoscope::cKey::Consumer::FrameBack
#define Consumer_Mark ::kaleidoscope::cKey::Consumer::Mark
#define Consumer_ClearMark ::kaleidoscope::cKey::Consumer::ClearMark
#define Consumer_RepeatFromMark ::kaleidoscope::cKey::Consumer::RepeatFromMark
#define Consumer_ReturnTo_Mark ::kaleidoscope::cKey::Consumer::ReturnTo_Mark
#define Consumer_SearchMarkForward ::kaleidoscope::cKey::Consumer::SearchMarkForward
#define Consumer_SearchMarkBackwards ::kaleidoscope::cKey::Consumer::SearchMarkBackwards
#define Consumer_CounterReset ::kaleidoscope::cKey::Consumer::CounterReset
#define Consumer_ShowCounter ::kaleidoscope::cKey::Consumer::ShowCounter
#define Consumer_TrackingIncrement ::kaleidoscope::cKey::Consumer::TrackingIncrement
#define Consumer_TrackingDecrement ::kaleidoscope::cKey::Consumer::TrackingDecrement
#define Consumer_StopSlashEject ::kaleidoscope::cKey::Consumer::StopSlashEject
#define Consumer_PlaySlashPause ::kaleidoscope::cKey::Consumer::PlaySlashPause
#define Consumer_PlaySlashSkip ::kaleidoscope::cKey::Consumer::PlaySlashSkip
#define Consumer_Volume ::kaleidoscope::cKey::Consumer::Volume
#define Consumer_Balance ::kaleidoscope::cKey::Consumer::Balance
#define Consumer_Mute ::kaleidoscope::cKey::Consumer::Mute
#define Consumer_Bass ::kaleidoscope::cKey::Consumer::Bass
#define Consumer_Treble ::kaleidoscope::cKey::Consumer::Treble
#define Consumer_BassBoost ::kaleidoscope::cKey::Consumer::BassBoost
#define Consumer_SurroundMode ::kaleidoscope::cKey::Consumer::SurroundMode
#define Consumer_Loudness ::kaleidoscope::cKey::Consumer::Loudness
#define Consumer_Mpx ::kaleidoscope::cKey::Consumer::Mpx
#define Consumer_VolumeIncrement ::kaleidoscope::cKey::Consumer::VolumeIncrement


#define Consumer_VolumeDecrement ::kaleidoscope::cKey::Consumer::VolumeDecrement

#define Consumer_SpeedSelect ::kaleidoscope::cKey::Consumer::SpeedSelect
#define Consumer_PlaybackSpeed ::kaleidoscope::cKey::Consumer::PlaybackSpeed
#define Consumer_StandardPlay ::kaleidoscope::cKey::Consumer::StandardPlay
#define Consumer_LongPlay ::kaleidoscope::cKey::Consumer::LongPlay
#define Consumer_ExtendedPlay ::kaleidoscope::cKey::Consumer::ExtendedPlay
#define Consumer_Slow ::kaleidoscope::cKey::Consumer::Slow

#define Consumer_FanEnable ::kaleidoscope::cKey::Consumer::FanEnable
#define Consumer_FanSpeed ::kaleidoscope::cKey::Consumer::FanSpeed
#define Consumer_LightEnable ::kaleidoscope::cKey::Consumer::LightEnable
#define Consumer_LightIlluminationLevel ::kaleidoscope::cKey::Consumer::LightIlluminationLevel
#define Consumer_ClimateControlEnable ::kaleidoscope::cKey::Consumer::ClimateControlEnable
#define Consumer_RoomTemperature ::kaleidoscope::cKey::Consumer::RoomTemperature
#define Consumer_SecurityEnable ::kaleidoscope::cKey::Consumer::SecurityEnable
#define Consumer_FireAlarm ::kaleidoscope::cKey::Consumer::FireAlarm
#define Consumer_PoliceAlarm ::kaleidoscope::cKey::Consumer::PoliceAlarm
#define Consumer_Proximity ::kaleidoscope::cKey::Consumer::Proximity
#define Consumer_Motion ::kaleidoscope::cKey::Consumer::Motion
#define Consumer_DuressAlarm ::kaleidoscope::cKey::Consumer::DuressAlarm
#define Consumer_HoldupAlarm ::kaleidoscope::cKey::Consumer::HoldupAlarm
#define Consumer_MedicalAlarm ::kaleidoscope::cKey::Consumer::MedicalAlarm

#define Consumer_BalanceRight ::kaleidoscope::cKey::Consumer::BalanceRight
#define Consumer_BalanceLeft ::kaleidoscope::cKey::Consumer::BalanceLeft
#define Consumer_BassIncrement ::kaleidoscope::cKey::Consumer::BassIncrement
#define Consumer_BassDecrement ::kaleidoscope::cKey::Consumer::BassDecrement
#define Consumer_TrebleIncrement ::kaleidoscope::cKey::Consumer::TrebleIncrement
#define Consumer_TrebleDecrement ::kaleidoscope::cKey::Consumer::TrebleDecrement

#define Consumer_SpeakerSystem ::kaleidoscope::cKey::Consumer::SpeakerSystem
#define Consumer_ChannelLeft ::kaleidoscope::cKey::Consumer::ChannelLeft
#define Consumer_ChannelRight ::kaleidoscope::cKey::Consumer::ChannelRight
#define Consumer_ChannelCenter ::kaleidoscope::cKey::Consumer::ChannelCenter
#define Consumer_ChannelFront ::kaleidoscope::cKey::Consumer::ChannelFront
#define Consumer_ChannelCenterFront ::kaleidoscope::cKey::Consumer::ChannelCenterFront
#define Consumer_ChannelSide ::kaleidoscope::cKey::Consumer::ChannelSide
#define Consumer_ChannelSurround ::kaleidoscope::cKey::Consumer::ChannelSurround
#define Consumer_ChannelLowFrequencyEnhancement ::kaleidoscope::cKey::Consumer::ChannelLowFrequencyEnhancement
#define Consumer_ChannelTop ::kaleidoscope::cKey::Consumer::ChannelTop
#define Consumer_ChannelUnknown ::kaleidoscope::cKey::Consumer::ChannelUnknown

#define Consumer_SubChannel ::kaleidoscope::cKey::Consumer::SubChannel
#define Consumer_SubChannelIncrement ::kaleidoscope::cKey::Consumer::SubChannelIncrement
#define Consumer_SubChannelDecrement ::kaleidoscope::cKey::Consumer::SubChannelDecrement
#define Consumer_AlternateAudioIncrement ::kaleidoscope::cKey::Consumer::AlternateAudioIncrement
#define Consumer_AlternateAudioDecrement ::kaleidoscope::cKey::Consumer::AlternateAudioDecrement

#define Consumer_Application_Launch_Buttons ::kaleidoscope::cKey::Consumer::Application_Launch_Buttons
#define Consumer_AL_Launch_Button_Configuration_Tool ::kaleidoscope::cKey::Consumer::AL_Launch_Button_Configuration_Tool
#define Consumer_AL_Programmable_Button_Configuration ::kaleidoscope::cKey::Consumer::AL_Programmable_Button_Configuration
#define Consumer_AL_Consumer_Control_Configuration ::kaleidoscope::cKey::Consumer::AL_Consumer_Control_Configuration
#define Consumer_AL_Word_Processor ::kaleidoscope::cKey::Consumer::AL_Word_Processor
#define Consumer_AL_Text_Editor ::kaleidoscope::cKey::Consumer::AL_Text_Editor
#define Consumer_AL_Spreadsheet ::kaleidoscope::cKey::Consumer::AL_Spreadsheet
#define Consumer_AL_Graphics_Editor ::kaleidoscope::cKey::Consumer::AL_Graphics_Editor
#define Consumer_AL_Presentation_App ::kaleidoscope::cKey::Consumer::AL_Presentation_App
#define Consumer_AL_Database_App ::kaleidoscope::cKey::Consumer::AL_Database_App
#define Consumer_AL_Email_Reader ::kaleidoscope::cKey::Consumer::AL_Email_Reader
#define Consumer_AL_Newsreader ::kaleidoscope::cKey::Consumer::AL_Newsreader
#define Consumer_AL_Voicemail ::kaleidoscope::cKey::Consumer::AL_Voicemail
#define Consumer_AL_Contacts_Slash_Address_Book ::kaleidoscope::cKey::Consumer::AL_Contacts_Slash_Address_Book
#define Consumer_AL_Calendar_Slash_Schedule ::kaleidoscope::cKey::Consumer::AL_Calendar_Slash_Schedule
#define Consumer_AL_Task_Slash_Project_Manager ::kaleidoscope::cKey::Consumer::AL_Task_Slash_Project_Manager
#define Consumer_AL_Log_Slash_Journal_Slash_Timecard ::kaleidoscope::cKey::Consumer::AL_Log_Slash_Journal_Slash_Timecard
#define Consumer_AL_Checkbook_Slash_Finance ::kaleidoscope::cKey::Consumer::AL_Checkbook_Slash_Finance
#define Consumer_AL_Calculator ::kaleidoscope::cKey::Consumer::AL_Calculator
#define Consumer_AL_AVCaptureSlashPlayback ::kaleidoscope::cKey::Consumer::AL_AVCaptureSlashPlayback
#define Consumer_AL_Local_MachineBrowser ::kaleidoscope::cKey::Consumer::AL_Local_MachineBrowser
#define Consumer_AL_Lan_SlashWanBrowser ::kaleidoscope::cKey::Consumer::AL_Lan_SlashWanBrowser
#define Consumer_AL_InternetBrowser ::kaleidoscope::cKey::Consumer::AL_InternetBrowser
#define Consumer_AL_RemoteNetworkingSlashIspConnect ::kaleidoscope::cKey::Consumer::AL_RemoteNetworkingSlashIspConnect
#define Consumer_AL_NetworkConference ::kaleidoscope::cKey::Consumer::AL_NetworkConference
#define Consumer_AL_NetworkChat ::kaleidoscope::cKey::Consumer::AL_NetworkChat
#define Consumer_AL_TelephonySlashDialer ::kaleidoscope::cKey::Consumer::AL_TelephonySlashDialer
#define Consumer_AL_Logon ::kaleidoscope::cKey::Consumer::AL_Logon
#define Consumer_AL_Logoff ::kaleidoscope::cKey::Consumer::AL_Logoff
#define Consumer_AL_LogonSlashLogoff ::kaleidoscope::cKey::Consumer::AL_LogonSlashLogoff
#define Consumer_AL_TerminalLockSlashScreensaver ::kaleidoscope::cKey::Consumer::AL_TerminalLockSlashScreensaver
#define Consumer_AL_ControlPanel ::kaleidoscope::cKey::Consumer::AL_ControlPanel
#define Consumer_AL_CommandLineProcessorSlashRun ::kaleidoscope::cKey::Consumer::AL_CommandLineProcessorSlashRun
#define Consumer_AL_ProcessSlashTask_Manager ::kaleidoscope::cKey::Consumer::AL_ProcessSlashTask_Manager
#define Consumer_AL_SelectTaskSlashApplication ::kaleidoscope::cKey::Consumer::AL_SelectTaskSlashApplication
#define Consumer_AL_NextTaskSlashApplication ::kaleidoscope::cKey::Consumer::AL_NextTaskSlashApplication
#define Consumer_AL_PreviousTaskSlashApplication ::kaleidoscope::cKey::Consumer::AL_PreviousTaskSlashApplication
#define Consumer_AL_PreemptiveHaltTaskSlashApplication ::kaleidoscope::cKey::Consumer::AL_PreemptiveHaltTaskSlashApplication
#define Consumer_AL_IntegratedHelpCenter ::kaleidoscope::cKey::Consumer::AL_IntegratedHelpCenter
#define Consumer_AL_Documents ::kaleidoscope::cKey::Consumer::AL_Documents
#define Consumer_AL_Thesaurus ::kaleidoscope::cKey::Consumer::AL_Thesaurus
#define Consumer_AL_Dictionary ::kaleidoscope::cKey::Consumer::AL_Dictionary
#define Consumer_AL_Desktop ::kaleidoscope::cKey::Consumer::AL_Desktop
#define Consumer_AL_SpellCheck ::kaleidoscope::cKey::Consumer::AL_SpellCheck
#define Consumer_AL_GrammarCheck ::kaleidoscope::cKey::Consumer::AL_GrammarCheck
#define Consumer_AL_WirelessStatus ::kaleidoscope::cKey::Consumer::AL_WirelessStatus
#define Consumer_AL_KeyboardLayout ::kaleidoscope::cKey::Consumer::AL_KeyboardLayout
#define Consumer_AL_VirusProtection ::kaleidoscope::cKey::Consumer::AL_VirusProtection
#define Consumer_AL_Encryption ::kaleidoscope::cKey::Consumer::AL_Encryption
#define Consumer_AL_ScreenSaver ::kaleidoscope::cKey::Consumer::AL_ScreenSaver
#define Consumer_AL_Alarms ::kaleidoscope::cKey::Consumer::AL_Alarms
#define Consumer_AL_Clock ::kaleidoscope::cKey::Consumer::AL_Clock
#define Consumer_AL_FileBrowser ::kaleidoscope::cKey::Consumer::AL_FileBrowser
#define Consumer_AL_PowerStatus ::kaleidoscope::cKey::Consumer::AL_PowerStatus
#define Consumer_AL_ImageBrowser ::kaleidoscope::cKey::Consumer::AL_ImageBrowser
#define Consumer_AL_AudioBrowser ::kaleidoscope::cKey::Consumer::AL_AudioBrowser
#define Consumer_AL_MovieBrowser ::kaleidoscope::cKey::Consumer::AL_MovieBrowser
#define Consumer_AL_DigitalRightsManager ::kaleidoscope::cKey::Consumer::AL_DigitalRightsManager
#define Consumer_AL_DigitalWallet ::kaleidoscope::cKey::Consumer::AL_DigitalWallet

#define Consumer_AL_InstantMessaging ::kaleidoscope::cKey::Consumer::AL_InstantMessaging
#define Consumer_AL_OemFeaturesSlashTipsSlashTUTORIALBrowser ::kaleidoscope::cKey::Consumer::AL_OemFeaturesSlashTipsSlashTUTORIALBrowser
#define Consumer_AL_OemHelp ::kaleidoscope::cKey::Consumer::AL_OemHelp
#define Consumer_AL_OnlineCommunity ::kaleidoscope::cKey::Consumer::AL_OnlineCommunity
#define Consumer_AL_Entertainment_Content_Browser ::kaleidoscope::cKey::Consumer::AL_Entertainment_Content_Browser
#define Consumer_AL_OnlineShoppingBrowser ::kaleidoscope::cKey::Consumer::AL_OnlineShoppingBrowser
#define Consumer_AL_SmartcardInformationSlashHelp ::kaleidoscope::cKey::Consumer::AL_SmartcardInformationSlashHelp
#define Consumer_AL_MarketMonitorSlashFinanceBrowser ::kaleidoscope::cKey::Consumer::AL_MarketMonitorSlashFinanceBrowser
#define Consumer_AL_CustomizedCorporateNewsBrowser ::kaleidoscope::cKey::Consumer::AL_CustomizedCorporateNewsBrowser
#define Consumer_AL_OnlineActivityBrowser ::kaleidoscope::cKey::Consumer::AL_OnlineActivityBrowser
#define Consumer_AL_ResearchSlashSearchBrowser ::kaleidoscope::cKey::Consumer::AL_ResearchSlashSearchBrowser
#define Consumer_AL_AudioPlayer ::kaleidoscope::cKey::Consumer::AL_AudioPlayer

#define Consumer_GenericGuiApplicationControls ::kaleidoscope::cKey::Consumer::GenericGuiApplicationControls
#define Consumer_AC_New ::kaleidoscope::cKey::Consumer::AC_New
#define Consumer_AC_Open ::kaleidoscope::cKey::Consumer::AC_Open
#define Consumer_AC_Close ::kaleidoscope::cKey::Consumer::AC_Close
#define Consumer_AC_Exit ::kaleidoscope::cKey::Consumer::AC_Exit
#define Consumer_AC_Maximize ::kaleidoscope::cKey::Consumer::AC_Maximize
#define Consumer_AC_Minimize ::kaleidoscope::cKey::Consumer::AC_Minimize
#define Consumer_AC_Save ::kaleidoscope::cKey::Consumer::AC_Save
#define Consumer_AC_Print ::kaleidoscope::cKey::Consumer::AC_Print
#define Consumer_AC_Properties ::kaleidoscope::cKey::Consumer::AC_Properties
#define Consumer_AC_Undo ::kaleidoscope::cKey::Consumer::AC_Undo
#define Consumer_AC_Copy ::kaleidoscope::cKey::Consumer::AC_Copy
#define Consumer_AC_Cut ::kaleidoscope::cKey::Consumer::AC_Cut
#define Consumer_AC_Paste ::kaleidoscope::cKey::Consumer::AC_Paste
#define Consumer_AC_SelectAll ::kaleidoscope::cKey::Consumer::AC_SelectAll
#define Consumer_AC_Find ::kaleidoscope::cKey::Consumer::AC_Find
#define Consumer_AC_FindAndReplace ::kaleidoscope::cKey::Consumer::AC_FindAndReplace
#define Consumer_AC_Search ::kaleidoscope::cKey::Consumer::AC_Search
#define Consumer_AC_GoTo ::kaleidoscope::cKey::Consumer::AC_GoTo
#define Consumer_AC_Home ::kaleidoscope::cKey::Consumer::AC_Home
#define Consumer_AC_Back ::kaleidoscope::cKey::Consumer::AC_Back
#define Consumer_AC_Forward ::kaleidoscope::cKey::Consumer::AC_Forward
#define Consumer_AC_Stop ::kaleidoscope::cKey::Consumer::AC_Stop
#define Consumer_AC_Refresh ::kaleidoscope::cKey::Consumer::AC_Refresh
#define Consumer_AC_PreviousLink ::kaleidoscope::cKey::Consumer::AC_PreviousLink
#define Consumer_AC_NextLink ::kaleidoscope::cKey::Consumer::AC_NextLink
#define Consumer_AC_Bookmarks ::kaleidoscope::cKey::Consumer::AC_Bookmarks
#define Consumer_AC_History ::kaleidoscope::cKey::Consumer::AC_History
#define Consumer_AC_Subscriptions ::kaleidoscope::cKey::Consumer::AC_Subscriptions
#define Consumer_AC_ZoomIn ::kaleidoscope::cKey::Consumer::AC_ZoomIn
#define Consumer_AC_ZoomOut ::kaleidoscope::cKey::Consumer::AC_ZoomOut
#define Consumer_AC_Zoom ::kaleidoscope::cKey::Consumer::AC_Zoom
#define Consumer_AC_FullSCreenView ::kaleidoscope::cKey::Consumer::AC_FullSCreenView
#define Consumer_AC_NormalView ::kaleidoscope::cKey::Consumer::AC_NormalView
#define Consumer_AC_ViewToggle ::kaleidoscope::cKey::Consumer::AC_ViewToggle
#define Consumer_AC_ScrollUp ::kaleidoscope::cKey::Consumer::AC_ScrollUp
#define Consumer_AC_ScrollDown ::kaleidoscope::cKey::Consumer::AC_ScrollDown
#define Consumer_AC_Scroll ::kaleidoscope::cKey::Consumer::AC_Scroll
#define Consumer_AC_PanLeft ::kaleidoscope::cKey::Consumer::AC_PanLeft
#define Consumer_AC_PanRight ::kaleidoscope::cKey::Consumer::AC_PanRight
#define Consumer_AC_Pan ::kaleidoscope::cKey::Consumer::AC_Pan
#define Consumer_AC_NewWindow ::kaleidoscope::cKey::Consumer::AC_NewWindow
#define Consumer_AC_TileHorizontally ::kaleidoscope::cKey::Consumer::AC_TileHorizontally
#define Consumer_AC_TileVertically ::kaleidoscope::cKey::Consumer::AC_TileVertically
#define Consumer_AC_Format ::kaleidoscope::cKey::Consumer::AC_Format
#define Consumer_AC_Edit ::kaleidoscope::cKey::Consumer::AC_Edit
#define Consumer_AC_Bold ::kaleidoscope::cKey::Consumer::AC_Bold
#define Consumer_AC_Italics ::kaleidoscope::cKey::Consumer::AC_Italics
#define Consumer_AC_Underline ::kaleidoscope::cKey::Consumer::AC_Underline
#define Consumer_AC_Strikethrough ::kaleidoscope::cKey::Consumer::AC_Strikethrough
#define Consumer_AC_Subscript ::kaleidoscope::cKey::Consumer::AC_Subscript
#define Consumer_AC_Superscript ::kaleidoscope::cKey::Consumer::AC_Superscript
#define Consumer_AC_AllCaps ::kaleidoscope::cKey::Consumer::AC_AllCaps
#define Consumer_AC_Rotate ::kaleidoscope::cKey::Consumer::AC_Rotate
#define Consumer_AC_Resize ::kaleidoscope::cKey::Consumer::AC_Resize
#define Consumer_AC_FlipHorizontal ::kaleidoscope::cKey::Consumer::AC_FlipHorizontal
#define Consumer_AC_FlipVertical ::kaleidoscope::cKey::Consumer::AC_FlipVertical
#define Consumer_AC_MirrorHorizontal ::kaleidoscope::cKey::Consumer::AC_MirrorHorizontal
#define Consumer_AC_MirrorVertical ::kaleidoscope::cKey::Consumer::AC_MirrorVertical
#define Consumer_AC_FontSelect ::kaleidoscope::cKey::Consumer::AC_FontSelect
#define Consumer_AC_FontColor ::kaleidoscope::cKey::Consumer::AC_FontColor
#define Consumer_AC_FontSize ::kaleidoscope::cKey::Consumer::AC_FontSize
#define Consumer_AC_JustifyLeft ::kaleidoscope::cKey::Consumer::AC_JustifyLeft
#define Consumer_AC_JustifyCenterH ::kaleidoscope::cKey::Consumer::AC_JustifyCenterH
#define Consumer_AC_JustifyRight ::kaleidoscope::cKey::Consumer::AC_JustifyRight
#define Consumer_AC_JustifyBlockH ::kaleidoscope::cKey::Consumer::AC_JustifyBlockH
#define Consumer_AC_JustifyTop ::kaleidoscope::cKey::Consumer::AC_JustifyTop
#define Consumer_AC_JustifyCenterV ::kaleidoscope::cKey::Consumer::AC_JustifyCenterV
#define Consumer_AC_JustifyBottom ::kaleidoscope::cKey::Consumer::AC_JustifyBottom
#define Consumer_AC_JustifyBlockV ::kaleidoscope::cKey::Consumer::AC_JustifyBlockV
#define Consumer_AC_IndentDecrease ::kaleidoscope::cKey::Consumer::AC_IndentDecrease
#define Consumer_AC_IndentIncrease ::kaleidoscope::cKey::Consumer::AC_IndentIncrease
#define Consumer_AC_NumberedList ::kaleidoscope::cKey::Consumer::AC_NumberedList
#define Consumer_AC_RestartNumbering ::kaleidoscope::cKey::Consumer::AC_RestartNumbering
#define Consumer_AC_BulletedList ::kaleidoscope::cKey::Consumer::AC_BulletedList
#define Consumer_AC_Promote ::kaleidoscope::cKey::Consumer::AC_Promote
#define Consumer_AC_Demote ::kaleidoscope::cKey::Consumer::AC_Demote
#define Consumer_AC_Yes ::kaleidoscope::cKey::Consumer::AC_Yes
#define Consumer_AC_No ::kaleidoscope::cKey::Consumer::AC_No
#define Consumer_AC_Cancel ::kaleidoscope::cKey::Consumer::AC_Cancel
#define Consumer_AC_Catalog ::kaleidoscope::cKey::Consumer::AC_Catalog
#define Consumer_AC_BuySlashCheckout ::kaleidoscope::cKey::Consumer::AC_BuySlashCheckout
#define Consumer_AC_AddToCart ::kaleidoscope::cKey::Consumer::AC_AddToCart
#define Consumer_AC_Expand ::kaleidoscope::cKey::Consumer::AC_Expand
#define Consumer_AC_ExpandAll ::kaleidoscope::cKey::Consumer::AC_ExpandAll
#define Consumer_AC_Collapse ::kaleidoscope::cKey::Consumer::AC_Collapse
#define Consumer_AC_CollapseAll ::kaleidoscope::cKey::Consumer::AC_CollapseAll
#define Consumer_AC_PrintPreview ::kaleidoscope::cKey::Consumer::AC_PrintPreview
#define Consumer_AC_PasteSpecial ::kaleidoscope::cKey::Consumer::AC_PasteSpecial
#define Consumer_AC_InsertMode ::kaleidoscope::cKey::Consumer::AC_InsertMode
#define Consumer_AC_Delete ::kaleidoscope::cKey::Consumer::AC_Delete
#define Consumer_AC_Lock ::kaleidoscope::cKey::Consumer::AC_Lock
#define Consumer_AC_Unlock ::kaleidoscope::cKey::Consumer::AC_Unlock
#define Consumer_AC_Protect ::kaleidoscope::cKey::Consumer::AC_Protect
#define Consumer_AC_Unprotect ::kaleidoscope::cKey::Consumer::AC_Unprotect
#define Consumer_AC_AttachComment ::kaleidoscope::cKey::Consumer::AC_AttachComment
#define Consumer_AC_DeleteComment ::kaleidoscope::cKey::Consumer::AC_DeleteComment
#define Consumer_AC_ViewComment ::kaleidoscope::cKey::Consumer::AC_ViewComment
#define Consumer_AC_SelectWord ::kaleidoscope::cKey::Consumer::AC_SelectWord
#define Consumer_AC_SelectSentence ::kaleidoscope::cKey::Consumer::AC_SelectSentence
#define Consumer_AC_SelectParagraph ::kaleidoscope::cKey::Consumer::AC_SelectParagraph
#define Consumer_AC_SelectColumn ::kaleidoscope::cKey::Consumer::AC_SelectColumn
#define Consumer_AC_SelectRow ::kaleidoscope::cKey::Consumer::AC_SelectRow
#define Consumer_AC_SelectTable ::kaleidoscope::cKey::Consumer::AC_SelectTable
#define Consumer_AC_SelectObject ::kaleidoscope::cKey::Consumer::AC_SelectObject
#define Consumer_AC_RedoSlashRepeat ::kaleidoscope::cKey::Consumer::AC_RedoSlashRepeat
#define Consumer_AC_Sort ::kaleidoscope::cKey::Consumer::AC_Sort
#define Consumer_AC_Sort_Ascending ::kaleidoscope::cKey::Consumer::AC_Sort_Ascending
#define Consumer_AC_Sort_Descending ::kaleidoscope::cKey::Consumer::AC_Sort_Descending
#define Consumer_AC_Filter ::kaleidoscope::cKey::Consumer::AC_Filter
#define Consumer_AC_SetClock ::kaleidoscope::cKey::Consumer::AC_SetClock
#define Consumer_AC_ViewClock ::kaleidoscope::cKey::Consumer::AC_ViewClock
#define Consumer_AC_SelectTimeZone ::kaleidoscope::cKey::Consumer::AC_SelectTimeZone
#define Consumer_AC_EditTimeZones ::kaleidoscope::cKey::Consumer::AC_EditTimeZones
#define Consumer_AC_SetAlarm ::kaleidoscope::cKey::Consumer::AC_SetAlarm
#define Consumer_AC_ClearAlarm ::kaleidoscope::cKey::Consumer::AC_ClearAlarm
#define Consumer_AC_SnoozeAlarm ::kaleidoscope::cKey::Consumer::AC_SnoozeAlarm
#define Consumer_AC_ResetAlarm ::kaleidoscope::cKey::Consumer::AC_ResetAlarm
#define Consumer_AC_Synchronize ::kaleidoscope::cKey::Consumer::AC_Synchronize
#define Consumer_AC_SendSlashReceive ::kaleidoscope::cKey::Consumer::AC_SendSlashReceive
#define Consumer_AC_SendTo ::kaleidoscope::cKey::Consumer::AC_SendTo
#define Consumer_AC_Reply ::kaleidoscope::cKey::Consumer::AC_Reply
#define Consumer_AC_ReplyAll ::kaleidoscope::cKey::Consumer::AC_ReplyAll
#define Consumer_AC_ForwardMsg ::kaleidoscope::cKey::Consumer::AC_ForwardMsg
#define Consumer_AC_Send ::kaleidoscope::cKey::Consumer::AC_Send
#define Consumer_AC_AttachFile ::kaleidoscope::cKey::Consumer::AC_AttachFile
#define Consumer_AC_Upload ::kaleidoscope::cKey::Consumer::AC_Upload
#define Consumer_AC_Download ::kaleidoscope::cKey::Consumer::AC_Download
#define Consumer_AC_SetBorders ::kaleidoscope::cKey::Consumer::AC_SetBorders
#define Consumer_AC_InsertRow ::kaleidoscope::cKey::Consumer::AC_InsertRow
#define Consumer_AC_InsertColumn ::kaleidoscope::cKey::Consumer::AC_InsertColumn
#define Consumer_AC_InsertFile ::kaleidoscope::cKey::Consumer::AC_InsertFile
#define Consumer_AC_InsertPicture ::kaleidoscope::cKey::Consumer::AC_InsertPicture
#define Consumer_AC_InsertObject ::kaleidoscope::cKey::Consumer::AC_InsertObject
#define Consumer_AC_InsertSymbol ::kaleidoscope::cKey::Consumer::AC_InsertSymbol
#define Consumer_AC_SaveandClose ::kaleidoscope::cKey::Consumer::AC_SaveandClose
#define Consumer_AC_Rename ::kaleidoscope::cKey::Consumer::AC_Rename
#define Consumer_AC_Merge ::kaleidoscope::cKey::Consumer::AC_Merge
#define Consumer_AC_Split ::kaleidoscope::cKey::Consumer::AC_Split
#define Consumer_AC_Distribute_Horizontally ::kaleidoscope::cKey::Consumer::AC_Distribute_Horizontally
#define Consumer_AC_Distribute_Vertically ::kaleidoscope::cKey::Consumer::AC_Distribute_Vertically
