#pragma once

// Keyboard HID mappings

// Reserved (no_event_indicated)
#define Key_NoEvent ::kaleidoscope::cKeyboardKey::NoEvent
#define Key_ErrorRollover ::kaleidoscope::cKeyboardKey::ErrorRollover
#define Key_PostFail ::kaleidoscope::cKeyboardKey::PostFail
#define Key_ErrorUndefined ::kaleidoscope::cKeyboardKey::ErrorUndefined
#define Key_A ::kaleidoscope::cKeyboardKey::A
#define Key_B ::kaleidoscope::cKeyboardKey::B
#define Key_C ::kaleidoscope::cKeyboardKey::C
#define Key_D ::kaleidoscope::cKeyboardKey::D
#define Key_E ::kaleidoscope::cKeyboardKey::E
#define Key_F ::kaleidoscope::cKeyboardKey::F
#define Key_G ::kaleidoscope::cKeyboardKey::G
#define Key_H ::kaleidoscope::cKeyboardKey::H
#define Key_I ::kaleidoscope::cKeyboardKey::I
#define Key_J ::kaleidoscope::cKeyboardKey::J
#define Key_K ::kaleidoscope::cKeyboardKey::K
#define Key_L ::kaleidoscope::cKeyboardKey::L
#define Key_M ::kaleidoscope::cKeyboardKey::M
#define Key_N ::kaleidoscope::cKeyboardKey::N
#define Key_O ::kaleidoscope::cKeyboardKey::O
#define Key_P ::kaleidoscope::cKeyboardKey::P
#define Key_Q ::kaleidoscope::cKeyboardKey::Q
#define Key_R ::kaleidoscope::cKeyboardKey::R
#define Key_S ::kaleidoscope::cKeyboardKey::S
#define Key_T ::kaleidoscope::cKeyboardKey::T
#define Key_U ::kaleidoscope::cKeyboardKey::U
#define Key_V ::kaleidoscope::cKeyboardKey::V
#define Key_W ::kaleidoscope::cKeyboardKey::W
#define Key_X ::kaleidoscope::cKeyboardKey::X
#define Key_Y ::kaleidoscope::cKeyboardKey::Y
#define Key_Z ::kaleidoscope::cKeyboardKey::Z
#define Key_1 ::kaleidoscope::cKeyboardKey::_1
#define Key_2 ::kaleidoscope::cKeyboardKey::_2
#define Key_3 ::kaleidoscope::cKeyboardKey::_3
#define Key_4 ::kaleidoscope::cKeyboardKey::_4
#define Key_5 ::kaleidoscope::cKeyboardKey::_5
#define Key_6 ::kaleidoscope::cKeyboardKey::_6
#define Key_7 ::kaleidoscope::cKeyboardKey::_7
#define Key_8 ::kaleidoscope::cKeyboardKey::_8
#define Key_9 ::kaleidoscope::cKeyboardKey::_9
#define Key_0 ::kaleidoscope::cKeyboardKey::_0
#define Key_Enter ::kaleidoscope::cKeyboardKey::Enter
#define Key_Escape ::kaleidoscope::cKeyboardKey::Escape
#define Key_Backspace ::kaleidoscope::cKeyboardKey::Backspace
#define Key_Tab ::kaleidoscope::cKeyboardKey::Tab
#define Key_Spacebar ::kaleidoscope::cKeyboardKey::Spacebar
#define Key_Minus ::kaleidoscope::cKeyboardKey::Minus
#define Key_Equals ::kaleidoscope::cKeyboardKey::Equals
#define Key_LeftBracket ::kaleidoscope::cKeyboardKey::LeftBracket
#define Key_RightBracket ::kaleidoscope::cKeyboardKey::RightBracket
#define Key_Backslash ::kaleidoscope::cKeyboardKey::Backslash
#define Key_NonUsPound ::kaleidoscope::cKeyboardKey::NonUsPound
#define Key_Semicolon ::kaleidoscope::cKeyboardKey::Semicolon
#define Key_Quote ::kaleidoscope::cKeyboardKey::Quote
#define Key_Backtick ::kaleidoscope::cKeyboardKey::Backtick
#define Key_Comma ::kaleidoscope::cKeyboardKey::Comma
#define Key_Period ::kaleidoscope::cKeyboardKey::Period
#define Key_Slash ::kaleidoscope::cKeyboardKey::Slash
#define Key_CapsLock ::kaleidoscope::cKeyboardKey::CapsLock
#define Key_F1 ::kaleidoscope::cKeyboardKey::F1
#define Key_F2 ::kaleidoscope::cKeyboardKey::F2
#define Key_F3 ::kaleidoscope::cKeyboardKey::F3
#define Key_F4 ::kaleidoscope::cKeyboardKey::F4
#define Key_F5 ::kaleidoscope::cKeyboardKey::F5
#define Key_F6 ::kaleidoscope::cKeyboardKey::F6
#define Key_F7 ::kaleidoscope::cKeyboardKey::F7
#define Key_F8 ::kaleidoscope::cKeyboardKey::F8
#define Key_F9 ::kaleidoscope::cKeyboardKey::F9
#define Key_F10 ::kaleidoscope::cKeyboardKey::F10
#define Key_F11 ::kaleidoscope::cKeyboardKey::F11
#define Key_F12 ::kaleidoscope::cKeyboardKey::F12
#define Key_PrintScreen ::kaleidoscope::cKeyboardKey::PrintScreen
#define Key_ScrollLock ::kaleidoscope::cKeyboardKey::ScrollLock
#define Key_Pause ::kaleidoscope::cKeyboardKey::Pause
#define Key_Insert ::kaleidoscope::cKeyboardKey::Insert
#define Key_Home ::kaleidoscope::cKeyboardKey::Home
#define Key_PageUp ::kaleidoscope::cKeyboardKey::PageUp
#define Key_Delete ::kaleidoscope::cKeyboardKey::Delete
#define Key_End ::kaleidoscope::cKeyboardKey::End
#define Key_PageDown ::kaleidoscope::cKeyboardKey::PageDown
#define Key_RightArrow ::kaleidoscope::cKeyboardKey::RightArrow
#define Key_LeftArrow ::kaleidoscope::cKeyboardKey::LeftArrow
#define Key_DownArrow ::kaleidoscope::cKeyboardKey::DownArrow
#define Key_UpArrow ::kaleidoscope::cKeyboardKey::UpArrow
#define Key_KeypadNumLock ::kaleidoscope::cKeyboardKey::KeypadNumLock
#define Key_KeypadDivide ::kaleidoscope::cKeyboardKey::KeypadDivide
#define Key_KeypadMultiply ::kaleidoscope::cKeyboardKey::KeypadMultiply
#define Key_KeypadSubtract ::kaleidoscope::cKeyboardKey::KeypadSubtract
#define Key_KeypadAdd ::kaleidoscope::cKeyboardKey::KeypadAdd
#define Key_KeypadEnter ::kaleidoscope::cKeyboardKey::KeypadEnter
#define Key_Keypad1 ::kaleidoscope::cKeyboardKey::Keypad1
#define Key_Keypad2 ::kaleidoscope::cKeyboardKey::Keypad2
#define Key_Keypad3 ::kaleidoscope::cKeyboardKey::Keypad3
#define Key_Keypad4 ::kaleidoscope::cKeyboardKey::Keypad4
#define Key_Keypad5 ::kaleidoscope::cKeyboardKey::Keypad5
#define Key_Keypad6 ::kaleidoscope::cKeyboardKey::Keypad6
#define Key_Keypad7 ::kaleidoscope::cKeyboardKey::Keypad7
#define Key_Keypad8 ::kaleidoscope::cKeyboardKey::Keypad8
#define Key_Keypad9 ::kaleidoscope::cKeyboardKey::Keypad9
#define Key_Keypad0 ::kaleidoscope::cKeyboardKey::Keypad0
#define Key_KeypadDot ::kaleidoscope::cKeyboardKey::KeypadDot
#define Key_NonUsBackslashAndPipe ::kaleidoscope::cKeyboardKey::NonUsBackslashAndPipe
#define Key_PcApplication ::kaleidoscope::cKeyboardKey::PcApplication
#define Key_Power ::kaleidoscope::cKeyboardKey::Power
#define Key_KeypadEquals ::kaleidoscope::cKeyboardKey::KeypadEquals
#define Key_F13 ::kaleidoscope::cKeyboardKey::F13
#define Key_F14 ::kaleidoscope::cKeyboardKey::F14
#define Key_F15 ::kaleidoscope::cKeyboardKey::F15
#define Key_F16 ::kaleidoscope::cKeyboardKey::F16
#define Key_F17 ::kaleidoscope::cKeyboardKey::F17
#define Key_F18 ::kaleidoscope::cKeyboardKey::F18
#define Key_F19 ::kaleidoscope::cKeyboardKey::F19
#define Key_F20 ::kaleidoscope::cKeyboardKey::F20
#define Key_F21 ::kaleidoscope::cKeyboardKey::F21
#define Key_F22 ::kaleidoscope::cKeyboardKey::F22
#define Key_F23 ::kaleidoscope::cKeyboardKey::F23
#define Key_F24 ::kaleidoscope::cKeyboardKey::F24
#define Key_Execute ::kaleidoscope::cKeyboardKey::Execute
#define Key_Help ::kaleidoscope::cKeyboardKey::Help
#define Key_Menu ::kaleidoscope::cKeyboardKey::Menu
#define Key_Select ::kaleidoscope::cKeyboardKey::Select
#define Key_Stop ::kaleidoscope::cKeyboardKey::Stop
#define Key_Again ::kaleidoscope::cKeyboardKey::Again
#define Key_Undo ::kaleidoscope::cKeyboardKey::Undo
#define Key_Cut ::kaleidoscope::cKeyboardKey::Cut
#define Key_Copy ::kaleidoscope::cKeyboardKey::Copy
#define Key_Paste ::kaleidoscope::cKeyboardKey::Paste
#define Key_Find ::kaleidoscope::cKeyboardKey::Find
#define Key_Mute ::kaleidoscope::cKeyboardKey::Mute
#define Key_VolumeUp ::kaleidoscope::cKeyboardKey::VolumeUp
#define Key_VolumeDown ::kaleidoscope::cKeyboardKey::VolumeDown
#define Key_LockingCapsLock ::kaleidoscope::cKeyboardKey::LockingCapsLock
#define Key_LockingNumLock ::kaleidoscope::cKeyboardKey::LockingNumLock
#define Key_LockingScrollLock ::kaleidoscope::cKeyboardKey::LockingScrollLock
#define Key_KeypadComma ::kaleidoscope::cKeyboardKey::KeypadComma
#define Key_KeypadEqualSign ::kaleidoscope::cKeyboardKey::KeypadEqualSign
#define Key_International1 ::kaleidoscope::cKeyboardKey::International1
#define Key_International2 ::kaleidoscope::cKeyboardKey::International2
#define Key_International3 ::kaleidoscope::cKeyboardKey::International3
#define Key_International4 ::kaleidoscope::cKeyboardKey::International4
#define Key_International5 ::kaleidoscope::cKeyboardKey::International5
#define Key_International6 ::kaleidoscope::cKeyboardKey::International6
#define Key_International7 ::kaleidoscope::cKeyboardKey::International7
#define Key_International8 ::kaleidoscope::cKeyboardKey::International8
#define Key_International9 ::kaleidoscope::cKeyboardKey::International9
#define Key_Lang1 ::kaleidoscope::cKeyboardKey::Lang1
#define Key_Lang2 ::kaleidoscope::cKeyboardKey::Lang2
#define Key_Lang3 ::kaleidoscope::cKeyboardKey::Lang3
#define Key_Lang4 ::kaleidoscope::cKeyboardKey::Lang4
#define Key_Lang5 ::kaleidoscope::cKeyboardKey::Lang5
#define Key_Lang6 ::kaleidoscope::cKeyboardKey::Lang6
#define Key_Lang7 ::kaleidoscope::cKeyboardKey::Lang7
#define Key_Lang8 ::kaleidoscope::cKeyboardKey::Lang8
#define Key_Lang9 ::kaleidoscope::cKeyboardKey::Lang9
#define Key_AlternateErase ::kaleidoscope::cKeyboardKey::AlternateErase
#define Key_Sysreq ::kaleidoscope::cKeyboardKey::Sysreq
#define Key_Cancel ::kaleidoscope::cKeyboardKey::Cancel
#define Key_Clear ::kaleidoscope::cKeyboardKey::Clear
#define Key_Prior ::kaleidoscope::cKeyboardKey::Prior
#define Key_Return ::kaleidoscope::cKeyboardKey::Return
#define Key_Separator ::kaleidoscope::cKeyboardKey::Separator
#define Key_Out ::kaleidoscope::cKeyboardKey::Out
#define Key_Oper ::kaleidoscope::cKeyboardKey::Oper
#define Key_ClearSlashAgain ::kaleidoscope::cKeyboardKey::ClearSlashAgain
#define Key_CrselSlashProps ::kaleidoscope::cKeyboardKey::CrselSlashProps
#define Key_Exsel ::kaleidoscope::cKeyboardKey::Exsel
// Reserved	0xA5-AF
#define Key_Keypad00 ::kaleidoscope::cKeyboardKey::Keypad00
#define Key_Keypad000 ::kaleidoscope::cKeyboardKey::Keypad000
#define Key_ThousandsSeparator ::kaleidoscope::cKeyboardKey::ThousandsSeparator
#define Key_DecimalSeparator ::kaleidoscope::cKeyboardKey::DecimalSeparator
#define Key_CurrencyUnit ::kaleidoscope::cKeyboardKey::CurrencyUnit
#define Key_CurrencySubunit ::kaleidoscope::cKeyboardKey::CurrencySubunit
#define Key_KeypadLeftParen ::kaleidoscope::cKeyboardKey::KeypadLeftParen
#define Key_KeypadRightParen ::kaleidoscope::cKeyboardKey::KeypadRightParen
#define Key_KeypadLeftCurlyBrace ::kaleidoscope::cKeyboardKey::KeypadLeftCurlyBrace
#define Key_KeypadRightCurlyBrace ::kaleidoscope::cKeyboardKey::KeypadRightCurlyBrace
#define Key_KeypadTab ::kaleidoscope::cKeyboardKey::KeypadTab
#define Key_KeypadBackspace ::kaleidoscope::cKeyboardKey::KeypadBackspace
#define Key_KeypadA ::kaleidoscope::cKeyboardKey::KeypadA
#define Key_KeypadB ::kaleidoscope::cKeyboardKey::KeypadB
#define Key_KeypadC ::kaleidoscope::cKeyboardKey::KeypadC
#define Key_KeypadD ::kaleidoscope::cKeyboardKey::KeypadD
#define Key_KeypadE ::kaleidoscope::cKeyboardKey::KeypadE
#define Key_KeypadF ::kaleidoscope::cKeyboardKey::KeypadF
#define Key_KeypadXor ::kaleidoscope::cKeyboardKey::KeypadXor
#define Key_KeypadCarat ::kaleidoscope::cKeyboardKey::KeypadCarat
#define Key_KeypadPercent ::kaleidoscope::cKeyboardKey::KeypadPercent
#define Key_KeypadLessThan ::kaleidoscope::cKeyboardKey::KeypadLessThan
#define Key_KeypadGreaterThan ::kaleidoscope::cKeyboardKey::KeypadGreaterThan
#define Key_KeypadAmpersand ::kaleidoscope::cKeyboardKey::KeypadAmpersand
#define Key_KeypadDoubleampersand ::kaleidoscope::cKeyboardKey::KeypadDoubleampersand
#define Key_KeypadPipe ::kaleidoscope::cKeyboardKey::KeypadPipe
#define Key_KeypadDoublepipe ::kaleidoscope::cKeyboardKey::KeypadDoublepipe
#define Key_KeypadColon ::kaleidoscope::cKeyboardKey::KeypadColon
#define Key_KeypadPoundSign ::kaleidoscope::cKeyboardKey::KeypadPoundSign
#define Key_KeypadSpace ::kaleidoscope::cKeyboardKey::KeypadSpace
#define Key_KeypadAtSign ::kaleidoscope::cKeyboardKey::KeypadAtSign
#define Key_KeypadExclamationPoint ::kaleidoscope::cKeyboardKey::KeypadExclamationPoint
#define Key_KeypadMemoryStore ::kaleidoscope::cKeyboardKey::KeypadMemoryStore
#define Key_KeypadMemoryRecall ::kaleidoscope::cKeyboardKey::KeypadMemoryRecall
#define Key_KeypadMemoryClear ::kaleidoscope::cKeyboardKey::KeypadMemoryClear
#define Key_KeypadMemoryAdd ::kaleidoscope::cKeyboardKey::KeypadMemoryAdd
#define Key_KeypadMemorySubtract ::kaleidoscope::cKeyboardKey::KeypadMemorySubtract
#define Key_KeypadMemoryMultiply ::kaleidoscope::cKeyboardKey::KeypadMemoryMultiply
#define Key_KeypadMemoryDivide ::kaleidoscope::cKeyboardKey::KeypadMemoryDivide
#define Key_KeypadPlusSlashMinus ::kaleidoscope::cKeyboardKey::KeypadPlusSlashMinus
#define Key_KeypadClear ::kaleidoscope::cKeyboardKey::KeypadClear
#define Key_KeypadClearEntry ::kaleidoscope::cKeyboardKey::KeypadClearEntry
#define Key_KeypadBinary ::kaleidoscope::cKeyboardKey::KeypadBinary
#define Key_KeypadOctal ::kaleidoscope::cKeyboardKey::KeypadOctal
#define Key_KeypadDecimal ::kaleidoscope::cKeyboardKey::KeypadDecimal
#define Key_KeypadHexadecimal ::kaleidoscope::cKeyboardKey::KeypadHexadecimal

#define Key_LeftControl ::kaleidoscope::cKeyboardKey::LeftControl
#define Key_LeftShift ::kaleidoscope::cKeyboardKey::LeftShift
#define Key_LeftAlt ::kaleidoscope::cKeyboardKey::LeftAlt
#define Key_LeftGui ::kaleidoscope::cKeyboardKey::LeftGui
#define Key_RightControl ::kaleidoscope::cKeyboardKey::RightControl
#define Key_RightShift ::kaleidoscope::cKeyboardKey::RightShift
#define Key_RightAlt ::kaleidoscope::cKeyboardKey::RightAlt
#define Key_RightGui ::kaleidoscope::cKeyboardKey::RightGui


