#pragma once


#define Consumer_NumericKeyPad ::kaleidoscope::cKey::consumer::NumericKeyPad
#define Consumer_ProgrammableButtons ::kaleidoscope::cKey::consumer::ProgrammableButtons
#define Consumer_MicrophoneCa ::kaleidoscope::cKey::consumer::MicrophoneCa
#define Consumer_HeadphoneCa ::kaleidoscope::cKey::consumer::HeadphoneCa
#define Consumer_GraphicEqualizerCa ::kaleidoscope::cKey::consumer::GraphicEqualizerCa

#define Consumer_Plus10 ::kaleidoscope::cKey::consumer::Plus10
#define Consumer_Plus100 ::kaleidoscope::cKey::consumer::Plus100
#define Consumer_AMSlashPM ::kaleidoscope::cKey::consumer::AMSlashPM

#define Consumer_Power ::kaleidoscope::cKey::consumer::Power
#define Consumer_Reset ::kaleidoscope::cKey::consumer::Reset
#define Consumer_Sleep ::kaleidoscope::cKey::consumer::Sleep
#define Consumer_Sleep_After ::kaleidoscope::cKey::consumer::Sleep_After
#define Consumer_Sleep_Mode ::kaleidoscope::cKey::consumer::Sleep_Mode
#define Consumer_Illumination ::kaleidoscope::cKey::consumer::Illumination
#define Consumer_Function_Buttons ::kaleidoscope::cKey::consumer::Function_Buttons

#define Consumer_Menu ::kaleidoscope::cKey::consumer::Menu
#define Consumer_MenuPick ::kaleidoscope::cKey::consumer::MenuPick
#define Consumer_MenuUp ::kaleidoscope::cKey::consumer::MenuUp
#define Consumer_MenuDown ::kaleidoscope::cKey::consumer::MenuDown
#define Consumer_MenuLeft ::kaleidoscope::cKey::consumer::MenuLeft
#define Consumer_MenuRight ::kaleidoscope::cKey::consumer::MenuRight
#define Consumer_MenuEscape ::kaleidoscope::cKey::consumer::MenuEscape
#define Consumer_MenuValueIncrease ::kaleidoscope::cKey::consumer::MenuValueIncrease
#define Consumer_MenuValueDecrease ::kaleidoscope::cKey::consumer::MenuValueDecrease

#define Consumer_DataOnScreen ::kaleidoscope::cKey::consumer::DataOnScreen
#define Consumer_ClosedCaption ::kaleidoscope::cKey::consumer::ClosedCaption
#define Consumer_ClosedCaptionSelect ::kaleidoscope::cKey::consumer::ClosedCaptionSelect
#define Consumer_VCRSlashTV ::kaleidoscope::cKey::consumer::VCRSlashTV
#define Consumer_BroadcastMode ::kaleidoscope::cKey::consumer::BroadcastMode
#define Consumer_SNapshot ::kaleidoscope::cKey::consumer::SNapshot
#define Consumer_Still ::kaleidoscope::cKey::consumer::Still

#define Consumer_Selection ::kaleidoscope::cKey::consumer::Selection
#define Consumer_AssignSelection ::kaleidoscope::cKey::consumer::AssignSelection
#define Consumer_ModeStep ::kaleidoscope::cKey::consumer::ModeStep
#define Consumer_RecallLast ::kaleidoscope::cKey::consumer::RecallLast
#define Consumer_EnterChannel ::kaleidoscope::cKey::consumer::EnterChannel
#define Consumer_OrderMovie ::kaleidoscope::cKey::consumer::OrderMovie
#define Consumer_Channel ::kaleidoscope::cKey::consumer::Channel
#define Consumer_MediaSelection ::kaleidoscope::cKey::consumer::MediaSelection
#define Consumer_MediaSelectComputer ::kaleidoscope::cKey::consumer::MediaSelectComputer
#define Consumer_MediaSelectTV ::kaleidoscope::cKey::consumer::MediaSelectTV
#define Consumer_MediaSelectWww ::kaleidoscope::cKey::consumer::MediaSelectWww
#define Consumer_MediaSelectDvd ::kaleidoscope::cKey::consumer::MediaSelectDvd
#define Consumer_MediaSelectTelephone ::kaleidoscope::cKey::consumer::MediaSelectTelephone
#define Consumer_MediaSelectProgramGuide ::kaleidoscope::cKey::consumer::MediaSelectProgramGuide
#define Consumer_MediaSelectVideoPhone ::kaleidoscope::cKey::consumer::MediaSelectVideoPhone
#define Consumer_MediaSelectGames ::kaleidoscope::cKey::consumer::MediaSelectGames
#define Consumer_MediaSelectMessages ::kaleidoscope::cKey::consumer::MediaSelectMessages
#define Consumer_MediaSelectCd ::kaleidoscope::cKey::consumer::MediaSelectCd
#define Consumer_MediaSelectVcr ::kaleidoscope::cKey::consumer::MediaSelectVcr
#define Consumer_MediaSelectTuner ::kaleidoscope::cKey::consumer::MediaSelectTuner
#define Consumer_Quit ::kaleidoscope::cKey::consumer::Quit
#define Consumer_Help ::kaleidoscope::cKey::consumer::Help
#define Consumer_MediaSelectTape ::kaleidoscope::cKey::consumer::MediaSelectTape
#define Consumer_MediaSelectCable ::kaleidoscope::cKey::consumer::MediaSelectCable
#define Consumer_MediaSelectSatellite ::kaleidoscope::cKey::consumer::MediaSelectSatellite
#define Consumer_MediaSelectSecurity ::kaleidoscope::cKey::consumer::MediaSelectSecurity
#define Consumer_MediaSelectHome ::kaleidoscope::cKey::consumer::MediaSelectHome
#define Consumer_MediaSelectCall ::kaleidoscope::cKey::consumer::MediaSelectCall
#define Consumer_ChannelIncrement ::kaleidoscope::cKey::consumer::ChannelIncrement
#define Consumer_ChannelDecrement ::kaleidoscope::cKey::consumer::ChannelDecrement
#define Consumer_MediaSelectSap ::kaleidoscope::cKey::consumer::MediaSelectSap

#define Consumer_VcrPlus ::kaleidoscope::cKey::consumer::VcrPlus
#define Consumer_Once ::kaleidoscope::cKey::consumer::Once
#define Consumer_Daily ::kaleidoscope::cKey::consumer::Daily
#define Consumer_Weekly ::kaleidoscope::cKey::consumer::Weekly
#define Consumer_Monthly ::kaleidoscope::cKey::consumer::Monthly

#define Consumer_Play ::kaleidoscope::cKey::consumer::Play
#define Consumer_Pause ::kaleidoscope::cKey::consumer::Pause
#define Consumer_Record ::kaleidoscope::cKey::consumer::Record
#define Consumer_FastForward ::kaleidoscope::cKey::consumer::FastForward
#define Consumer_Rewind ::kaleidoscope::cKey::consumer::Rewind
#define Consumer_ScanNextTrack ::kaleidoscope::cKey::consumer::ScanNextTrack
#define Consumer_ScanPreviousTrack ::kaleidoscope::cKey::consumer::ScanPreviousTrack
#define Consumer_Stop ::kaleidoscope::cKey::consumer::Stop
#define Consumer_Eject ::kaleidoscope::cKey::consumer::Eject
#define Consumer_RandomPlay ::kaleidoscope::cKey::consumer::RandomPlay
#define Consumer_SelectDisc ::kaleidoscope::cKey::consumer::SelectDisc
#define Consumer_EnterDiscMc ::kaleidoscope::cKey::consumer::EnterDiscMc
#define Consumer_Repeat ::kaleidoscope::cKey::consumer::Repeat
#define Consumer_Tracking ::kaleidoscope::cKey::consumer::Tracking
#define Consumer_Track_Normal ::kaleidoscope::cKey::consumer::Track_Normal
#define Consumer_SlowTracking ::kaleidoscope::cKey::consumer::SlowTracking
#define Consumer_FrameForward ::kaleidoscope::cKey::consumer::FrameForward
#define Consumer_FrameBack ::kaleidoscope::cKey::consumer::FrameBack
#define Consumer_Mark ::kaleidoscope::cKey::consumer::Mark
#define Consumer_ClearMark ::kaleidoscope::cKey::consumer::ClearMark
#define Consumer_RepeatFromMark ::kaleidoscope::cKey::consumer::RepeatFromMark
#define Consumer_ReturnTo_Mark ::kaleidoscope::cKey::consumer::ReturnTo_Mark
#define Consumer_SearchMarkForward ::kaleidoscope::cKey::consumer::SearchMarkForward
#define Consumer_SearchMarkBackwards ::kaleidoscope::cKey::consumer::SearchMarkBackwards
#define Consumer_CounterReset ::kaleidoscope::cKey::consumer::CounterReset
#define Consumer_ShowCounter ::kaleidoscope::cKey::consumer::ShowCounter
#define Consumer_TrackingIncrement ::kaleidoscope::cKey::consumer::TrackingIncrement
#define Consumer_TrackingDecrement ::kaleidoscope::cKey::consumer::TrackingDecrement
#define Consumer_StopSlashEject ::kaleidoscope::cKey::consumer::StopSlashEject
#define Consumer_PlaySlashPause ::kaleidoscope::cKey::consumer::PlaySlashPause
#define Consumer_PlaySlashSkip ::kaleidoscope::cKey::consumer::PlaySlashSkip
#define Consumer_Volume ::kaleidoscope::cKey::consumer::Volume
#define Consumer_Balance ::kaleidoscope::cKey::consumer::Balance
#define Consumer_Mute ::kaleidoscope::cKey::consumer::Mute
#define Consumer_Bass ::kaleidoscope::cKey::consumer::Bass
#define Consumer_Treble ::kaleidoscope::cKey::consumer::Treble
#define Consumer_BassBoost ::kaleidoscope::cKey::consumer::BassBoost
#define Consumer_SurroundMode ::kaleidoscope::cKey::consumer::SurroundMode
#define Consumer_Loudness ::kaleidoscope::cKey::consumer::Loudness
#define Consumer_Mpx ::kaleidoscope::cKey::consumer::Mpx
#define Consumer_VolumeIncrement ::kaleidoscope::cKey::consumer::VolumeIncrement


#define Consumer_VolumeDecrement ::kaleidoscope::cKey::consumer::VolumeDecrement

#define Consumer_SpeedSelect ::kaleidoscope::cKey::consumer::SpeedSelect
#define Consumer_PlaybackSpeed ::kaleidoscope::cKey::consumer::PlaybackSpeed
#define Consumer_StandardPlay ::kaleidoscope::cKey::consumer::StandardPlay
#define Consumer_LongPlay ::kaleidoscope::cKey::consumer::LongPlay
#define Consumer_ExtendedPlay ::kaleidoscope::cKey::consumer::ExtendedPlay
#define Consumer_Slow ::kaleidoscope::cKey::consumer::Slow

#define Consumer_FanEnable ::kaleidoscope::cKey::consumer::FanEnable
#define Consumer_FanSpeed ::kaleidoscope::cKey::consumer::FanSpeed
#define Consumer_LightEnable ::kaleidoscope::cKey::consumer::LightEnable
#define Consumer_LightIlluminationLevel ::kaleidoscope::cKey::consumer::LightIlluminationLevel
#define Consumer_ClimateControlEnable ::kaleidoscope::cKey::consumer::ClimateControlEnable
#define Consumer_RoomTemperature ::kaleidoscope::cKey::consumer::RoomTemperature
#define Consumer_SecurityEnable ::kaleidoscope::cKey::consumer::SecurityEnable
#define Consumer_FireAlarm ::kaleidoscope::cKey::consumer::FireAlarm
#define Consumer_PoliceAlarm ::kaleidoscope::cKey::consumer::PoliceAlarm
#define Consumer_Proximity ::kaleidoscope::cKey::consumer::Proximity
#define Consumer_Motion ::kaleidoscope::cKey::consumer::Motion
#define Consumer_DuressAlarm ::kaleidoscope::cKey::consumer::DuressAlarm
#define Consumer_HoldupAlarm ::kaleidoscope::cKey::consumer::HoldupAlarm
#define Consumer_MedicalAlarm ::kaleidoscope::cKey::consumer::MedicalAlarm

#define Consumer_BalanceRight ::kaleidoscope::cKey::consumer::BalanceRight
#define Consumer_BalanceLeft ::kaleidoscope::cKey::consumer::BalanceLeft
#define Consumer_BassIncrement ::kaleidoscope::cKey::consumer::BassIncrement
#define Consumer_BassDecrement ::kaleidoscope::cKey::consumer::BassDecrement
#define Consumer_TrebleIncrement ::kaleidoscope::cKey::consumer::TrebleIncrement
#define Consumer_TrebleDecrement ::kaleidoscope::cKey::consumer::TrebleDecrement

#define Consumer_SpeakerSystem ::kaleidoscope::cKey::consumer::SpeakerSystem
#define Consumer_ChannelLeft ::kaleidoscope::cKey::consumer::ChannelLeft
#define Consumer_ChannelRight ::kaleidoscope::cKey::consumer::ChannelRight
#define Consumer_ChannelCenter ::kaleidoscope::cKey::consumer::ChannelCenter
#define Consumer_ChannelFront ::kaleidoscope::cKey::consumer::ChannelFront
#define Consumer_ChannelCenterFront ::kaleidoscope::cKey::consumer::ChannelCenterFront
#define Consumer_ChannelSide ::kaleidoscope::cKey::consumer::ChannelSide
#define Consumer_ChannelSurround ::kaleidoscope::cKey::consumer::ChannelSurround
#define Consumer_ChannelLowFrequencyEnhancement ::kaleidoscope::cKey::consumer::ChannelLowFrequencyEnhancement
#define Consumer_ChannelTop ::kaleidoscope::cKey::consumer::ChannelTop
#define Consumer_ChannelUnknown ::kaleidoscope::cKey::consumer::ChannelUnknown

#define Consumer_SubChannel ::kaleidoscope::cKey::consumer::SubChannel
#define Consumer_SubChannelIncrement ::kaleidoscope::cKey::consumer::SubChannelIncrement
#define Consumer_SubChannelDecrement ::kaleidoscope::cKey::consumer::SubChannelDecrement
#define Consumer_AlternateAudioIncrement ::kaleidoscope::cKey::consumer::AlternateAudioIncrement
#define Consumer_AlternateAudioDecrement ::kaleidoscope::cKey::consumer::AlternateAudioDecrement

#define Consumer_Application_Launch_Buttons ::kaleidoscope::cKey::consumer::Application_Launch_Buttons
#define Consumer_AL_Launch_Button_Configuration_Tool ::kaleidoscope::cKey::consumer::AL_Launch_Button_Configuration_Tool
#define Consumer_AL_Programmable_Button_Configuration ::kaleidoscope::cKey::consumer::AL_Programmable_Button_Configuration
#define Consumer_AL_Consumer_Control_Configuration ::kaleidoscope::cKey::consumer::AL_Consumer_Control_Configuration
#define Consumer_AL_Word_Processor ::kaleidoscope::cKey::consumer::AL_Word_Processor
#define Consumer_AL_Text_Editor ::kaleidoscope::cKey::consumer::AL_Text_Editor
#define Consumer_AL_Spreadsheet ::kaleidoscope::cKey::consumer::AL_Spreadsheet
#define Consumer_AL_Graphics_Editor ::kaleidoscope::cKey::consumer::AL_Graphics_Editor
#define Consumer_AL_Presentation_App ::kaleidoscope::cKey::consumer::AL_Presentation_App
#define Consumer_AL_Database_App ::kaleidoscope::cKey::consumer::AL_Database_App
#define Consumer_AL_Email_Reader ::kaleidoscope::cKey::consumer::AL_Email_Reader
#define Consumer_AL_Newsreader ::kaleidoscope::cKey::consumer::AL_Newsreader
#define Consumer_AL_Voicemail ::kaleidoscope::cKey::consumer::AL_Voicemail
#define Consumer_AL_Contacts_Slash_Address_Book ::kaleidoscope::cKey::consumer::AL_Contacts_Slash_Address_Book
#define Consumer_AL_Calendar_Slash_Schedule ::kaleidoscope::cKey::consumer::AL_Calendar_Slash_Schedule
#define Consumer_AL_Task_Slash_Project_Manager ::kaleidoscope::cKey::consumer::AL_Task_Slash_Project_Manager
#define Consumer_AL_Log_Slash_Journal_Slash_Timecard ::kaleidoscope::cKey::consumer::AL_Log_Slash_Journal_Slash_Timecard
#define Consumer_AL_Checkbook_Slash_Finance ::kaleidoscope::cKey::consumer::AL_Checkbook_Slash_Finance
#define Consumer_AL_Calculator ::kaleidoscope::cKey::consumer::AL_Calculator
#define Consumer_AL_AVCaptureSlashPlayback ::kaleidoscope::cKey::consumer::AL_AVCaptureSlashPlayback
#define Consumer_AL_Local_MachineBrowser ::kaleidoscope::cKey::consumer::AL_Local_MachineBrowser
#define Consumer_AL_Lan_SlashWanBrowser ::kaleidoscope::cKey::consumer::AL_Lan_SlashWanBrowser
#define Consumer_AL_InternetBrowser ::kaleidoscope::cKey::consumer::AL_InternetBrowser
#define Consumer_AL_RemoteNetworkingSlashIspConnect ::kaleidoscope::cKey::consumer::AL_RemoteNetworkingSlashIspConnect
#define Consumer_AL_NetworkConference ::kaleidoscope::cKey::consumer::AL_NetworkConference
#define Consumer_AL_NetworkChat ::kaleidoscope::cKey::consumer::AL_NetworkChat
#define Consumer_AL_TelephonySlashDialer ::kaleidoscope::cKey::consumer::AL_TelephonySlashDialer
#define Consumer_AL_Logon ::kaleidoscope::cKey::consumer::AL_Logon
#define Consumer_AL_Logoff ::kaleidoscope::cKey::consumer::AL_Logoff
#define Consumer_AL_LogonSlashLogoff ::kaleidoscope::cKey::consumer::AL_LogonSlashLogoff
#define Consumer_AL_TerminalLockSlashScreensaver ::kaleidoscope::cKey::consumer::AL_TerminalLockSlashScreensaver
#define Consumer_AL_ControlPanel ::kaleidoscope::cKey::consumer::AL_ControlPanel
#define Consumer_AL_CommandLineProcessorSlashRun ::kaleidoscope::cKey::consumer::AL_CommandLineProcessorSlashRun
#define Consumer_AL_ProcessSlashTask_Manager ::kaleidoscope::cKey::consumer::AL_ProcessSlashTask_Manager
#define Consumer_AL_SelectTaskSlashApplication ::kaleidoscope::cKey::consumer::AL_SelectTaskSlashApplication
#define Consumer_AL_NextTaskSlashApplication ::kaleidoscope::cKey::consumer::AL_NextTaskSlashApplication
#define Consumer_AL_PreviousTaskSlashApplication ::kaleidoscope::cKey::consumer::AL_PreviousTaskSlashApplication
#define Consumer_AL_PreemptiveHaltTaskSlashApplication ::kaleidoscope::cKey::consumer::AL_PreemptiveHaltTaskSlashApplication
#define Consumer_AL_IntegratedHelpCenter ::kaleidoscope::cKey::consumer::AL_IntegratedHelpCenter
#define Consumer_AL_Documents ::kaleidoscope::cKey::consumer::AL_Documents
#define Consumer_AL_Thesaurus ::kaleidoscope::cKey::consumer::AL_Thesaurus
#define Consumer_AL_Dictionary ::kaleidoscope::cKey::consumer::AL_Dictionary
#define Consumer_AL_Desktop ::kaleidoscope::cKey::consumer::AL_Desktop
#define Consumer_AL_SpellCheck ::kaleidoscope::cKey::consumer::AL_SpellCheck
#define Consumer_AL_GrammarCheck ::kaleidoscope::cKey::consumer::AL_GrammarCheck
#define Consumer_AL_WirelessStatus ::kaleidoscope::cKey::consumer::AL_WirelessStatus
#define Consumer_AL_KeyboardLayout ::kaleidoscope::cKey::consumer::AL_KeyboardLayout
#define Consumer_AL_VirusProtection ::kaleidoscope::cKey::consumer::AL_VirusProtection
#define Consumer_AL_Encryption ::kaleidoscope::cKey::consumer::AL_Encryption
#define Consumer_AL_ScreenSaver ::kaleidoscope::cKey::consumer::AL_ScreenSaver
#define Consumer_AL_Alarms ::kaleidoscope::cKey::consumer::AL_Alarms
#define Consumer_AL_Clock ::kaleidoscope::cKey::consumer::AL_Clock
#define Consumer_AL_FileBrowser ::kaleidoscope::cKey::consumer::AL_FileBrowser
#define Consumer_AL_PowerStatus ::kaleidoscope::cKey::consumer::AL_PowerStatus
#define Consumer_AL_ImageBrowser ::kaleidoscope::cKey::consumer::AL_ImageBrowser
#define Consumer_AL_AudioBrowser ::kaleidoscope::cKey::consumer::AL_AudioBrowser
#define Consumer_AL_MovieBrowser ::kaleidoscope::cKey::consumer::AL_MovieBrowser
#define Consumer_AL_DigitalRightsManager ::kaleidoscope::cKey::consumer::AL_DigitalRightsManager
#define Consumer_AL_DigitalWallet ::kaleidoscope::cKey::consumer::AL_DigitalWallet

#define Consumer_AL_InstantMessaging ::kaleidoscope::cKey::consumer::AL_InstantMessaging
#define Consumer_AL_OemFeaturesSlashTipsSlashTUTORIALBrowser ::kaleidoscope::cKey::consumer::AL_OemFeaturesSlashTipsSlashTUTORIALBrowser
#define Consumer_AL_OemHelp ::kaleidoscope::cKey::consumer::AL_OemHelp
#define Consumer_AL_OnlineCommunity ::kaleidoscope::cKey::consumer::AL_OnlineCommunity
#define Consumer_AL_Entertainment_Content_Browser ::kaleidoscope::cKey::consumer::AL_Entertainment_Content_Browser
#define Consumer_AL_OnlineShoppingBrowser ::kaleidoscope::cKey::consumer::AL_OnlineShoppingBrowser
#define Consumer_AL_SmartcardInformationSlashHelp ::kaleidoscope::cKey::consumer::AL_SmartcardInformationSlashHelp
#define Consumer_AL_MarketMonitorSlashFinanceBrowser ::kaleidoscope::cKey::consumer::AL_MarketMonitorSlashFinanceBrowser
#define Consumer_AL_CustomizedCorporateNewsBrowser ::kaleidoscope::cKey::consumer::AL_CustomizedCorporateNewsBrowser
#define Consumer_AL_OnlineActivityBrowser ::kaleidoscope::cKey::consumer::AL_OnlineActivityBrowser
#define Consumer_AL_ResearchSlashSearchBrowser ::kaleidoscope::cKey::consumer::AL_ResearchSlashSearchBrowser
#define Consumer_AL_AudioPlayer ::kaleidoscope::cKey::consumer::AL_AudioPlayer

#define Consumer_GenericGuiApplicationControls ::kaleidoscope::cKey::consumer::GenericGuiApplicationControls
#define Consumer_AC_New ::kaleidoscope::cKey::consumer::AC_New
#define Consumer_AC_Open ::kaleidoscope::cKey::consumer::AC_Open
#define Consumer_AC_Close ::kaleidoscope::cKey::consumer::AC_Close
#define Consumer_AC_Exit ::kaleidoscope::cKey::consumer::AC_Exit
#define Consumer_AC_Maximize ::kaleidoscope::cKey::consumer::AC_Maximize
#define Consumer_AC_Minimize ::kaleidoscope::cKey::consumer::AC_Minimize
#define Consumer_AC_Save ::kaleidoscope::cKey::consumer::AC_Save
#define Consumer_AC_Print ::kaleidoscope::cKey::consumer::AC_Print
#define Consumer_AC_Properties ::kaleidoscope::cKey::consumer::AC_Properties
#define Consumer_AC_Undo ::kaleidoscope::cKey::consumer::AC_Undo
#define Consumer_AC_Copy ::kaleidoscope::cKey::consumer::AC_Copy
#define Consumer_AC_Cut ::kaleidoscope::cKey::consumer::AC_Cut
#define Consumer_AC_Paste ::kaleidoscope::cKey::consumer::AC_Paste
#define Consumer_AC_SelectAll ::kaleidoscope::cKey::consumer::AC_SelectAll
#define Consumer_AC_Find ::kaleidoscope::cKey::consumer::AC_Find
#define Consumer_AC_FindAndReplace ::kaleidoscope::cKey::consumer::AC_FindAndReplace
#define Consumer_AC_Search ::kaleidoscope::cKey::consumer::AC_Search
#define Consumer_AC_GoTo ::kaleidoscope::cKey::consumer::AC_GoTo
#define Consumer_AC_Home ::kaleidoscope::cKey::consumer::AC_Home
#define Consumer_AC_Back ::kaleidoscope::cKey::consumer::AC_Back
#define Consumer_AC_Forward ::kaleidoscope::cKey::consumer::AC_Forward
#define Consumer_AC_Stop ::kaleidoscope::cKey::consumer::AC_Stop
#define Consumer_AC_Refresh ::kaleidoscope::cKey::consumer::AC_Refresh
#define Consumer_AC_PreviousLink ::kaleidoscope::cKey::consumer::AC_PreviousLink
#define Consumer_AC_NextLink ::kaleidoscope::cKey::consumer::AC_NextLink
#define Consumer_AC_Bookmarks ::kaleidoscope::cKey::consumer::AC_Bookmarks
#define Consumer_AC_History ::kaleidoscope::cKey::consumer::AC_History
#define Consumer_AC_Subscriptions ::kaleidoscope::cKey::consumer::AC_Subscriptions
#define Consumer_AC_ZoomIn ::kaleidoscope::cKey::consumer::AC_ZoomIn
#define Consumer_AC_ZoomOut ::kaleidoscope::cKey::consumer::AC_ZoomOut
#define Consumer_AC_Zoom ::kaleidoscope::cKey::consumer::AC_Zoom
#define Consumer_AC_FullSCreenView ::kaleidoscope::cKey::consumer::AC_FullSCreenView
#define Consumer_AC_NormalView ::kaleidoscope::cKey::consumer::AC_NormalView
#define Consumer_AC_ViewToggle ::kaleidoscope::cKey::consumer::AC_ViewToggle
#define Consumer_AC_ScrollUp ::kaleidoscope::cKey::consumer::AC_ScrollUp
#define Consumer_AC_ScrollDown ::kaleidoscope::cKey::consumer::AC_ScrollDown
#define Consumer_AC_Scroll ::kaleidoscope::cKey::consumer::AC_Scroll
#define Consumer_AC_PanLeft ::kaleidoscope::cKey::consumer::AC_PanLeft
#define Consumer_AC_PanRight ::kaleidoscope::cKey::consumer::AC_PanRight
#define Consumer_AC_Pan ::kaleidoscope::cKey::consumer::AC_Pan
#define Consumer_AC_NewWindow ::kaleidoscope::cKey::consumer::AC_NewWindow
#define Consumer_AC_TileHorizontally ::kaleidoscope::cKey::consumer::AC_TileHorizontally
#define Consumer_AC_TileVertically ::kaleidoscope::cKey::consumer::AC_TileVertically
#define Consumer_AC_Format ::kaleidoscope::cKey::consumer::AC_Format
#define Consumer_AC_Edit ::kaleidoscope::cKey::consumer::AC_Edit
#define Consumer_AC_Bold ::kaleidoscope::cKey::consumer::AC_Bold
#define Consumer_AC_Italics ::kaleidoscope::cKey::consumer::AC_Italics
#define Consumer_AC_Underline ::kaleidoscope::cKey::consumer::AC_Underline
#define Consumer_AC_Strikethrough ::kaleidoscope::cKey::consumer::AC_Strikethrough
#define Consumer_AC_Subscript ::kaleidoscope::cKey::consumer::AC_Subscript
#define Consumer_AC_Superscript ::kaleidoscope::cKey::consumer::AC_Superscript
#define Consumer_AC_AllCaps ::kaleidoscope::cKey::consumer::AC_AllCaps
#define Consumer_AC_Rotate ::kaleidoscope::cKey::consumer::AC_Rotate
#define Consumer_AC_Resize ::kaleidoscope::cKey::consumer::AC_Resize
#define Consumer_AC_FlipHorizontal ::kaleidoscope::cKey::consumer::AC_FlipHorizontal
#define Consumer_AC_FlipVertical ::kaleidoscope::cKey::consumer::AC_FlipVertical
#define Consumer_AC_MirrorHorizontal ::kaleidoscope::cKey::consumer::AC_MirrorHorizontal
#define Consumer_AC_MirrorVertical ::kaleidoscope::cKey::consumer::AC_MirrorVertical
#define Consumer_AC_FontSelect ::kaleidoscope::cKey::consumer::AC_FontSelect
#define Consumer_AC_FontColor ::kaleidoscope::cKey::consumer::AC_FontColor
#define Consumer_AC_FontSize ::kaleidoscope::cKey::consumer::AC_FontSize
#define Consumer_AC_JustifyLeft ::kaleidoscope::cKey::consumer::AC_JustifyLeft
#define Consumer_AC_JustifyCenterH ::kaleidoscope::cKey::consumer::AC_JustifyCenterH
#define Consumer_AC_JustifyRight ::kaleidoscope::cKey::consumer::AC_JustifyRight
#define Consumer_AC_JustifyBlockH ::kaleidoscope::cKey::consumer::AC_JustifyBlockH
#define Consumer_AC_JustifyTop ::kaleidoscope::cKey::consumer::AC_JustifyTop
#define Consumer_AC_JustifyCenterV ::kaleidoscope::cKey::consumer::AC_JustifyCenterV
#define Consumer_AC_JustifyBottom ::kaleidoscope::cKey::consumer::AC_JustifyBottom
#define Consumer_AC_JustifyBlockV ::kaleidoscope::cKey::consumer::AC_JustifyBlockV
#define Consumer_AC_IndentDecrease ::kaleidoscope::cKey::consumer::AC_IndentDecrease
#define Consumer_AC_IndentIncrease ::kaleidoscope::cKey::consumer::AC_IndentIncrease
#define Consumer_AC_NumberedList ::kaleidoscope::cKey::consumer::AC_NumberedList
#define Consumer_AC_RestartNumbering ::kaleidoscope::cKey::consumer::AC_RestartNumbering
#define Consumer_AC_BulletedList ::kaleidoscope::cKey::consumer::AC_BulletedList
#define Consumer_AC_Promote ::kaleidoscope::cKey::consumer::AC_Promote
#define Consumer_AC_Demote ::kaleidoscope::cKey::consumer::AC_Demote
#define Consumer_AC_Yes ::kaleidoscope::cKey::consumer::AC_Yes
#define Consumer_AC_No ::kaleidoscope::cKey::consumer::AC_No
#define Consumer_AC_Cancel ::kaleidoscope::cKey::consumer::AC_Cancel
#define Consumer_AC_Catalog ::kaleidoscope::cKey::consumer::AC_Catalog
#define Consumer_AC_BuySlashCheckout ::kaleidoscope::cKey::consumer::AC_BuySlashCheckout
#define Consumer_AC_AddToCart ::kaleidoscope::cKey::consumer::AC_AddToCart
#define Consumer_AC_Expand ::kaleidoscope::cKey::consumer::AC_Expand
#define Consumer_AC_ExpandAll ::kaleidoscope::cKey::consumer::AC_ExpandAll
#define Consumer_AC_Collapse ::kaleidoscope::cKey::consumer::AC_Collapse
#define Consumer_AC_CollapseAll ::kaleidoscope::cKey::consumer::AC_CollapseAll
#define Consumer_AC_PrintPreview ::kaleidoscope::cKey::consumer::AC_PrintPreview
#define Consumer_AC_PasteSpecial ::kaleidoscope::cKey::consumer::AC_PasteSpecial
#define Consumer_AC_InsertMode ::kaleidoscope::cKey::consumer::AC_InsertMode
#define Consumer_AC_Delete ::kaleidoscope::cKey::consumer::AC_Delete
#define Consumer_AC_Lock ::kaleidoscope::cKey::consumer::AC_Lock
#define Consumer_AC_Unlock ::kaleidoscope::cKey::consumer::AC_Unlock
#define Consumer_AC_Protect ::kaleidoscope::cKey::consumer::AC_Protect
#define Consumer_AC_Unprotect ::kaleidoscope::cKey::consumer::AC_Unprotect
#define Consumer_AC_AttachComment ::kaleidoscope::cKey::consumer::AC_AttachComment
#define Consumer_AC_DeleteComment ::kaleidoscope::cKey::consumer::AC_DeleteComment
#define Consumer_AC_ViewComment ::kaleidoscope::cKey::consumer::AC_ViewComment
#define Consumer_AC_SelectWord ::kaleidoscope::cKey::consumer::AC_SelectWord
#define Consumer_AC_SelectSentence ::kaleidoscope::cKey::consumer::AC_SelectSentence
#define Consumer_AC_SelectParagraph ::kaleidoscope::cKey::consumer::AC_SelectParagraph
#define Consumer_AC_SelectColumn ::kaleidoscope::cKey::consumer::AC_SelectColumn
#define Consumer_AC_SelectRow ::kaleidoscope::cKey::consumer::AC_SelectRow
#define Consumer_AC_SelectTable ::kaleidoscope::cKey::consumer::AC_SelectTable
#define Consumer_AC_SelectObject ::kaleidoscope::cKey::consumer::AC_SelectObject
#define Consumer_AC_RedoSlashRepeat ::kaleidoscope::cKey::consumer::AC_RedoSlashRepeat
#define Consumer_AC_Sort ::kaleidoscope::cKey::consumer::AC_Sort
#define Consumer_AC_Sort_Ascending ::kaleidoscope::cKey::consumer::AC_Sort_Ascending
#define Consumer_AC_Sort_Descending ::kaleidoscope::cKey::consumer::AC_Sort_Descending
#define Consumer_AC_Filter ::kaleidoscope::cKey::consumer::AC_Filter
#define Consumer_AC_SetClock ::kaleidoscope::cKey::consumer::AC_SetClock
#define Consumer_AC_ViewClock ::kaleidoscope::cKey::consumer::AC_ViewClock
#define Consumer_AC_SelectTimeZone ::kaleidoscope::cKey::consumer::AC_SelectTimeZone
#define Consumer_AC_EditTimeZones ::kaleidoscope::cKey::consumer::AC_EditTimeZones
#define Consumer_AC_SetAlarm ::kaleidoscope::cKey::consumer::AC_SetAlarm
#define Consumer_AC_ClearAlarm ::kaleidoscope::cKey::consumer::AC_ClearAlarm
#define Consumer_AC_SnoozeAlarm ::kaleidoscope::cKey::consumer::AC_SnoozeAlarm
#define Consumer_AC_ResetAlarm ::kaleidoscope::cKey::consumer::AC_ResetAlarm
#define Consumer_AC_Synchronize ::kaleidoscope::cKey::consumer::AC_Synchronize
#define Consumer_AC_SendSlashReceive ::kaleidoscope::cKey::consumer::AC_SendSlashReceive
#define Consumer_AC_SendTo ::kaleidoscope::cKey::consumer::AC_SendTo
#define Consumer_AC_Reply ::kaleidoscope::cKey::consumer::AC_Reply
#define Consumer_AC_ReplyAll ::kaleidoscope::cKey::consumer::AC_ReplyAll
#define Consumer_AC_ForwardMsg ::kaleidoscope::cKey::consumer::AC_ForwardMsg
#define Consumer_AC_Send ::kaleidoscope::cKey::consumer::AC_Send
#define Consumer_AC_AttachFile ::kaleidoscope::cKey::consumer::AC_AttachFile
#define Consumer_AC_Upload ::kaleidoscope::cKey::consumer::AC_Upload
#define Consumer_AC_Download ::kaleidoscope::cKey::consumer::AC_Download
#define Consumer_AC_SetBorders ::kaleidoscope::cKey::consumer::AC_SetBorders
#define Consumer_AC_InsertRow ::kaleidoscope::cKey::consumer::AC_InsertRow
#define Consumer_AC_InsertColumn ::kaleidoscope::cKey::consumer::AC_InsertColumn
#define Consumer_AC_InsertFile ::kaleidoscope::cKey::consumer::AC_InsertFile
#define Consumer_AC_InsertPicture ::kaleidoscope::cKey::consumer::AC_InsertPicture
#define Consumer_AC_InsertObject ::kaleidoscope::cKey::consumer::AC_InsertObject
#define Consumer_AC_InsertSymbol ::kaleidoscope::cKey::consumer::AC_InsertSymbol
#define Consumer_AC_SaveandClose ::kaleidoscope::cKey::consumer::AC_SaveandClose
#define Consumer_AC_Rename ::kaleidoscope::cKey::consumer::AC_Rename
#define Consumer_AC_Merge ::kaleidoscope::cKey::consumer::AC_Merge
#define Consumer_AC_Split ::kaleidoscope::cKey::consumer::AC_Split
#define Consumer_AC_Distribute_Horizontally ::kaleidoscope::cKey::consumer::AC_Distribute_Horizontally
#define Consumer_AC_Distribute_Vertically ::kaleidoscope::cKey::consumer::AC_Distribute_Vertically
